; ======================================================
; Streaming HTTP response parser used by DLSPEED and its host-side Z80 tests.
; It accepts one HTTP/1.x 2xx response with a non-zero Content-Length, rejects
; transfer/content encodings, and counts exactly the announced body bytes.
;
; API:
;   HL=header buffer, DE=capacity; CALL DHTTP.RESET
;   HL=data, BC=size;             CALL DHTTP.CONSUME
;     CF=0/A=0: need more data
;     CF=0/A=1: Content-Length reached exactly
;     CF=1/A=DHTTP_ERR_*: invalid/unsupported response
; ======================================================

	IFNDEF	_DLSPEED_HTTP
	DEFINE	_DLSPEED_HTTP

DHTTP_ERR_STATUS	EQU 1
DHTTP_ERR_LENGTH_MISSING EQU 2
DHTTP_ERR_LENGTH_ZERO	EQU 3
DHTTP_ERR_TRANSFER_ENCODING EQU 4
DHTTP_ERR_CONTENT_ENCODING EQU 5
DHTTP_ERR_HEADER_LARGE	EQU 6
DHTTP_ERR_LENGTH_INVALID EQU 7

	MODULE DHTTP

RESET
	LD	(HEADER_BASE),HL
	LD	(HEADER_CAP),DE
	XOR	A
	LD	(PHASE),A
	LD	(SEARCH_STATE),A
	LD	(HDR_STATE),A
	LD	(DONE),A
	LD	(ERROR),A
	LD	(CONTENT_LENGTH_SEEN),A
	LD	(HEADER_LEN),A
	LD	(HEADER_LEN+1),A
	LD	(CONTENT_LENGTH),A
	LD	(CONTENT_LENGTH+1),A
	LD	(CONTENT_LENGTH+2),A
	LD	(CONTENT_LENGTH+3),A
	LD	(BODY_BYTES),A
	LD	(BODY_BYTES+1),A
	LD	(BODY_BYTES+2),A
	LD	(BODY_BYTES+3),A
	RET

CONSUME
	LD	(INPUT_PTR),HL
	LD	(INPUT_LEFT),BC
.LOOP
	LD	A,(DONE)
	OR	A
	JR	NZ,.COMPLETE
	LD	BC,(INPUT_LEFT)
	LD	A,B
	OR	C
	JR	Z,.MORE
	LD	A,(PHASE)
	OR	A
	JR	Z,.SEEK
	CP	1
	JR	Z,.HEADER
	CALL	COUNT_BODY_INPUT
	JR	.LOOP
.SEEK
	CALL	TAKE_BYTE
	CALL	SEEK_HTTP_BYTE
	JR	.LOOP
.HEADER
	CALL	TAKE_BYTE
	CALL	APPEND_HEADER_BYTE
	JR	C,.FAIL
	LD	A,(PHASE)
	CP	2
	JR	NZ,.LOOP
	CALL	VALIDATE_HEADER
	JR	C,.FAIL
	JR	.LOOP
.MORE
	XOR	A
	RET
.COMPLETE
	LD	A,1
	OR	A
	RET
.FAIL
	LD	(ERROR),A
	SCF
	RET

; Return next input byte in A and consume it. Preserves DE/HL except scratch.
TAKE_BYTE
	LD	HL,(INPUT_PTR)
	LD	A,(HL)
	INC	HL
	LD	(INPUT_PTR),HL
	LD	HL,(INPUT_LEFT)
	DEC	HL
	LD	(INPUT_LEFT),HL
	RET

; Ignore ESP command text before the HTTP status.  Begin buffering only after
; the complete "HTTP/" marker, which may itself cross TCP receive blocks.
SEEK_HTTP_BYTE
	LD	E,A
	LD	A,(SEARCH_STATE)
	LD	C,A
	LD	B,0
	LD	HL,HTTP_PREFIX
	ADD	HL,BC
	LD	A,(HL)
	CP	E
	JR	NZ,.MISMATCH
	INC	C
	LD	A,C
	LD	(SEARCH_STATE),A
	CP	5
	RET	NZ
	LD	HL,(HEADER_BASE)
	EX	DE,HL
	LD	HL,HTTP_PREFIX
	LD	BC,5
	LDIR
	LD	HL,5
	LD	(HEADER_LEN),HL
	LD	A,1
	LD	(PHASE),A
	RET
.MISMATCH
	XOR	A
	LD	(SEARCH_STATE),A
	LD	A,E
	CP	'H'
	RET	NZ
	LD	A,1
	LD	(SEARCH_STATE),A
	RET

APPEND_HEADER_BYTE
	LD	(LAST_BYTE),A
	LD	HL,(HEADER_CAP)
	DEC	HL			; reserve ASCIIZ terminator
	LD	DE,(HEADER_LEN)
	OR	A
	SBC	HL,DE
	JR	C,.TOO_LARGE
	JR	Z,.TOO_LARGE
	LD	HL,(HEADER_BASE)
	ADD	HL,DE
	LD	A,(LAST_BYTE)
	LD	(HL),A
	LD	HL,(HEADER_LEN)
	INC	HL
	LD	(HEADER_LEN),HL
	LD	A,(LAST_BYTE)
	CALL	UPDATE_HEADER_STATE
	LD	A,(HDR_STATE)
	CP	4
	JR	Z,.HEADER_DONE
	OR	A			; normal partial header, CF=0
	RET
.HEADER_DONE
	LD	HL,(HEADER_BASE)
	LD	DE,(HEADER_LEN)
	ADD	HL,DE
	LD	(HL),0
	LD	A,2
	LD	(PHASE),A
	OR	A
	RET
.TOO_LARGE
	LD	A,DHTTP_ERR_HEADER_LARGE
	SCF
	RET

; Track CR LF CR LF; state 4 is terminal.
UPDATE_HEADER_STATE
	LD	E,A
	LD	A,(HDR_STATE)
	OR	A
	JR	Z,.S0
	CP	1
	JR	Z,.S1
	CP	2
	JR	Z,.S2
	CP	3
	JR	Z,.S3
	RET
.S0
	LD	A,E
	CP	13
	JR	Z,.SET1
	XOR	A
	JR	.STORE
.S1
	LD	A,E
	CP	10
	JR	Z,.SET2
	CP	13
	JR	Z,.SET1
	XOR	A
	JR	.STORE
.S2
	LD	A,E
	CP	13
	JR	Z,.SET3
	XOR	A
	JR	.STORE
.S3
	LD	A,E
	CP	10
	JR	Z,.SET4
	CP	13
	JR	Z,.SET3
	XOR	A
	JR	.STORE
.SET1
	LD	A,1
	JR	.STORE
.SET2
	LD	A,2
	JR	.STORE
.SET3
	LD	A,3
	JR	.STORE
.SET4
	LD	A,4
.STORE
	LD	(HDR_STATE),A
	RET

; Validate status and supported framing after the whole header is buffered.
VALIDATE_HEADER
	LD	HL,(HEADER_BASE)
	LD	B,32
.STATUS_SPACE
	LD	A,(HL)
	CP	' '
	JR	Z,.STATUS_CODE
	CP	13
	JR	Z,.BAD_STATUS
	OR	A
	JR	Z,.BAD_STATUS
	INC	HL
	DJNZ	.STATUS_SPACE
.BAD_STATUS
	LD	A,DHTTP_ERR_STATUS
	SCF
	RET
.STATUS_CODE
	INC	HL
.STATUS_SKIP
	LD	A,(HL)
	CP	' '
	JR	NZ,.STATUS_TEST
	INC	HL
	JR	.STATUS_SKIP
.STATUS_TEST
	CP	'2'
	JR	NZ,.BAD_STATUS
	INC	HL
	LD	A,(HL)
	CP	'0'
	JR	C,.BAD_STATUS
	CP	'9'+1
	JR	NC,.BAD_STATUS
	INC	HL
	LD	A,(HL)
	CP	'0'
	JR	C,.BAD_STATUS
	CP	'9'+1
	JR	NC,.BAD_STATUS

	; Move to the first header line.
	LD	HL,(HEADER_BASE)
	CALL	NEXT_LINE
.LINE_LOOP
	LD	A,(HL)
	CP	13
	JR	Z,.LINES_DONE
	OR	A
	JR	Z,.LINES_DONE
	PUSH	HL
	LD	DE,H_CONTENT_LENGTH
	CALL	MATCH_PREFIX_CI
	JR	Z,.CONTENT_LENGTH
	POP	HL
	PUSH	HL
	LD	DE,H_TRANSFER_ENCODING
	CALL	MATCH_PREFIX_CI
	JR	Z,.TRANSFER_ENCODING
	POP	HL
	PUSH	HL
	LD	DE,H_CONTENT_ENCODING
	CALL	MATCH_PREFIX_CI
	JR	Z,.CONTENT_ENCODING
	POP	HL
.NEXT_LINE
	CALL	NEXT_LINE
	JR	.LINE_LOOP

.CONTENT_LENGTH
	POP	DE			; discard saved line pointer
	CALL	SKIP_VALUE_SPACE
	CALL	PARSE_CONTENT_LENGTH
	RET	C
	LD	A,1
	LD	(CONTENT_LENGTH_SEEN),A
	JR	.NEXT_LINE

.TRANSFER_ENCODING
	POP	DE
	LD	A,DHTTP_ERR_TRANSFER_ENCODING
	SCF
	RET

.CONTENT_ENCODING
	POP	DE
	CALL	SKIP_VALUE_SPACE
	LD	DE,V_IDENTITY
	CALL	MATCH_TOKEN_CI
	JR	NZ,.BAD_ENCODING
	CALL	SKIP_VALUE_SPACE
	LD	A,(HL)
	CP	13
	JR	Z,.NEXT_LINE
	OR	A
	JR	Z,.NEXT_LINE
.BAD_ENCODING
	LD	A,DHTTP_ERR_CONTENT_ENCODING
	SCF
	RET

.LINES_DONE
	LD	A,(CONTENT_LENGTH_SEEN)
	OR	A
	JR	Z,.MISSING_LENGTH
	LD	HL,CONTENT_LENGTH
	LD	A,(HL)
	INC	HL
	OR	(HL)
	INC	HL
	OR	(HL)
	INC	HL
	OR	(HL)
	JR	Z,.ZERO_LENGTH
	XOR	A
	RET
.MISSING_LENGTH
	LD	A,DHTTP_ERR_LENGTH_MISSING
	SCF
	RET
.ZERO_LENGTH
	LD	A,DHTTP_ERR_LENGTH_ZERO
	SCF
	RET

; Advance HL to the byte after the next LF (or to ASCIIZ end).
NEXT_LINE
	LD	A,(HL)
	OR	A
	RET	Z
	INC	HL
	CP	10
	JR	NZ,NEXT_LINE
	RET

MATCH_PREFIX_CI
	LD	A,(DE)
	OR	A
	RET	Z
	LD	C,A
	LD	A,(HL)
	CALL	ASCII_LOWER
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	JR	MATCH_PREFIX_CI

MATCH_TOKEN_CI
	LD	A,(DE)
	OR	A
	RET	Z
	LD	C,A
	LD	A,(HL)
	CALL	ASCII_LOWER
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	JR	MATCH_TOKEN_CI

ASCII_LOWER
	CP	'A'
	RET	C
	CP	'Z'+1
	RET	NC
	ADD	A,32
	RET

SKIP_VALUE_SPACE
	LD	A,(HL)
	CP	' '
	JR	Z,.ONE
	CP	9
	RET	NZ
.ONE
	INC	HL
	JR	SKIP_VALUE_SPACE

PARSE_CONTENT_LENGTH
	LD	(PARSE_PTR),HL
	XOR	A
	LD	(CONTENT_LENGTH),A
	LD	(CONTENT_LENGTH+1),A
	LD	(CONTENT_LENGTH+2),A
	LD	(CONTENT_LENGTH+3),A
	LD	(DIGITS),A
.DIGIT_LOOP
	LD	HL,(PARSE_PTR)
	LD	A,(HL)
	CP	'0'
	JR	C,.DIGITS_DONE
	CP	'9'+1
	JR	NC,.DIGITS_DONE
	SUB	'0'
	LD	(DIGIT),A
	CALL	MUL10
	JR	C,.INVALID
	LD	A,(DIGIT)
	CALL	ADD_DIGIT
	JR	C,.INVALID
	LD	HL,(PARSE_PTR)
	INC	HL
	LD	(PARSE_PTR),HL
	LD	A,(DIGITS)
	INC	A
	LD	(DIGITS),A
	JR	.DIGIT_LOOP
.DIGITS_DONE
	LD	A,(DIGITS)
	OR	A
	JR	Z,.INVALID
	LD	HL,(PARSE_PTR)
	CALL	SKIP_VALUE_SPACE
	LD	A,(HL)
	CP	13
	JR	Z,.OK
	OR	A
	JR	NZ,.INVALID
.OK
	OR	A
	RET
.INVALID
	LD	A,DHTTP_ERR_LENGTH_INVALID
	SCF
	RET

MUL10
	LD	HL,CONTENT_LENGTH
	LD	DE,U32_TEMP
	LD	BC,4
	LDIR
	LD	HL,CONTENT_LENGTH
	CALL	SHL_U32
	RET	C
	LD	B,3
.TEMP_SHIFT
	LD	HL,U32_TEMP
	CALL	SHL_U32
	RET	C
	DJNZ	.TEMP_SHIFT
	LD	HL,CONTENT_LENGTH
	LD	DE,U32_TEMP
	LD	B,4
	OR	A
.ADD
	LD	A,(DE)
	ADC	A,(HL)
	LD	(HL),A
	INC	HL
	INC	DE
	DJNZ	.ADD
	RET

SHL_U32
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	RET

ADD_DIGIT
	LD	E,A
	LD	HL,CONTENT_LENGTH
	LD	A,(HL)
	ADD	A,E
	LD	(HL),A
	LD	B,3
.CARRY
	INC	HL
	LD	A,(HL)
	ADC	A,0
	LD	(HL),A
	DJNZ	.CARRY
	RET

; Count all currently supplied body bytes, capped at Content-Length.
COUNT_BODY_INPUT
	LD	BC,(INPUT_LEFT)
	OR	A
	LD	HL,(CONTENT_LENGTH)
	LD	DE,(BODY_BYTES)
	SBC	HL,DE
	LD	(REMAIN_LOW),HL
	LD	HL,(CONTENT_LENGTH+2)
	LD	DE,(BODY_BYTES+2)
	SBC	HL,DE
	LD	A,H
	OR	L
	JR	NZ,.ADD_ALL
	LD	DE,(REMAIN_LOW)
	LD	H,B
	LD	L,C
	OR	A
	SBC	HL,DE			; input - remaining
	JR	C,.ADD_ALL
	; This block reaches or crosses the exact body boundary.  Extra bytes are
	; deliberately ignored and never enter BODY_BYTES.
	LD	HL,(CONTENT_LENGTH)
	LD	(BODY_BYTES),HL
	LD	HL,(CONTENT_LENGTH+2)
	LD	(BODY_BYTES+2),HL
	LD	HL,0
	LD	(INPUT_LEFT),HL
	LD	A,1
	LD	(DONE),A
	RET
.ADD_ALL
	LD	HL,(BODY_BYTES)
	ADD	HL,BC
	LD	(BODY_BYTES),HL
	JR	NC,.NO_CARRY
	LD	HL,(BODY_BYTES+2)
	INC	HL
	LD	(BODY_BYTES+2),HL
.NO_CARRY
	LD	HL,0
	LD	(INPUT_LEFT),HL
	RET

HTTP_PREFIX	DB "HTTP/"
H_CONTENT_LENGTH DB "content-length:",0
H_TRANSFER_ENCODING DB "transfer-encoding:",0
H_CONTENT_ENCODING DB "content-encoding:",0
V_IDENTITY	DB "identity",0

PHASE		DB 0		; 0 seek status, 1 header, 2 body
SEARCH_STATE	DB 0
HDR_STATE	DB 0
DONE		DB 0
ERROR		DB 0
CONTENT_LENGTH_SEEN DB 0
HEADER_BASE	DW 0
HEADER_CAP	DW 0
HEADER_LEN	DW 0
INPUT_PTR	DW 0
INPUT_LEFT	DW 0
PARSE_PTR	DW 0
REMAIN_LOW	DW 0
DIGIT		DB 0
DIGITS		DB 0
LAST_BYTE	DB 0
CONTENT_LENGTH	DD 0
BODY_BYTES	DD 0
U32_TEMP	DD 0

	ENDMODULE
	ENDIF
