; ======================================================
; Shared NET.CFG parser for Sprinter ESP Network Kit
; ======================================================

	IFNDEF _NETCFG
	DEFINE _NETCFG

	MODULE NETCFG

; Most clients keep this parser buffer in WIN1. Utilities that only consume
; NETUP's published session values never call LOAD/PARSE and need only the
; scalar CFG_* slots (not a file buffer). Memory-tight ORG 0x4100 utilities
; which still load NET.CFG use the compact parser buffer.
	IFDEF	NETCFG_SESSION_ONLY
CFG_BUFF_SIZE	EQU 1
	ELSE
	IFDEF	NETCFG_COMPACT_BUFFER
CFG_BUFF_SIZE	EQU 1536
	ELSE
CFG_BUFF_SIZE	EQU 2048
	ENDIF
	ENDIF
DSS_CREATE_OVERWRITE	EQU 0x0A

; ------------------------------------------------------
; Load NET.CFG from current directory and parse it.
; Out: CF=0 - loaded and parsed
;      CF=1 - DSS error in A, defaults remain active
; ------------------------------------------------------
LOAD
	CALL	SET_DEFAULTS
	LD	HL,CFG_FILE
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	RET	C

	LD	(CFG_FH),A
	LD	HL,CFG_BUFF
	LD	DE,CFG_BUFF_SIZE-1
	LD	C,DSS_READ_FILE
	RST	DSS
	JR	C,.READ_ERROR

	; Zero-terminate at actual read size.
	LD	HL,CFG_BUFF
	ADD	HL,DE
	LD	(HL),0

	LD	A,(CFG_FH)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	RET	C

	LD	HL,CFG_BUFF
	CALL	PARSE
	XOR	A
	RET

.READ_ERROR
	PUSH	AF
	LD	A,(CFG_FH)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	POP	AF
	SCF
	RET

; Load and parse the ASCIIZ configuration path in HL. This is needed only by
; NETUP to keep its configuration beside NETUP.EXE. Keep it conditional so
; legacy utilities do not grow their already-tight code/BSS image.
	IFDEF NETCFG_ENABLE_LOAD_PATH
LOAD_PATH
	PUSH	HL
	CALL	SET_DEFAULTS
	POP	HL

	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	RET	C

	LD	(CFG_FH),A
	LD	HL,CFG_BUFF
	LD	DE,CFG_BUFF_SIZE-1
	LD	C,DSS_READ_FILE
	RST	DSS
	JR	C,.READ_ERROR

	LD	HL,CFG_BUFF
	ADD	HL,DE
	LD	(HL),0

	LD	A,(CFG_FH)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	RET	C

	LD	HL,CFG_BUFF
	CALL	PARSE
	XOR	A
	RET

.READ_ERROR
	PUSH	AF
	LD	A,(CFG_FH)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	POP	AF
	SCF
	RET
	ENDIF

; ------------------------------------------------------
; Save current config values to NET.CFG.
; Out: CF=0 - saved
;      CF=1 - DSS error in A
; ------------------------------------------------------
SAVE
	CALL	BUILD_SAVE_BUFFER
	PUSH	HL
	LD	HL,CFG_FILE
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	POP	HL
	RET	C

	LD	(CFG_FH),A

	LD	DE,CFG_BUFF
	AND	A
	SBC	HL,DE
	EX	DE,HL						; DE = length

	LD	A,(CFG_FH)
	LD	HL,CFG_BUFF
	LD	C,DSS_WRITE
	RST	DSS
	JR	C,.WRITE_ERROR

	LD	A,(CFG_FH)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	RET

.WRITE_ERROR
	PUSH	AF
	LD	A,(CFG_FH)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	POP	AF
	SCF
	RET

; ------------------------------------------------------
; Set safe default values.
; ------------------------------------------------------
SET_DEFAULTS
	LD	HL,EMPTY
	LD	DE,CFG_SSID
	LD	B,CFG_SSID_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,EMPTY
	LD	DE,CFG_PASS
	LD	B,CFG_PASS_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_DHCP
	LD	DE,CFG_DHCP
	LD	B,CFG_FLAG_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,EMPTY
	LD	DE,CFG_IP
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,EMPTY
	LD	DE,CFG_GATEWAY
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,EMPTY
	LD	DE,CFG_NETMASK
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_DNS1
	LD	DE,CFG_DNS1
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_DNS2
	LD	DE,CFG_DNS2
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_TZ
	LD	DE,CFG_TZ
	LD	B,CFG_TZ_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_NTP
	LD	DE,CFG_NTP
	LD	B,CFG_NTP_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_AUTOJOIN
	LD	DE,CFG_AUTOJOIN
	LD	B,CFG_FLAG_SIZE
	CALL	COPY_ASCIIZ

	LD	HL,DEFAULT_BAUD
	LD	DE,CFG_BAUD
	LD	B,CFG_BAUD_SIZE
	JP	COPY_ASCIIZ

; ------------------------------------------------------
; Parse zero-ended config buffer.
; In: HL - buffer
; ------------------------------------------------------
PARSE
.LINE
	CALL	SKIP_LINE_PREFIX
	LD	A,(HL)
	AND	A
	RET	Z
	CP	13
	JR	Z,.NEXT_CHAR
	CP	10
	JR	Z,.NEXT_CHAR
	CP	'#'
	JR	Z,.SKIP_LINE

	LD	DE,KEY_SSID
	CALL	@UTIL.STARTSWITH
	JP	Z,.SSID
	LD	DE,KEY_PASS
	CALL	@UTIL.STARTSWITH
	JP	Z,.PASS
	LD	DE,KEY_DHCP
	CALL	@UTIL.STARTSWITH
	JP	Z,.DHCP
	LD	DE,KEY_IP
	CALL	@UTIL.STARTSWITH
	JP	Z,.IP
	LD	DE,KEY_GATEWAY
	CALL	@UTIL.STARTSWITH
	JP	Z,.GATEWAY
	LD	DE,KEY_NETMASK
	CALL	@UTIL.STARTSWITH
	JP	Z,.NETMASK
	LD	DE,KEY_DNS1
	CALL	@UTIL.STARTSWITH
	JP	Z,.DNS1
	LD	DE,KEY_DNS2
	CALL	@UTIL.STARTSWITH
	JP	Z,.DNS2
	LD	DE,KEY_TZ
	CALL	@UTIL.STARTSWITH
	JP	Z,.TZ
	LD	DE,KEY_NTP
	CALL	@UTIL.STARTSWITH
	JP	Z,.NTP
	LD	DE,KEY_AUTOJOIN
	CALL	@UTIL.STARTSWITH
	JP	Z,.AUTOJOIN
	LD	DE,KEY_BAUD
	CALL	@UTIL.STARTSWITH
	JP	Z,.BAUD

.SKIP_LINE
	CALL	SKIP_TO_NEXT_LINE
	JP	.LINE

.NEXT_CHAR
	INC	HL
	JP	.LINE

.SSID
	LD	BC,5
	ADD	HL,BC
	LD	DE,CFG_SSID
	LD	B,CFG_SSID_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.PASS
	LD	BC,5
	ADD	HL,BC
	LD	DE,CFG_PASS
	LD	B,CFG_PASS_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.DHCP
	LD	BC,5
	ADD	HL,BC
	LD	DE,CFG_DHCP
	LD	B,CFG_FLAG_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.IP
	LD	BC,3
	ADD	HL,BC
	LD	DE,CFG_IP
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.GATEWAY
	LD	BC,8
	ADD	HL,BC
	LD	DE,CFG_GATEWAY
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.NETMASK
	LD	BC,8
	ADD	HL,BC
	LD	DE,CFG_NETMASK
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.DNS1
	LD	BC,5
	ADD	HL,BC
	LD	DE,CFG_DNS1
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_VALUE
	JR	.SKIP_LINE
.DNS2
	LD	BC,5
	ADD	HL,BC
	LD	DE,CFG_DNS2
	LD	B,CFG_ADDR_SIZE
	CALL	COPY_VALUE
	JP	.SKIP_LINE
.TZ
	LD	BC,3
	ADD	HL,BC
	LD	DE,CFG_TZ
	LD	B,CFG_TZ_SIZE
	CALL	COPY_VALUE
	JP	.SKIP_LINE
.NTP
	LD	BC,4
	ADD	HL,BC
	LD	DE,CFG_NTP
	LD	B,CFG_NTP_SIZE
	CALL	COPY_VALUE
	JP	.SKIP_LINE
.AUTOJOIN
	LD	BC,9
	ADD	HL,BC
	LD	DE,CFG_AUTOJOIN
	LD	B,CFG_FLAG_SIZE
	CALL	COPY_VALUE
	JP	.SKIP_LINE
.BAUD
	LD	BC,5
	ADD	HL,BC
	LD	DE,CFG_BAUD
	LD	B,CFG_BAUD_SIZE
	CALL	COPY_VALUE
	JP	.SKIP_LINE

; ------------------------------------------------------
; Apply configured UART baud divisor to the ESP library.
; Unknown values fall back to 115200.
; ------------------------------------------------------
APPLY_UART_BAUD
	CALL	GET_UART_DIVISOR
	JP	@WIFI.UART_SET_DIVISOR

GET_UART_BAUD_TEXT
	LD	HL,BAUD_230400
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	RET	NC
	LD	HL,BAUD_115200
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	RET	NC
	LD	HL,BAUD_57600
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	RET	NC
	LD	HL,BAUD_38400
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	RET	NC
	LD	HL,BAUD_19200
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	RET	NC
	LD	HL,BAUD_9600
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	RET	NC
	LD	HL,BAUD_115200
	RET

GET_UART_DIVISOR
	LD	HL,BAUD_230400
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	JR	NC,.D230400
	LD	HL,BAUD_115200
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	JR	NC,.D115200
	LD	HL,BAUD_57600
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	JR	NC,.D57600
	LD	HL,BAUD_38400
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	JR	NC,.D38400
	LD	HL,BAUD_19200
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	JR	NC,.D19200
	LD	HL,BAUD_9600
	LD	DE,CFG_BAUD
	CALL	@UTIL.STRCMP
	JR	NC,.D9600
.D230400
	LD	A,4
	RET
.D115200
	LD	A,8
	RET
.D57600
	LD	A,16
	RET
.D38400
	LD	A,24
	RET
.D19200
	LD	A,48
	RET
.D9600
	LD	A,96
	RET

; ------------------------------------------------------
; Skip leading spaces and tabs on a line.
; ------------------------------------------------------
SKIP_LINE_PREFIX
	LD	A,(HL)
	CP	' '
	JR	Z,.SKIP
	CP	9
	RET	NZ
.SKIP
	INC	HL
	JR	SKIP_LINE_PREFIX

; ------------------------------------------------------
; Move HL to next line or string end.
; ------------------------------------------------------
SKIP_TO_NEXT_LINE
	LD	A,(HL)
	AND	A
	RET	Z
	INC	HL
	CP	10
	RET	Z
	JR	SKIP_TO_NEXT_LINE

; ------------------------------------------------------
; Copy ASCIIZ from HL to DE. B is destination size including zero.
; ------------------------------------------------------
COPY_ASCIIZ
	DEC	B
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.END
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	.NEXT
.END
	XOR	A
	LD	(DE),A
	RET

; ------------------------------------------------------
; Copy config value from HL to DE. B is destination size including zero.
; Stops at CR, LF, # or string end.
; ------------------------------------------------------
COPY_VALUE
	DEC	B
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.END
	CP	13
	JR	Z,.END
	CP	10
	JR	Z,.END
	CP	'#'
	JR	Z,.END
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	.NEXT
.END
	XOR	A
	LD	(DE),A
	RET

; ------------------------------------------------------
; Build NET.CFG text in CFG_BUFF.
; Out: HL - end of data
; ------------------------------------------------------
BUILD_SAVE_BUFFER
	LD	HL,CFG_BUFF

	LD	DE,SAVE_HEADER
	CALL	APPEND_STR

	LD	DE,KEY_SSID
	LD	IX,CFG_SSID
	CALL	APPEND_FIELD

	LD	DE,KEY_PASS
	LD	IX,CFG_PASS
	CALL	APPEND_FIELD

	LD	DE,KEY_DHCP
	LD	IX,CFG_DHCP
	CALL	APPEND_FIELD

	LD	DE,KEY_IP
	LD	IX,CFG_IP
	CALL	APPEND_FIELD

	LD	DE,KEY_GATEWAY
	LD	IX,CFG_GATEWAY
	CALL	APPEND_FIELD

	LD	DE,KEY_NETMASK
	LD	IX,CFG_NETMASK
	CALL	APPEND_FIELD

	LD	DE,KEY_DNS1
	LD	IX,CFG_DNS1
	CALL	APPEND_FIELD

	LD	DE,KEY_DNS2
	LD	IX,CFG_DNS2
	CALL	APPEND_FIELD

	LD	DE,KEY_TZ
	LD	IX,CFG_TZ
	CALL	APPEND_FIELD

	LD	DE,KEY_NTP
	LD	IX,CFG_NTP
	CALL	APPEND_FIELD

	LD	DE,KEY_AUTOJOIN
	LD	IX,CFG_AUTOJOIN
	CALL	APPEND_FIELD
	LD	DE,KEY_BAUD
	LD	IX,CFG_BAUD
	CALL	APPEND_FIELD
	RET

; ------------------------------------------------------
; Append key in DE, value in IX and CRLF to buffer at HL.
; Out: HL - new end
; ------------------------------------------------------
APPEND_FIELD
	CALL	APPEND_STR
	CALL	APPEND_IX_STR
	JP	APPEND_CRLF

; ------------------------------------------------------
; Append ASCIIZ from DE to buffer at HL.
; Out: HL - new end
; ------------------------------------------------------
APPEND_STR
	LD	A,(DE)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	DE
	JR	APPEND_STR

; ------------------------------------------------------
; Append ASCIIZ from IX to buffer at HL.
; Out: HL - new end
; ------------------------------------------------------
APPEND_IX_STR
	LD	A,(IX+0)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	IX
	JR	APPEND_IX_STR

APPEND_CRLF
	LD	(HL),13
	INC	HL
	LD	(HL),10
	INC	HL
	RET

CFG_FILE	DB "NET.CFG",0
EMPTY		DB 0

DEFAULT_DHCP		DB "1",0
DEFAULT_DNS1		DB "1.1.1.1",0
DEFAULT_DNS2		DB "8.8.8.8",0
DEFAULT_TZ		DB "+6",0
DEFAULT_NTP		DB "pool.ntp.org",0
DEFAULT_AUTOJOIN	DB "1",0
DEFAULT_BAUD		DB "115200",0

BAUD_230400		DB "230400",0
BAUD_115200		DB "115200",0
BAUD_57600		DB "57600",0
BAUD_38400		DB "38400",0
BAUD_19200		DB "19200",0
BAUD_9600		DB "9600",0

KEY_SSID	DB "SSID=",0
KEY_PASS	DB "PASS=",0
KEY_DHCP	DB "DHCP=",0
KEY_IP		DB "IP=",0
KEY_GATEWAY	DB "GATEWAY=",0
KEY_NETMASK	DB "NETMASK=",0
KEY_DNS1	DB "DNS1=",0
KEY_DNS2	DB "DNS2=",0
KEY_TZ		DB "TZ=",0
KEY_NTP		DB "NTP=",0
KEY_AUTOJOIN	DB "AUTOJOIN=",0
KEY_BAUD	DB "BAUD=",0

SAVE_HEADER
	DB "# Sprinter ESP Network Kit configuration",13,10
	DB "# Password is stored in clear text.",13,10,0

CFG_SSID_SIZE		EQU 33
CFG_PASS_SIZE		EQU 65
CFG_FLAG_SIZE		EQU 2
CFG_ADDR_SIZE		EQU 16
CFG_TZ_SIZE		EQU 6
CFG_NTP_SIZE		EQU 64
CFG_BAUD_SIZE		EQU 7

	IFNDEF	NETCFG_BSS_BASE_OVERRIDE
NETCFG_BSS_BASE	EQU WIFI.RS_BUFF + RS_BUFF_SIZE
	ENDIF

CFG_FH		EQU NETCFG_BSS_BASE
CFG_SSID	EQU CFG_FH + 1
CFG_PASS	EQU CFG_SSID + CFG_SSID_SIZE
CFG_DHCP	EQU CFG_PASS + CFG_PASS_SIZE
CFG_IP		EQU CFG_DHCP + CFG_FLAG_SIZE
CFG_GATEWAY	EQU CFG_IP + CFG_ADDR_SIZE
CFG_NETMASK	EQU CFG_GATEWAY + CFG_ADDR_SIZE
CFG_DNS1	EQU CFG_NETMASK + CFG_ADDR_SIZE
CFG_DNS2	EQU CFG_DNS1 + CFG_ADDR_SIZE
CFG_TZ		EQU CFG_DNS2 + CFG_ADDR_SIZE
CFG_NTP		EQU CFG_TZ + CFG_TZ_SIZE
CFG_AUTOJOIN	EQU CFG_NTP + CFG_NTP_SIZE
CFG_BAUD	EQU CFG_AUTOJOIN + CFG_FLAG_SIZE

CFG_BUFF	EQU CFG_BAUD + CFG_BAUD_SIZE
NETCFG_BSS_END	EQU CFG_BUFF + CFG_BUFF_SIZE

	ENDMODULE

	ENDIF
