; ======================================================
; DLSPEED - SprinterESP TCP/UART download throughput diagnostic.
; Receives one plain HTTP body, discards it, and reports an RTC-aligned rate.
; Developer diagnostic only: built by `make dlspeed`, never packaged.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
RECV_TIMEOUT		EQU 7000
MUX_RECOVERY_DELAY	EQU 250
RECV_BUFFER_SIZE	EQU 16384
URL_SIZE		EQU 192
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
PATH_SIZE		EQU 192
REQ_SIZE		EQU 384
HEADER_SIZE		EQU 1024

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

LOAD_ADDR	EQU 0x4100
STACK_TOP	EQU 0x8000
WIN2_BASE	EQU 0x8000

	ORG LOAD_ADDR - 0x0200
EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0200
	DW 0,0,0,0,0
	DW START
	DW START
	DW STACK_TOP
	DS 490,0

	ORG LOAD_ADDR

START
	LD	(CMDLINE_PTR),IX
	CALL	INIT_RUNTIME_PAGE
	JP	C,MEMORY_ERROR
	CALL	CLEAR_BSS
	XOR	A
	LD	(TCP_IS_OPEN),A

	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN	MSG_BANNER

	CALL	PARSE_CMD_LINE
	JP	C,USAGE
	LD	A,(HELP_REQUESTED)
	OR	A
	JP	NZ,SHOW_HELP
	CALL	PARSE_URL
	JP	C,USAGE
	CALL	BUILD_HTTP_REQUEST
	PRINT	MSG_SOURCE
	PRINT	URL_BUFF
	PRINT	WCOMMON.LINE_END

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI
	CALL	WCOMMON.REQUIRE_NET_UP
	CALL	WCOMMON.APPLY_NET_BAUD
	CALL	WIFI.UART_INIT

	CALL	WCOMMON.SYNC_ESP_COMMAND
	JP	C,NETWORK_ERROR
	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD
	JP	C,NETWORK_ERROR
	CALL	WCOMMON.SETUP_UART_FLOW
	OR	A
	JP	NZ,NETWORK_ERROR

	CALL	WCOMMON.CLEAN_ESP_LINKS
	LD	HL,MUX_RECOVERY_DELAY
	CALL	UTIL.DELAY
	LD	HL,CMD_CIPMUX_0
	CALL	SEND_CMD
	JP	C,NETWORK_ERROR

	PRINT	MSG_CONNECTING
	PRINT	HOST_BUFF
	PRINT	MSG_COLON
	PRINT	PORT_BUFF
	PRINT	WCOMMON.LINE_END
	LD	HL,HOST_BUFF
	LD	DE,PORT_BUFF
	CALL	OPEN_TCP
	JP	C,CONNECT_ERROR
	LD	A,1
	LD	(TCP_IS_OPEN),A

	LD	HL,HEADER_BUFF
	LD	DE,HEADER_SIZE
	CALL	DHTTP.RESET
	PRINTLN	MSG_WAIT_EDGE
	CALL	TPUT.START_ALIGNED
	JP	C,RTC_ERROR

	; The first operation after the detected RTC edge is transmission of GET.
	LD	HL,REQ_BUFF
	CALL	UTIL.STRLEN
	CALL	TCP.SEND_BUFFER_NO_WAIT
	JP	C,NETWORK_ERROR

	CALL	RECEIVE_BODY
	JP	C,RECEIVE_ERROR

	; STOP was captured by RECEIVE_BODY at the exact Content-Length boundary.
	CALL	WIFI.UART_RX_RESUME
	CALL	CLOSE_SOCKET

	PRINT	MSG_RECEIVED
	LD	HL,(DHTTP.BODY_BYTES)
	LD	DE,(DHTTP.BODY_BYTES+2)
	CALL	TPUT.PRINT_DEC_32
	PRINTLN	MSG_BYTES

	LD	HL,(DHTTP.BODY_BYTES)
	LD	DE,(DHTTP.BODY_BYTES+2)
	CALL	TPUT.REPORT_STOPPED
	JP	C,SAMPLE_TOO_SHORT
	PRINTLN	MSG_INTEGRITY_OK
	LD	B,0
	JP	WCOMMON.EXIT

NO_WIFI
	PRINTLN	MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

MEMORY_ERROR
	LD	B,3
	LD	C,DSS_EXIT
	RST	DSS

USAGE
	PRINTLN	MSG_USAGE
	LD	B,1
	JP	WCOMMON.EXIT

SHOW_HELP
	PRINTLN	MSG_USAGE
	LD	B,0
	JP	WCOMMON.EXIT

SAMPLE_TOO_SHORT
	PRINTLN	MSG_SAMPLE_SHORT
	LD	B,3
	JP	WCOMMON.EXIT

RTC_ERROR
	CALL	CLOSE_SOCKET
	PRINTLN	MSG_RTC_STOPPED
	LD	B,3
	JP	WCOMMON.EXIT

RECEIVE_ERROR
	LD	(RECEIVE_RESULT),A
	CALL	CLOSE_SOCKET
	LD	A,(WCOMMON.CANCELLED)
	OR	A
	JR	Z,.NOT_CANCELLED
	PRINTLN	MSG_CANCELLED
	JR	.ERROR_EXIT
.NOT_CANCELLED
	LD	A,(DHTTP.ERROR)
	OR	A
	JR	Z,.TRANSPORT
	CALL	PRINT_HTTP_ERROR
	JR	.ERROR_EXIT
.TRANSPORT
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	JR	Z,.INCOMPLETE
	PRINTLN	MSG_UART_ERROR
	JR	.ERROR_EXIT
.INCOMPLETE
	PRINTLN	MSG_INCOMPLETE
.ERROR_EXIT
	LD	B,3
	JP	WCOMMON.EXIT

NETWORK_ERROR
	LD	(RECEIVE_RESULT),A
	CALL	CLOSE_SOCKET
	PRINT	MSG_NETWORK_ERROR
	CALL	PRINT_RECEIVE_RESULT
	PRINT	WCOMMON.LINE_END
	CALL	PRINT_NETWORK_HINT
	LD	B,3
	JP	WCOMMON.EXIT

CONNECT_ERROR
	LD	(RECEIVE_RESULT),A
	; A timed-out CIPSTART may still be pending inside ESP. Abort it now so a
	; corrected second invocation does not inherit "busy p..." from this one.
	CALL	SEND_CLOSE_NO_WAIT
	PRINT	MSG_CONNECT_ERROR
	PRINT	HOST_BUFF
	PRINT	MSG_COLON
	PRINT	PORT_BUFF
	PRINT	MSG_RESULT_OPEN
	CALL	PRINT_RECEIVE_RESULT
	PRINTLN	MSG_RESULT_CLOSE
	CALL	PRINT_NETWORK_HINT
	LD	B,3
	JP	WCOMMON.EXIT

PRINT_RECEIVE_RESULT
	LD	A,(RECEIVE_RESULT)
	LD	L,A
	LD	H,0
	LD	DE,NUM_BUFF
	CALL	UTIL.UTOA
	PRINT	NUM_BUFF
	RET

PRINT_NETWORK_HINT
	LD	A,(RECEIVE_RESULT)
	CP	RES_BUSY
	JR	Z,.BUSY
	CP	RES_RS_TIMEOUT
	JR	Z,.TIMEOUT
	CP	RES_ERROR
	JR	Z,.CONNECT
	CP	RES_FAIL
	RET	NZ
.CONNECT
	PRINTLN	MSG_CONNECT_HINT
	RET
.BUSY
	PRINTLN	MSG_BUSY_HINT
	RET
.TIMEOUT
	PRINTLN	MSG_TIMEOUT_HINT
	RET

CLOSE_SOCKET
	LD	A,(TCP_IS_OPEN)
	OR	A
	RET	Z
	XOR	A
	LD	(TCP_IS_OPEN),A
	; Cleanup must not delay or hide a completed measurement. UART_TX_CMD waits
	; for a terminal line and can spend an unbounded wall time walking through
	; a continuous +IPD backlog because each received byte refreshes its timeout.
	; Transmit CIPCLOSE and let the next utility's normal SYNC/CLEAN sequence
	; drain its asynchronous OK/CLOSED tail.
	JP	SEND_CLOSE_NO_WAIT

SEND_CLOSE_NO_WAIT
	CALL	WIFI.UART_RX_RESUME
	LD	HL,CMD_CIPCLOSE
	JP	WIFI.UART_TX_STRING

; ------------------------------------------------------
; Receive loop. No file I/O or progress output is performed. The only DSS call
; in the loop is the cancellation poll. DHTTP counts no more than the declared
; body size; STOP is the first call after it reports completion.
; ------------------------------------------------------
RECEIVE_BODY
.LOOP
	CALL	WCOMMON.CHECK_CANCEL
	JR	C,.CANCELLED
	CALL	WIFI.UART_RX_RESUME
	LD	HL,RECV_BUFFER
	LD	BC,RECV_BUFFER_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	TCP.RECEIVE
	JR	C,.TRANSPORT_ERROR
	LD	(RECEIVE_RESULT),A
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	JR	NZ,.UART_ERROR
	LD	A,B
	OR	C
	JR	Z,.LOOP
	LD	HL,RECV_BUFFER
	CALL	DHTTP.CONSUME
	RET	C
	OR	A
	JR	Z,.LOOP
	CALL	TPUT.STOP
	XOR	A
	RET
.TRANSPORT_ERROR
	LD	(RECEIVE_RESULT),A
	SCF
	RET
.UART_ERROR
	LD	A,RES_RS_TIMEOUT
	LD	(RECEIVE_RESULT),A
	SCF
	RET
.CANCELLED
	LD	A,RES_RS_TIMEOUT
	LD	(RECEIVE_RESULT),A
	SCF
	RET

; ------------------------------------------------------
; Command line: exactly one full plain-http URL, or /?.
; ------------------------------------------------------
PARSE_CMD_LINE
	XOR	A
	LD	(HELP_REQUESTED),A
	LD	HL,(CMDLINE_PTR)
	LD	A,(HL)
	OR	A
	JR	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	PUSH	HL
	PUSH	BC
	LD	HL,SWITCH_HELP
	LD	DE,URL_BUFF
	CALL	UTIL.STRCMP_CI
	POP	BC
	POP	HL
	JR	C,.NOT_HELP
	LD	A,1
	LD	(HELP_REQUESTED),A
.NOT_HELP
	CALL	ONLY_SPACES_LEFT
	RET	NC
.ERR
	SCF
	RET

SKIP_SPACES
	LD	A,B
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	XOR	A
	LD	(ARG_LEN),A
.NEXT
	LD	A,B
	OR	A
	JR	Z,.DONE
	LD	A,(HL)
	CP	0x21
	JR	C,.DONE
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	DEC	C
	LD	A,(ARG_LEN)
	INC	A
	LD	(ARG_LEN),A
	JR	.NEXT
.DONE
	XOR	A
	LD	(DE),A
	LD	A,(ARG_LEN)
	OR	A
	RET	NZ
.ERR
	SCF
	RET

ONLY_SPACES_LEFT
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	0x21
	JR	NC,.ERR
	INC	HL
	DJNZ	ONLY_SPACES_LEFT
	OR	A
	RET
.ERR
	SCF
	RET

; Strict full http:// URL parser. HTTPS and scheme-less inputs are rejected.
PARSE_URL
	LD	HL,URL_BUFF
	LD	DE,HTTP_PREFIX
	CALL	UTIL.STARTSWITH
	JP	NZ,.ERR
	LD	BC,7
	ADD	HL,BC
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
.HOST
	LD	A,(HL)
	OR	A
	JR	Z,.HOST_DONE
	CP	'/'
	JR	Z,.HOST_DONE
	CP	':'
	JR	Z,.PORT_START
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.HOST
.HOST_DONE
	XOR	A
	LD	(DE),A
	LD	A,(HOST_BUFF)
	OR	A
	JR	Z,.ERR
	PUSH	HL
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	CALL	COPY_ASCIIZ
	POP	HL
	JR	.PATH_START
.PORT_START
	XOR	A
	LD	(DE),A
	INC	HL
	LD	DE,PORT_BUFF
	LD	C,PORT_SIZE-1
.PORT
	LD	A,(HL)
	OR	A
	JR	Z,.PORT_DONE
	CP	'/'
	JR	Z,.PORT_DONE
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.PORT
.PORT_DONE
	XOR	A
	LD	(DE),A
	LD	A,(PORT_BUFF)
	OR	A
	JR	Z,.ERR
.PATH_START
	LD	A,(HL)
	CP	'/'
	JR	Z,.COPY_PATH
	OR	A
	JR	NZ,.ERR
	LD	HL,DEFAULT_PATH
.COPY_PATH
	LD	DE,PATH_BUFF
	LD	C,PATH_SIZE-1
.PATH
	LD	A,(HL)
	OR	A
	JR	Z,.PATH_DONE
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.PATH
.PATH_DONE
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET

COPY_ASCIIZ
	LD	A,(HL)
	LD	(DE),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ

BUILD_HTTP_REQUEST
	LD	HL,REQ_BUFF
	LD	DE,REQ_GET
	CALL	APPEND_STR
	LD	DE,PATH_BUFF
	CALL	APPEND_STR
	LD	DE,REQ_HTTP_HOST
	CALL	APPEND_STR
	LD	DE,HOST_BUFF
	CALL	APPEND_STR
	; UTIL.STRCMP preserves its inputs, but selecting PORT_BUFF as its HL input
	; would otherwise lose the request write pointer. On a custom port the next
	; APPEND_STR then copied PORT_BUFF over itself with a one-byte offset, never
	; reached NUL and hung before the first "Source:" line was printed.
	PUSH	HL
	LD	HL,PORT_BUFF
	LD	DE,DEFAULT_PORT
	CALL	UTIL.STRCMP
	POP	HL
	JR	NC,.DEFAULT_PORT
	LD	DE,REQ_COLON
	CALL	APPEND_STR
	LD	DE,PORT_BUFF
	CALL	APPEND_STR
.DEFAULT_PORT
	LD	DE,REQ_END
	JP	APPEND_STR

APPEND_STR
	LD	A,(DE)
	LD	(HL),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	APPEND_STR

SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	OR	A
	RET	Z
	SCF
	RET

OPEN_TCP
	; The session was synchronised, cleaned and put in CIPMUX=0 immediately
	; above. Do not repeat that whole command sequence here: duplicate cleanup
	; can collide with asynchronous CLOSED/ERROR tails and manufacture RES_BUSY.
	PUSH	HL
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	XOR	A
	LD	(TCP.LSR_ACCUM),A
	CALL	WIFI.UART_RX_RESUME
	CALL	WIFI.UART_EMPTY_RS
	POP	HL
	; TCP.OPEN already has its own bounded busy-p retry loop. A second blind
	; CIPSTART after refusal/timeout can race the first pending connect and turn
	; the useful original result into a misleading RES_BUSY (#9).
	JP	TCP.OPEN

PRINT_HTTP_ERROR
	LD	A,(DHTTP.ERROR)
	CP	DHTTP_ERR_STATUS
	JR	Z,.STATUS
	CP	DHTTP_ERR_LENGTH_MISSING
	JR	Z,.MISSING
	CP	DHTTP_ERR_LENGTH_ZERO
	JR	Z,.ZERO
	CP	DHTTP_ERR_TRANSFER_ENCODING
	JR	Z,.TRANSFER
	CP	DHTTP_ERR_CONTENT_ENCODING
	JR	Z,.ENCODING
	CP	DHTTP_ERR_HEADER_LARGE
	JR	Z,.LARGE
	PRINTLN	MSG_BAD_LENGTH
	RET
.STATUS
	PRINTLN	MSG_BAD_STATUS
	RET
.MISSING
	PRINTLN	MSG_MISSING_LENGTH
	RET
.ZERO
	PRINTLN	MSG_ZERO_LENGTH
	RET
.TRANSFER
	PRINTLN	MSG_TRANSFER_ENCODING
	RET
.ENCODING
	PRINTLN	MSG_CONTENT_ENCODING
	RET
.LARGE
	PRINTLN	MSG_HEADER_LARGE
	RET

INIT_RUNTIME_PAGE
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	RET	C
	LD	B,0
	LD	C,DSS_SETWIN2
	RST	DSS
	RET

CLEAR_BSS
	LD	HL,DLSPEED_BSS_BASE
	LD	DE,DLSPEED_BSS_BASE+1
	LD	BC,DLSPEED_BSS_END-DLSPEED_BSS_BASE-1
	LD	(HL),0
	LDIR
	RET

MSG_BANNER
	DB "DLSPEED "
	PACKAGE_VERSION_TAG
	DB " - ESP download throughput"
	IFDEF	ESP_AT_FORCE_221
	DB " (ESP-AT 2.2.1)"
	ELSE
	IFDEF	ESP_AT_FORCE_222
	DB " (ESP-AT 2.2.2)"
	ENDIF
	ENDIF
	DB 0
MSG_USAGE
	DB "Usage: DLSPEED.EXE http://host[:port]/path",13,10
	DB "       DLSPEED.EXE /?",13,10
	DB "Use at least 512 KiB for a stable one-second RTC measurement.",0
MSG_SOURCE	DB "Source: ",0
MSG_CONNECTING	DB "Connecting to ",0
MSG_COLON	DB ":",0
MSG_WAIT_EDGE	DB "Waiting for RTC second edge; transfer is silent until done...",0
MSG_RECEIVED	DB "Received: ",0
MSG_BYTES	DB " bytes",0
MSG_INTEGRITY_OK DB "Integrity: OK",0
MSG_SAMPLE_SHORT DB "Sample too short (less than one RTC second).",0
MSG_RTC_STOPPED DB "RTC second did not advance; measurement cancelled.",0
MSG_WIFI_NOT_FOUND DB "Sprinter-WiFi not found!",0
MSG_NETWORK_ERROR DB "ESP/TCP error #",0
MSG_CONNECT_ERROR DB "Could not connect to ",0
MSG_RESULT_OPEN DB " (ESP result #",0
MSG_RESULT_CLOSE DB ").",0
MSG_BUSY_HINT DB "ESP is busy. Wait for the previous connection attempt to finish and retry.",0
MSG_TIMEOUT_HINT DB "ESP did not answer before timeout; Esc can cancel long waits.",0
MSG_CONNECT_HINT DB "Check the server address, port and host firewall.",0
MSG_INCOMPLETE	DB "HTTP response ended before Content-Length.",0
MSG_UART_ERROR	DB "Integrity failed: UART LSR error detected.",0
MSG_CANCELLED	DB "Measurement cancelled.",0
MSG_BAD_STATUS	DB "HTTP response is not 2xx.",0
MSG_MISSING_LENGTH DB "HTTP response has no Content-Length.",0
MSG_ZERO_LENGTH	DB "HTTP Content-Length is zero.",0
MSG_TRANSFER_ENCODING DB "Transfer-Encoding is not supported for this test.",0
MSG_CONTENT_ENCODING DB "Content-Encoding must be identity.",0
MSG_HEADER_LARGE DB "HTTP header is too large.",0
MSG_BAD_LENGTH	DB "Invalid 32-bit Content-Length.",0

CMD_AT		DB "AT",13,10,0
CMD_ECHO_OFF	DB "ATE0",13,10,0
CMD_CIPMUX_0	DB "AT+CIPMUX=0",13,10,0
CMD_CIPCLOSE	DB "AT+CIPCLOSE",13,10,0
HTTP_PREFIX	DB "http://",0
DEFAULT_PORT	DB "80",0
DEFAULT_PATH	DB "/",0
SWITCH_HELP	DB "/?",0
REQ_GET		DB "GET ",0
REQ_HTTP_HOST	DB " HTTP/1.1",13,10,"Host: ",0
REQ_COLON	DB ":",0
REQ_END		DB 13,10,"Accept-Encoding: identity",13,10
		DB "Connection: keep-alive",13,10,13,10,0

CMDLINE_PTR	DW 0
HELP_REQUESTED	DB 0
ARG_LEN		DB 0
TCP_IS_OPEN	DB 0
RECEIVE_RESULT	DB 0

	ENDMODULE

	DEFINE	NETCFG_SESSION_ONLY
	INCLUDE "netcfg_lib.asm"
	INCLUDE "wcommon.asm"
	INCLUDE "isa.asm"
	INCLUDE "esp_tcp.asm"
	INCLUDE "dlspeed_http.asm"
	DEFINE	TPUT_ALIGNED
	INCLUDE "tput_lib.asm"
	IFNDEF	ESP_AT_FORCE_222
	DEFINE	WIFI_STABLE_ACTIVE_RX
	ENDIF
	INCLUDE "esplib.asm"

	MODULE MAIN
	ASSERT	$ < STACK_TOP - 0x0100

DLSPEED_BSS_BASE EQU NETCFG.NETCFG_BSS_END
NUM_BUFF	EQU DLSPEED_BSS_BASE
URL_BUFF	EQU NUM_BUFF + 8
HOST_BUFF	EQU URL_BUFF + URL_SIZE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
PATH_BUFF	EQU PORT_BUFF + PORT_SIZE
REQ_BUFF	EQU PATH_BUFF + PATH_SIZE
HEADER_BUFF	EQU REQ_BUFF + REQ_SIZE
DLSPEED_BSS_END EQU HEADER_BUFF + HEADER_SIZE
RECV_BUFFER	EQU WIN2_BASE

	ASSERT	DLSPEED_BSS_END < STACK_TOP - 0x0100
	ASSERT	RECV_BUFFER + RECV_BUFFER_SIZE <= 0xC000
	ENDMODULE

	IFNDEF	DLSPEED_REQUEST_TEST
	END MAIN.START
	ENDIF
