; ======================================================
; TFTP client for Sprinter ESP Network Kit
; Minimal RFC 1350 RRQ/WRQ client over ESP-AT UDP.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
RECV_TIMEOUT		EQU 5000
; UDP datagrams can be dropped silently by ESP/Wi-Fi/network. Bumping the
; retry budget tolerates a few lost packets before failing the transfer.
; For large transfers on real hardware the per-block OE-recovery budget
; needs to be generous — a few percent OE rate over hundreds of blocks
; can otherwise burn through a small retry pool.
RETRY_LIMIT		EQU 16
URL_SIZE		EQU 160
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
REMOTE_FILE_SIZE	EQU 128
LOCAL_FILE_SIZE	EQU 80
TFTP_PACKET_SIZE	EQU 516
TFTP_DATA_SIZE		EQU 512
DSS_CREATE_OVERWRITE	EQU 0x0A
NO_HANDLE		EQU 0xFF

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	; Load at 0x4100 so code and small BSS live below the #8000 stack.
	; Cmdline buffer pointer is taken from IX at entry (see START); load-#80
	; (=0x4080) is the documented default but not assumed.
LOAD_ADDR	EQU 0x4100
STACK_TOP	EQU 0x8000
WIN2_BASE	EQU 0x8000

	; Full 512-byte DSS EXE header.
	ORG LOAD_ADDR - 0x0200

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0200
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 490, 0

	ORG LOAD_ADDR

START
	; DSS passes the command-line buffer pointer in IX at entry
	; ([IX+0]=length, [IX+1..]=text). Capture it first, before any CALL clobbers
	; IX, instead of assuming the load-#80 address. CMDLINE_PTR is a code-segment
	; var, so CLEAR_BSS (WIN2) does not wipe it.
	LD	(CMDLINE_PTR),IX
	CALL	INIT_RUNTIME_PAGE
	JP	C,INIT_MEMORY_ERROR
	CALL	CLEAR_BSS
	LD	A,NO_HANDLE
	LD	(OUT_FH),A
	LD	(IN_FH),A
	XOR	A
	LD	(UDP_IS_OPEN),A
	LD	(TRANSFER_DONE),A
	LD	(TRANSFER_MODE),A
	LD	(FILE_ERROR_FLAG),A
	LD	(FILE_ERROR_CODE),A

	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	PARSE_CMD_LINE
	JP	C,USAGE
	LD	A,(HELP_REQUESTED)
	AND	A
	JP	NZ,SHOW_HELP
	CALL	PRINT_SOURCE_INFO

	CALL	OPEN_TRANSFER_FILE
	JP	C,FILE_ERROR_EXIT

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI
	CALL	WCOMMON.REQUIRE_NET_UP

	CALL	WCOMMON.APPLY_NET_BAUD		; baud from env NET_BAUD (NETUP session); utilities never read NET.CFG
	CALL	WIFI.UART_INIT
	PRINTLN MSG_UART_READY

	LD	HL,CMD_AT
	CALL	SEND_CMD_RECOVER

	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD

	; Verify the UART mode already selected from NET_ESP_FLOW.
	CALL	WCOMMON.SETUP_UART_FLOW
	AND	A
	JP	NZ,UDP_ERROR_EXIT

	CALL	WCOMMON.CLEAN_ESP_LINKS		; drop any link a prior run left open
	LD	HL,CMD_CIPMUX_0
	CALL	SEND_CMD

	CALL	UDP.CLOSE

	PRINT MSG_CONNECTING
	PRINT HOST_BUFF
	PRINT MSG_COLON
	PRINT PORT_BUFF
	PRINT WCOMMON.LINE_END
	LD	HL,HOST_BUFF
	LD	DE,PORT_BUFF
	LD	IX,LOCAL_PORT
	CALL	UDP.OPEN_LOCAL
	JP	C,UDP_ERROR_EXIT
	LD	A,1
	LD	(UDP_IS_OPEN),A
	CALL	VERIFY_UDP_OPEN
	JP	C,UDP_ERROR_EXIT

	CALL	TRANSFER_TFTP
	JP	C,TRANSFER_ERROR_EXIT

	CALL	UDP.CLOSE
	XOR	A
	LD	(UDP_IS_OPEN),A
	CALL	CLOSE_FILES
	JP	C,FILE_ERROR_EXIT

	PRINT WCOMMON.LINE_END
	PRINTLN MSG_DONE
	LD	B,0
	JP	WCOMMON.EXIT

NO_WIFI
	CALL	CLOSE_FILES_IGNORE
	PRINTLN MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

USAGE
	PRINTLN MSG_USAGE
	LD	B,1
	JP	WCOMMON.EXIT

SHOW_HELP
	PRINTLN MSG_USAGE
	LD	B,0
	JP	WCOMMON.EXIT

UDP_ERROR_EXIT
	; Save the inbound error code in A *before* poking CANCELLED — the LD
	; from CANCELLED clobbers A and previously caused every error to print
	; as #0.
	PUSH	AF
	LD	A,(WCOMMON.CANCELLED)
	AND	A
	JR	Z,.NOT_CANCELLED
	POP	AF
	JP	CANCEL_EXIT
.NOT_CANCELLED
	CALL	PRINT_UDP_DEBUG
	CALL	ABORT_UDP_SESSION
	CALL	CLOSE_FILES_IGNORE
	POP	AF
	PUSH	AF
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_NET_ERROR
	POP	AF
	CALL	PRINT_NET_REASON		; plain-language hint for the RES_* code
	LD	B,3
	JP	WCOMMON.EXIT

; Print a human-readable explanation line for the RES_* network error code in A
; (esplib.asm), so "#3" is not the only thing a tester sees. Unknown/benign
; codes print nothing. Trashes A,HL,DE.
PRINT_NET_REASON
	CP	NET_REASON_COUNT
	RET	NC
	LD	L,A
	LD	H,0
	ADD	HL,HL				; code * 2 (word table)
	LD	DE,NET_REASON_TABLE
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	A,D
	OR	E				; null entry -> no extra line
	RET	Z
	EX	DE,HL
	PRINTLN_HL
	RET

PRINT_UDP_DEBUG
	PRINT	MSG_DEBUG
	PRINT	MSG_DEBUG_BLOCK
	LD	HL,(EXPECTED_BLOCK)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_IPD
	LD	HL,(TCP.LAST_IPD_LEN)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_LEFT
	LD	HL,(TCP.PAYLOAD_LEFT)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_LSR
	LD	A,(TCP.LAST_LSR)
	CALL	PRINT_A_HEX
	PRINT	MSG_DEBUG_ACC
	LD	A,(TCP.LSR_ACCUM)
	CALL	PRINT_A_HEX
	PRINT	WCOMMON.LINE_END
	RET

PRINT_HL_DEC
	LD	DE,NUM_PRINT_BUFF
	CALL	UTIL.UTOA
	PRINT	NUM_PRINT_BUFF
	RET

; In-place download progress: "<KB>KB / ?". KB = EXPECTED_BLOCK/2 (block*512/1024).
; The total is "?" because TFTP does not negotiate tsize here. Leading 0x0A
; resets the X column (this console) so each block overwrites the same line.
PRINT_PROGRESS_KB
	PRINT	MSG_CR_ONLY		; 0x0A -> column 0
	LD	HL,(EXPECTED_BLOCK)
	SRL	H
	RR	L			; HL = blocks / 2 = KB
	CALL	PRINT_HL_DEC
	PRINT	MSG_KB_UNK		; "KB / ?"
	RET

PRINT_A_HEX
	LD	C,A
	LD	DE,HEX_PRINT_BUFF
	CALL	UTIL.HEXB
	PRINT	HEX_PRINT_BUFF
	RET

TRANSFER_ERROR_EXIT
	PUSH	AF
	LD	A,(FILE_ERROR_FLAG)
	AND	A
	JR	NZ,.FILE
	POP	AF
	JP	UDP_ERROR_EXIT
.FILE
	POP	AF
	LD	A,(FILE_ERROR_CODE)
	JP	FILE_ERROR_EXIT

FILE_ERROR_EXIT
	PUSH	AF
	CALL	ABORT_UDP_SESSION
	CALL	CLOSE_FILES_IGNORE
	POP	AF
	LD	A,(OUTPUT_ABORTED)
	AND	A
	JR	NZ,OUTPUT_ABORT_EXIT
	CALL	PRINT_FILE_ERROR
	LD	B,5
	JP	WCOMMON.EXIT

OUTPUT_ABORT_EXIT
	PRINTLN	MSG_ABORTED
	LD	B,1
	JP	WCOMMON.EXIT

CANCEL_EXIT
	CALL	ABORT_UDP_SESSION
	CALL	CLOSE_FILES_IGNORE
	PRINT	WCOMMON.LINE_END
	PRINTLN	MSG_CANCELLED
	LD	B,7
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Parse command line:
;   TFTP.EXE host[:port] GET remote-file [-o local-name] [-y|-f overwrite]
;   TFTP.EXE host[:port] PUT local-file  [-o remote-name]
; ------------------------------------------------------
PARSE_CMD_LINE
	XOR	A
	LD	(TRANSFER_MODE),A
	LD	(HELP_REQUESTED),A
	LD	(FORCE_OVERWRITE),A
	LD	(OUTPUT_ABORTED),A
	LD	DE,DEFAULT_PORT
	LD	HL,PORT_BUFF
	CALL	COPY_ASCIIZ_HL
	LD	HL,(CMDLINE_PTR)
	LD	A,(HL)
	AND	A
	JP	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	PUSH	HL
	PUSH	BC
	CALL	IS_HOST_HELP
	POP	BC
	POP	HL
	JP	NC,.HELP
	PUSH	HL
	PUSH	BC
	CALL	SPLIT_HOST_PORT
	POP	BC
	POP	HL
	JP	C,.ERR
	LD	A,(HOST_BUFF)
	AND	A
	JP	Z,.ERR

	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,ARG1_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	PUSH	HL
	PUSH	BC
	CALL	IS_ARG1_GET
	POP	BC
	POP	HL
	JP	NC,.GET
	PUSH	HL
	PUSH	BC
	CALL	IS_ARG1_PUT
	POP	BC
	POP	HL
	JP	NC,.PUT
	JP	.ERR

.GET
	XOR	A
	LD	(TRANSFER_MODE),A
	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,REMOTE_FILE
	LD	C,REMOTE_FILE_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	JR	.OPTIONS

.PUT
	LD	A,1
	LD	(TRANSFER_MODE),A
	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR

.OPTIONS
	CALL	SKIP_SPACES
	JR	C,.DEFAULT_NAMES
	LD	DE,ARG2_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	PUSH	HL
	PUSH	BC
	CALL	IS_ARG2_OUTPUT
	POP	BC
	POP	HL
	JR	NC,.OUTPUT
	PUSH	HL
	PUSH	BC
	CALL	IS_ARG2_YES
	POP	BC
	POP	HL
	JR	NC,.YES
	PUSH	HL
	PUSH	BC
	CALL	IS_ARG2_HELP
	POP	BC
	POP	HL
	JR	NC,.HELP
	JR	.ERR
.OUTPUT
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,ARG3_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	; COPY_ASCIIZ_LIMIT below clobbers HL/BC, which still hold the cmdline
	; cursor; preserve them so a flag after `-o <name>` (e.g. trailing -y/-f)
	; is not read from garbage and lost.
	PUSH	HL
	PUSH	BC
	LD	A,(TRANSFER_MODE)
	AND	A
	JR	NZ,.PUT_REMOTE
	LD	HL,ARG3_BUFF
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	POP	BC
	POP	HL
	JR	NC,.OPTIONS
	JR	.ERR
.PUT_REMOTE
	LD	HL,ARG3_BUFF
	LD	DE,REMOTE_FILE
	LD	C,REMOTE_FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	POP	BC
	POP	HL
	JR	NC,.OPTIONS
	JR	.ERR
.YES
	LD	A,1
	LD	(FORCE_OVERWRITE),A
	JR	.OPTIONS
.DEFAULT_NAMES
	LD	A,(TRANSFER_MODE)
	AND	A
	JR	NZ,.DEFAULT_PUT_REMOTE
	LD	A,(OUT_FILE)
	AND	A
	CALL	Z,BUILD_LOCAL_FROM_REMOTE
	RET	NC
	JR	.ERR
.DEFAULT_PUT_REMOTE
	LD	A,(REMOTE_FILE)
	AND	A
	CALL	Z,BUILD_REMOTE_FROM_LOCAL
	RET	NC
	JR	.ERR
.HELP
	LD	A,1
	LD	(HELP_REQUESTED),A
	RET
.ERR
	SCF
	RET

IS_HOST_HELP
	LD	DE,HOST_BUFF
	JR	IS_HELP_TOKEN

IS_ARG2_HELP
	LD	DE,ARG2_BUFF
IS_HELP_TOKEN
	LD	HL,SWITCH_HELP_Q_SLASH
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_HELP_Q_DASH
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_HELP_H_SLASH
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_HELP_H_DASH
	JP	UTIL.STRCMP_CI

IS_ARG1_GET
	LD	HL,SWITCH_GET
	LD	DE,ARG1_BUFF
	JP	UTIL.STRCMP_CI

IS_ARG1_PUT
	LD	HL,SWITCH_PUT
	LD	DE,ARG1_BUFF
	JP	UTIL.STRCMP_CI

IS_ARG2_OUTPUT
	LD	HL,SWITCH_OUTPUT_DASH
	LD	DE,ARG2_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_OUTPUT_SLASH
	LD	DE,ARG2_BUFF
	JP	UTIL.STRCMP_CI

; Overwrite flag: -y / /y, plus -f / /f as a clearer "force" alias.
; (TFTP is a lockstep protocol with no resume, so there is no -r here.)
IS_ARG2_YES
	LD	HL,SWITCH_YES_DASH
	LD	DE,ARG2_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_YES_SLASH
	LD	DE,ARG2_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_FORCE_DASH
	LD	DE,ARG2_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_FORCE_SLASH
	LD	DE,ARG2_BUFF
	JP	UTIL.STRCMP_CI

SPLIT_HOST_PORT
	LD	HL,HOST_BUFF
.NEXT
	LD	A,(HL)
	AND	A
	RET	Z
	CP	':'
	JR	Z,.FOUND
	INC	HL
	JR	.NEXT
.FOUND
	XOR	A
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	LD	DE,PORT_BUFF
	LD	C,PORT_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	RET
.ERR
	SCF
	RET

SKIP_SPACES
	LD	A,B
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	XOR	A
	LD	(ARG_LEN),A
.NEXT
	LD	A,B
	AND	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	DEC	C
	LD	A,(ARG_LEN)
	INC	A
	LD	(ARG_LEN),A
	JR	.NEXT
.END
	XOR	A
	LD	(DE),A
	LD	A,(ARG_LEN)
	AND	A
	RET	NZ
.ERR
	SCF
	RET

COPY_ASCIIZ_HL
	LD	A,(DE)
	LD	(HL),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ_HL

COPY_ASCIIZ_LIMIT
	LD	A,(HL)
	AND	A
	JR	Z,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	COPY_ASCIIZ_LIMIT
.END
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET

BUILD_LOCAL_FROM_REMOTE
	LD	IX,REMOTE_FILE
	LD	HL,REMOTE_FILE
	JR	BUILD_BASENAME_TO_OUT

BUILD_REMOTE_FROM_LOCAL
	LD	IX,OUT_FILE
	LD	HL,OUT_FILE
	JR	BUILD_BASENAME_TO_REMOTE

BUILD_BASENAME_TO_OUT
	CALL	FIND_BASENAME
	LD	A,(IX+0)
	AND	A
	JR	Z,.ERR
	PUSH	IX
	POP	HL
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	JP	COPY_ASCIIZ_LIMIT
.ERR
	SCF
	RET

BUILD_BASENAME_TO_REMOTE
	CALL	FIND_BASENAME
	LD	A,(IX+0)
	AND	A
	JR	Z,.ERR
	PUSH	IX
	POP	HL
	LD	DE,REMOTE_FILE
	LD	C,REMOTE_FILE_SIZE-1
	JP	COPY_ASCIIZ_LIMIT
.ERR
	SCF
	RET

FIND_BASENAME
	LD	A,(HL)
	AND	A
	RET	Z
	CP	'/'
	JR	Z,.SLASH
	CP	'\'
	JR	Z,.SLASH
	INC	HL
	JR	FIND_BASENAME
.SLASH
	INC	HL
	PUSH	HL
	POP	IX
	JR	FIND_BASENAME

; ------------------------------------------------------
; TFTP RRQ download.
; ------------------------------------------------------
TRANSFER_TFTP
	LD	A,(TRANSFER_MODE)
	AND	A
	JP	NZ,UPLOAD_WRQ

DOWNLOAD_RRQ
	LD	HL,1
	LD	(EXPECTED_BLOCK),HL
	CALL	BUILD_RRQ_PACKET
	CALL	SEND_PACKET
	RET	C
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A

.RECV_NEXT
	CALL	WCOMMON.CHECK_CANCEL
	JP	C,CANCEL_EXIT
	; Each TFTP DATA is its own UDP datagram. If a previous READ_PAYLOAD
	; timed out mid-datagram, PAYLOAD_LEFT is still non-zero, and the next
	; RECEIVE would skip WAIT_IPD_HEADER and start eating the +IPD header
	; of the retransmitted block as if it were data. Force a fresh +IPD
	; parse on every attempt.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	XOR	A
	LD	(TCP.LSR_ACCUM),A			; clear sticky LSR error bits
	CALL	RECEIVE_PACKET_RETRY
	JR	C,.RX_TIMEOUT
	; UART overrun (or other LSR error) detected during this RECEIVE
	; means the +IPD payload is misaligned — even a "correct"-looking
	; TFTP header at byte 0 is just a coincidence of corrupted bytes.
	; Drain the UART, scrub state and force the same retry path as a
	; protocol error (server retransmits DATA after no-ACK timeout).
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	JR	NZ,.RX_CORRUPT
	CALL	HANDLE_PACKET
	JR	C,.HANDLE_FAIL
	; Reset the corruption-retry counter on every successful packet —
	; transient UART OE / ESP desync should not accumulate against later
	; blocks.
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A
	LD	A,(TRANSFER_DONE)
	AND	A
	JR	Z,.RECV_NEXT
	XOR	A
	RET

.RX_TIMEOUT
	; Receive returned an error. If LSR_ACCUM has any error bit set,
	; the failure was caused by OE/PE/FE corrupting the +IPD parser
	; mid-frame (the parser can return RES_RS_TIMEOUT *or* RES_ERROR
	; depending on where the corruption struck the length field) —
	; treat both as recoverable: DRAIN + ACK retransmit + retry. Without
	; this, OE that bubbles out as #1 (RES_ERROR from
	; READ_IPD_LEN.ERROR_BAD_CHAR) or #4 (RES_RS_TIMEOUT from a stuck
	; payload read) silently aborts a transfer that should retry.
	LD	C,A
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	JR	NZ,.RX_CORRUPT
	; Pure receive timeout (no data, no UART error). Propagate caller's
	; result code unchanged.
	LD	A,C
	SCF
	RET

.RX_CORRUPT
	; UART overrun: previous packet was lost / mis-aligned. Drain UART
	; state and re-send our last ACK *immediately* — without it, the
	; server's own retransmit timer (1–5 s) may be the only thing nudging
	; the next DATA, and if the server already retried during our drain
	; window it can give up before our next RECV_TIMEOUT (5 s) elapses.
	; The "Sorcerer's Apprentice" concern (RFC 1350) only matters when
	; we are exchanging ACKs for blocks the server has already seen ACKed;
	; here we never delivered the DATA, so an extra ACK for the previous
	; block is exactly what TFTP recovery expects.
	CALL	DRAIN_UART_AFTER_OE
	PRINTLN MSG_OVERRUN
	CALL	SEND_PACKET
	LD	HL,HANDLE_RETRIES
	DEC	(HL)
	JR	Z,.OE_GIVEUP
	JR	.RECV_NEXT
.OE_GIVEUP
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

.HANDLE_FAIL
	; Server-side TFTP ERROR (opcode 5) is fatal — propagate immediately.
	; Anything else (PROTO_ERR — header that *parsed* but didn't match
	; expected block) is recoverable: resend our last ACK to nudge the
	; server's retransmit logic, since its own timer might be far away.
	CP	RES_ERROR
	RET	Z
	PUSH	AF
	LD	HL,HANDLE_RETRIES
	DEC	(HL)
	JR	Z,.HANDLE_GIVEUP
	POP	AF
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	.RECV_NEXT
.HANDLE_GIVEUP
	POP	AF
	SCF
	RET

BUILD_RRQ_PACKET
	LD	HL,PACKET_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),1
	INC	HL
	LD	DE,REMOTE_FILE
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,MODE_OCTET
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,PACKET_BUFFER
	AND	A
	SBC	HL,DE
	LD	BC,HL
	LD	(LAST_TX_LEN),BC
	LD	HL,PACKET_BUFFER
	LD	(LAST_TX_PTR),HL
	RET

; ------------------------------------------------------
; TFTP WRQ upload.
; ------------------------------------------------------
UPLOAD_WRQ
	LD	HL,0
	LD	(EXPECTED_BLOCK),HL
	CALL	BUILD_WRQ_PACKET
	CALL	SEND_PACKET
	RET	C
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	CALL	WAIT_ACK_WITH_RETRY
	RET	C

	LD	HL,1
	LD	(EXPECTED_BLOCK),HL
.NEXT_BLOCK
	CALL	WCOMMON.CHECK_CANCEL
	JP	C,CANCEL_EXIT
	CALL	BUILD_DATA_PACKET_FROM_FILE
	RET	C
	CALL	SEND_PACKET
	RET	C
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A
	; See note in DOWNLOAD_RRQ — clear stale PAYLOAD_LEFT before each ACK
	; receive so a previous mid-packet timeout doesn't desync the next
	; +IPD header parse.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	CALL	WAIT_ACK_WITH_RETRY
	RET	C
	CALL	CHECK_UPLOAD_DONE
	RET	Z
	CALL	INC_EXPECTED_BLOCK
	JR	.NEXT_BLOCK

BUILD_WRQ_PACKET
	LD	HL,PACKET_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),2
	INC	HL
	LD	DE,REMOTE_FILE
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,MODE_OCTET
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,PACKET_BUFFER
	AND	A
	SBC	HL,DE
	LD	BC,HL
	LD	(LAST_TX_LEN),BC
	LD	HL,PACKET_BUFFER
	LD	(LAST_TX_PTR),HL
	RET

BUILD_DATA_PACKET_FROM_FILE
	LD	HL,PACKET_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),3
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	LD	(HL),A
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	LD	(HL),A

	; Pause RX during the slow DSS_READ_FILE; resume so SEND_PACKET that
	; follows can read its '>' / SEND OK via WAIT_PROMPT.
	CALL	WIFI.UART_RX_PAUSE
	LD	A,(IN_FH)
	LD	HL,PACKET_BUFFER+4
	LD	DE,TFTP_DATA_SIZE
	LD	C,DSS_READ_FILE
	RST	DSS
	PUSH	AF,DE
	CALL	WIFI.UART_RX_RESUME
	POP	DE,AF
	JR	C,.FILE_ERROR
	LD	(LAST_DATA_LEN),DE
	LD	BC,DE
	INC	BC
	INC	BC
	INC	BC
	INC	BC
	LD	(LAST_TX_LEN),BC
	LD	HL,PACKET_BUFFER
	LD	(LAST_TX_PTR),HL
	XOR	A
	RET
.FILE_ERROR
	LD	(FILE_ERROR_CODE),A
	LD	A,1
	LD	(FILE_ERROR_FLAG),A
	SCF
	RET

; Wrap RECEIVE_ACK_RETRY with corruption-retry. Caller must initialise
; HANDLE_RETRIES before invoking. On a PROTO_ERR (RES_RS_TIMEOUT from
; HANDLE_ACK_PACKET) we resend the last packet and try again, until the
; corruption budget is exhausted or a fatal/server error occurs.
WAIT_ACK_WITH_RETRY
	; Reset stale PAYLOAD_LEFT (see DOWNLOAD_RRQ note).
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	XOR	A
	LD	(TCP.LSR_ACCUM),A
	CALL	RECEIVE_ACK_RETRY
	JR	C,.RECV_FAIL
	; Same OE check as in download — corrupt UART means the +IPD parser
	; landed on misaligned bytes, so even a "correct"-looking ACK is just
	; a coincidence. Drain and retry.
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	JR	NZ,.RX_CORRUPT
	XOR	A
	RET

.RECV_FAIL
	; If a UART error bit is set, the receive failure was caused by OE
	; corrupting the +IPD parser — recover via DRAIN + retransmit nudge.
	; Preserve A (RECEIVE_ACK_RETRY's result) across the LSR check so
	; non-OE error codes still propagate via the normal path below.
	LD	C,A
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	JR	NZ,.RX_CORRUPT
	LD	A,C
	CP	RES_RS_TIMEOUT
	RET	NZ							; not a recoverable case
	JR	.RETRY

.RX_CORRUPT
	; OE on ACK reception. Resend our last DATA packet so the server,
	; which may be waiting for our ACK and hold off retransmit, sees
	; activity and either ACKs again or re-sends. Same rationale as
	; DOWNLOAD_RRQ.RX_CORRUPT.
	CALL	DRAIN_UART_AFTER_OE
	PRINTLN MSG_OVERRUN
	CALL	SEND_PACKET
	LD	HL,HANDLE_RETRIES
	DEC	(HL)
	JR	Z,.GIVEUP
	JR	WAIT_ACK_WITH_RETRY
.RETRY
	LD	HL,HANDLE_RETRIES
	DEC	(HL)
	JR	Z,.GIVEUP
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	WAIT_ACK_WITH_RETRY
.GIVEUP
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

RECEIVE_ACK_RETRY
	LD	A,RETRY_LIMIT
	LD	(RETRIES_LEFT),A
.TRY
	; Force fresh +IPD parse on every attempt — see DOWNLOAD_RRQ note.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	LD	HL,PACKET_BUFFER
	LD	BC,TFTP_PACKET_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	UDP.RECEIVE
	JR	NC,.GOT_PACKET
	CP	RES_RS_TIMEOUT
	RET	NZ
	LD	HL,RETRIES_LEFT
	DEC	(HL)
	JR	Z,.TIMEOUT
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	.TRY
.TIMEOUT
	LD	A,RES_RS_TIMEOUT
	SCF
	RET
.GOT_PACKET
	CALL	HANDLE_ACK_PACKET
	RET

HANDLE_ACK_PACKET
	LD	(RECV_LEN),BC
	LD	HL,(RECV_LEN)
	LD	DE,4
	CALL	HL_LT_DE
	JR	C,.PROTO_ERR
	LD	HL,PACKET_BUFFER
	LD	A,(HL)
	AND	A
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(HL)
	CP	4
	JR	Z,.ACK
	CP	5
	JR	Z,.TFTP_ERROR
	JR	.PROTO_ERR
.ACK
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	CP	(HL)
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	CP	(HL)
	JR	NZ,.PROTO_ERR
	XOR	A
	RET
.TFTP_ERROR
	CALL	PRINT_TFTP_ERROR
	LD	A,RES_ERROR
	SCF
	RET
.PROTO_ERR
	; See note in HANDLE_PACKET.PROTO_ERR — RES_RS_TIMEOUT marks this
	; failure as recoverable (corrupt ACK, retransmit DATA may help).
	PRINTLN MSG_PROTO_ERROR
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

CHECK_UPLOAD_DONE
	LD	HL,(LAST_DATA_LEN)
	LD	DE,TFTP_DATA_SIZE
	CALL	HL_LT_DE
	JR	C,.DONE
	PRINT MSG_PROGRESS
	OR	1
	RET
.DONE
	XOR	A
	RET

BUILD_ACK_PACKET
	LD	HL,ACK_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),4
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	LD	(HL),A
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	LD	(HL),A
	LD	HL,ACK_BUFFER
	LD	(LAST_TX_PTR),HL
	LD	BC,4
	LD	(LAST_TX_LEN),BC
	RET

SEND_PACKET
	LD	HL,(LAST_TX_PTR)
	LD	BC,(LAST_TX_LEN)
	; TFTP DATA/ACK packets can arrive before ESP reports SEND OK. Let the
	; subsequent RECEIVE consume command text and retain the first +IPD frame.
	JP	UDP.SEND_BUFFER_NO_WAIT

RECEIVE_PACKET_RETRY
	LD	A,RETRY_LIMIT
	LD	(RETRIES_LEFT),A
.TRY
	; Force fresh +IPD parse on every attempt — see DOWNLOAD_RRQ note.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	LD	HL,PACKET_BUFFER
	LD	BC,TFTP_PACKET_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	UDP.RECEIVE
	RET	NC
	CP	RES_RS_TIMEOUT
	RET	NZ
	LD	HL,RETRIES_LEFT
	DEC	(HL)
	JR	Z,.TIMEOUT
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	.TRY
.TIMEOUT
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

; ------------------------------------------------------
; Recover from a UART overrun: hold RTS low, give ESP up to ~50 ms to drain any
; bytes still queued in its UART TX buffer, reset the 16550 RX FIFO and clear
; the sticky LSR_ACCUM. RX is resumed on exit so the
; subsequent retry path (PRINTLN "UART overrun, retrying" + next
; RECEIVE) and any intermediate SEND_PACKET work normally.
; ------------------------------------------------------
DRAIN_UART_AFTER_OE
	PUSH	AF,BC,DE,HL
	CALL	@WIFI.UART_RX_PAUSE
	LD	HL,50
	CALL	@UTIL.DELAY
	CALL	@WIFI.UART_EMPTY_RS
	XOR	A
	LD	(TCP.LSR_ACCUM),A
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	LD	(TCP.LAST_IPD_LEN),HL
	CALL	@WIFI.UART_RX_RESUME
	POP	HL,DE,BC,AF
	RET

; Never send CIPCLOSE while a partial +IPD packet is still pending: that mixes
; AT text with binary data and can leave ESP's UDP state wedged for the next
; program. This is the same cleanup rule as NTP, using TFTP's existing drain.
ABORT_UDP_SESSION
	LD	A,(UDP_IS_OPEN)
	AND	A
	RET	Z
	CALL	DRAIN_UART_AFTER_OE
	CALL	WCOMMON.CLEAN_ESP_LINKS
	XOR	A
	LD	(UDP_IS_OPEN),A
	RET

HANDLE_PACKET
	LD	(RECV_LEN),BC
	LD	A,B
	OR	C
	JR	Z,.PROTO_ERR
	LD	HL,(RECV_LEN)
	LD	DE,4
	CALL	HL_LT_DE
	JR	C,.PROTO_ERR

	LD	HL,PACKET_BUFFER
	LD	A,(HL)
	AND	A
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(HL)
	CP	3
	JR	Z,.DATA
	CP	5
	JR	Z,.TFTP_ERROR
	JR	.PROTO_ERR

.DATA
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	CP	(HL)
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	CP	(HL)
	JR	NZ,.PROTO_ERR

	; Pause RX during the slow DSS_WRITE so ESP can't push next-block
	; bytes into a 16-byte FIFO we aren't draining. RESUME before ACK
	; build/send so SEND_BUFFER's WAIT_PROMPT can read the '>' / SEND OK
	; responses.
	CALL	WIFI.UART_RX_PAUSE
	CALL	WRITE_DATA_PAYLOAD
	PUSH	AF
	CALL	WIFI.UART_RX_RESUME
	POP	AF
	RET	C
	CALL	BUILD_ACK_PACKET
	CALL	SEND_PACKET
	RET	C
	CALL	CHECK_FINAL_BLOCK
	CALL	INC_EXPECTED_BLOCK
	XOR	A
	RET

.TFTP_ERROR
	CALL	PRINT_TFTP_ERROR
	LD	A,RES_ERROR
	SCF
	RET
.PROTO_ERR
	; Use RES_RS_TIMEOUT (not RES_ERROR) so the caller's recovery path
	; can distinguish a corrupt/desynced packet (retransmit may help)
	; from a server-issued TFTP ERROR (fatal).
	PRINTLN MSG_PROTO_ERROR
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

WRITE_DATA_PAYLOAD
	LD	BC,(RECV_LEN)
	DEC	BC
	DEC	BC
	DEC	BC
	DEC	BC
	LD	A,B
	OR	C
	RET	Z
	LD	HL,PACKET_BUFFER+4
	LD	A,(OUT_FH)
	LD	D,B
	LD	E,C
	LD	C,DSS_WRITE
	RST	DSS
	RET

CHECK_FINAL_BLOCK
	LD	HL,(RECV_LEN)
	LD	DE,TFTP_PACKET_SIZE
	CALL	HL_LT_DE
	JR	NC,.MORE
	LD	A,1
	LD	(TRANSFER_DONE),A
	RET
.MORE
	CALL	PRINT_PROGRESS_KB
	RET

INC_EXPECTED_BLOCK
	LD	HL,(EXPECTED_BLOCK)
	INC	HL
	LD	(EXPECTED_BLOCK),HL
	RET

HL_LT_DE
	LD	A,H
	CP	D
	RET	NZ
	LD	A,L
	CP	E
	RET

; ------------------------------------------------------
; File helpers.
; ------------------------------------------------------
OPEN_OUTPUT_FILE
	LD	HL,OUT_FILE
	LD	A,FA_READONLY
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.CREATE
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,(FORCE_OVERWRITE)
	AND	A
	JR	NZ,.DELETE
	CALL	CONFIRM_OVERWRITE
	JR	C,.ABORT
.DELETE
	LD	HL,OUT_FILE
	LD	C,DSS_DELETE
	RST	DSS
.CREATE
	LD	HL,OUT_FILE
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	RET	C
	LD	(OUT_FH),A
	XOR	A
	LD	(OUTPUT_ABORTED),A
	RET
.ABORT
	LD	A,1
	LD	(OUTPUT_ABORTED),A
	SCF
	RET

CONFIRM_OVERWRITE
	PRINT	MSG_OVERWRITE_PRE
	PRINT	OUT_FILE
	PRINT	MSG_OVERWRITE_POST
	LD	C,DSS_WAITKEY
	RST	DSS
	PUSH	AF
	LD	C,DSS_PUTCHAR
	RST	DSS
	LD	A,13
	LD	C,DSS_PUTCHAR
	RST	DSS
	LD	A,10
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	AF
	CP	'Y'
	RET	Z
	CP	'y'
	RET	Z
	SCF
	RET

OPEN_INPUT_FILE
	LD	HL,OUT_FILE
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	RET	C
	LD	(IN_FH),A
	RET

OPEN_TRANSFER_FILE
	LD	A,(TRANSFER_MODE)
	AND	A
	JP	NZ,OPEN_INPUT_FILE
	JP	OPEN_OUTPUT_FILE

CLOSE_OUTPUT_FILE
	LD	A,(OUT_FH)
	CP	NO_HANDLE
	RET	Z
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,NO_HANDLE
	LD	(OUT_FH),A
	RET

CLOSE_INPUT_FILE
	LD	A,(IN_FH)
	CP	NO_HANDLE
	RET	Z
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,NO_HANDLE
	LD	(IN_FH),A
	RET

CLOSE_FILES
	CALL	CLOSE_OUTPUT_FILE
	RET	C
	JP	CLOSE_INPUT_FILE

CLOSE_FILES_IGNORE
	CALL	CLOSE_OUTPUT_FILE
	CALL	CLOSE_INPUT_FILE
	RET

PRINT_FILE_ERROR
	PRINT	MSG_FILE_ERROR
	CALL	DSS_ERROR.GET_ERR_MSG
	PRINTLN_HL
	RET

; ------------------------------------------------------
; ESP/UDP command helpers.
; ------------------------------------------------------
SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	RET	Z
	JP	UDP_ERROR_EXIT

SEND_CMD_RECOVER
	PUSH	HL
	CALL	WCOMMON.SYNC_ESP_COMMAND
	POP	HL
	JP	SEND_CMD

VERIFY_UDP_OPEN
	LD	HL,CMD_CIPSTATUS
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	NZ,.ERR
	LD	HL,WIFI.RS_BUFF
	LD	DE,UDP_STATUS_TOKEN
	CALL	FIND_SUBSTR
	RET	NC
	PRINTLN MSG_UDP_NOT_CONFIRMED
.ERR
	LD	A,RES_ERROR
	SCF
	RET

FIND_SUBSTR
	LD	A,(DE)
	AND	A
	RET	Z
.NEXT_START
	LD	A,(HL)
	AND	A
	JR	Z,.NOT_FOUND
	PUSH	HL
	PUSH	DE
.MATCH
	LD	A,(DE)
	AND	A
	JR	Z,.FOUND_POP
	LD	B,A
	LD	A,(HL)
	AND	A
	JR	Z,.NO_MATCH_POP
	CP	B
	JR	NZ,.NO_MATCH_POP
	INC	HL
	INC	DE
	JR	.MATCH
.FOUND_POP
	POP	DE
	POP	HL
	XOR	A
	RET
.NO_MATCH_POP
	POP	DE
	POP	HL
	INC	HL
	JR	.NEXT_START
.NOT_FOUND
	SCF
	RET

APPEND_STR_TO_HL
	LD	A,(DE)
	LD	(HL),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	APPEND_STR_TO_HL

PRINT_SOURCE_INFO
	PRINT MSG_REMOTE
	PRINT HOST_BUFF
	PRINT MSG_COLON
	PRINT PORT_BUFF
	PRINT MSG_SLASH
	PRINT REMOTE_FILE
	PRINT WCOMMON.LINE_END
	LD	A,(TRANSFER_MODE)
	AND	A
	JR	NZ,.INPUT
	PRINT MSG_OUTPUT
	JR	.FILE
.INPUT
	PRINT MSG_INPUT
.FILE
	PRINT OUT_FILE
	PRINT WCOMMON.LINE_END
	RET

PRINT_TFTP_ERROR
	PRINT MSG_TFTP_ERROR
	LD	HL,PACKET_BUFFER+4
	LD	B,80
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.DONE
	LD	C,DSS_PUTCHAR
	RST	DSS
	INC	HL
	DJNZ	.NEXT
.DONE
	PRINT WCOMMON.LINE_END
	RET

CLEAR_BSS
	LD	HL,TFTP_BSS_BASE
	LD	DE,TFTP_BSS_BASE+1
	LD	BC,TFTP_BSS_END-TFTP_BSS_BASE-1
	LD	(HL),0
	LDIR
	RET

INIT_RUNTIME_PAGE
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	RET	C
	LD	B,0
	LD	C,DSS_SETWIN2
	RST	DSS
	RET

INIT_MEMORY_ERROR
	LD	B,3
	LD	C,DSS_EXIT
	RST	DSS

MSG_START
	DB "TFTP "
	PACKAGE_VERSION_TAG
	DB " - UDP TFTP client for SprinterESP"
	DB 0
MSG_USAGE
	DB "Usage: TFTP.EXE host[:port] GET remote [-o local] [-y|-f]",13,10
	DB "       TFTP.EXE host[:port] PUT local [-o remote]",13,10
	DB "  -o name   local name (get) / remote name (put)",13,10
	DB "  -y, -f    overwrite an existing local file (no resume in TFTP)",13,10
	DB "  /?        show this help",0
MSG_REMOTE
	DB "Remote file: ",0
MSG_OUTPUT
	DB "Output file: ",0
MSG_INPUT
	DB "Input file: ",0
MSG_UART_READY
	DB "UART initialized.",0
MSG_CONNECTING
	DB "Opening UDP endpoint to ",0
MSG_COLON
	DB ":",0
MSG_SLASH
	DB "/",0
MSG_RETRY
	DB "Timeout, retrying.",0
MSG_PROGRESS
	DB ".",0
MSG_CR_ONLY
	DB 13,0			; reset X to column 0 (this console: 0x0D=CR, 0x0A=LF)
MSG_KB_UNK
	DB "KB / ?",0
MSG_DONE
	DB "TFTP done.",0
MSG_WIFI_NOT_FOUND
	DB "Sprinter-WiFi not found!",0
MSG_FILE_ERROR
	DB "File error: ",0
MSG_ABORTED
	DB "Aborted by user.",0
MSG_OVERWRITE_PRE
	DB "Local file '",0
MSG_OVERWRITE_POST
	DB "' exists. Overwrite [Y/N]? ",0
MSG_NET_ERROR
	DB "Network/ESP error #"
MSG_ERROR_NO
	DB "n!",0
; Plain-language hints for the RES_* codes, printed under "Network/ESP error #N".
; Indexed by code; a 0 entry means "no hint for this code". TFTP is UDP, so the
; wording avoids TCP "connection refused".
NET_REASON_COUNT	EQU 7
NET_REASON_TABLE
	DW 0			; 0 RES_OK (not an error)
	DW MSG_NETR_ERR		; 1 RES_ERROR
	DW MSG_NETR_FAIL	; 2 RES_FAIL
	DW MSG_NETR_TXTO	; 3 RES_TX_TIMEOUT
	DW MSG_NETR_RXTO	; 4 RES_RS_TIMEOUT
	DW 0			; 5 RES_CONNECTED
	DW MSG_NETR_NOCONN	; 6 RES_NOT_CONN
MSG_NETR_ERR
	DB "Could not set up the transfer: wrong address/DNS, host",13,10
	DB "unreachable, or Wi-Fi not up (run NETUP).",0
MSG_NETR_FAIL
	DB "The network operation failed.",0
MSG_NETR_TXTO
	DB "Sprinter-WiFi (ESP) did not respond - check the card and cabling.",0
MSG_NETR_RXTO
	DB "No reply from the server - it may be down or too slow (timeout).",0
MSG_NETR_NOCONN
	DB "The transfer was interrupted before it finished.",0
MSG_PROTO_ERROR
	DB "Unexpected TFTP packet.",0
MSG_OVERRUN
	DB "UART overrun, retrying.",0
MSG_TFTP_ERROR
	DB "TFTP error: ",0
MSG_UDP_NOT_CONFIRMED
	DB "UDP socket was not confirmed by ESP status.",0
MSG_CANCELLED
	DB "Cancelled by user.",0
MSG_DEBUG
	DB "TFTP debug:",0
MSG_DEBUG_BLOCK
	DB " block=",0
MSG_DEBUG_IPD
	DB " ipd=",0
MSG_DEBUG_LEFT
	DB " left=",0
MSG_DEBUG_LSR
	DB " lsr=0x",0
MSG_DEBUG_ACC
	DB " lsr_acc=0x",0
HEX_PRINT_BUFF
	DB "xx",0

CMD_AT
	DB "AT",13,10,0
CMD_ECHO_OFF
	DB "ATE0",13,10,0
CMD_CIPMUX_0
	DB "AT+CIPMUX=0",13,10,0
CMD_CIPSTATUS
	DB "AT+CIPSTATUS",13,10,0
UDP_STATUS_TOKEN
	DB "UDP",0

SWITCH_GET
	DB "GET",0
SWITCH_PUT
	DB "PUT",0
SWITCH_OUTPUT_DASH
	DB "-o",0
SWITCH_OUTPUT_SLASH
	DB "/o",0
SWITCH_YES_DASH
	DB "-y",0
SWITCH_YES_SLASH
	DB "/y",0
SWITCH_FORCE_DASH
	DB "-f",0
SWITCH_FORCE_SLASH
	DB "/f",0
SWITCH_HELP_Q_SLASH
	DB "/?",0
SWITCH_HELP_Q_DASH
	DB "-?",0
SWITCH_HELP_H_SLASH
	DB "/h",0
SWITCH_HELP_H_DASH
	DB "-h",0
DEFAULT_PORT
	DB "69",0
LOCAL_PORT
	DB "1069",0
MODE_OCTET
	DB "octet",0

ARG_LEN		DB 0
OUT_FH		DB NO_HANDLE
IN_FH		DB NO_HANDLE
UDP_IS_OPEN	DB 0
TRANSFER_DONE	DB 0
TRANSFER_MODE	DB 0
HELP_REQUESTED	DB 0
CMDLINE_PTR	DW 0		; arg buffer ptr captured from IX at entry
FORCE_OVERWRITE	DB 0
OUTPUT_ABORTED	DB 0
FILE_ERROR_FLAG DB 0
FILE_ERROR_CODE DB 0
RETRIES_LEFT	DB 0
HANDLE_RETRIES	DB 0
EXPECTED_BLOCK	DW 1
RECV_LEN	DW 0
LAST_TX_PTR	DW 0
LAST_TX_LEN	DW 0
LAST_DATA_LEN	DW 0

	ENDMODULE

	DEFINE ESP_TCP_BSS_BASE_OVERRIDE
ESP_TCP_BSS_BASE	EQU 0xB000

	INCLUDE "netcfg_lib.asm"
	DEFINE WCOMMON_USE_NETCFG
	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "esp_tcp.asm"
	INCLUDE "esp_udp.asm"
	; Universal TFTP uses the field-proven trigger-8 active receive path.
	; A forced 2.2.2 diagnostic image retains trigger 4.
	IFNDEF	ESP_AT_FORCE_222
	DEFINE	WIFI_STABLE_ACTIVE_RX
	ENDIF
	INCLUDE "esplib.asm"

	MODULE MAIN

	ASSERT	$ < STACK_TOP - 0x0100

; Place TFTP buffers AFTER TCP/UDP buffers, not just after NETCFG. The
; ESP_TCP_BSS_BASE override (0xB000) puts TCP/UDP CMD buffers inside the
; TFTP BSS range — HOST_BUFF then overlaps UDP CMD_BUFFER, and
; APPEND_IX_STR(HOST_BUFF) inside UDP.OPEN_LOCAL falls into an infinite
; loop reading from the buffer it's currently writing to (the bug that
; corrupted memory with repeated "AT+CIPSTART=\"UDP\",\"192.168.1." pattern).
TFTP_BSS_BASE	EQU UDP.UDP_BSS_END
NUM_PRINT_BUFF	EQU TFTP_BSS_BASE
ARG1_BUFF	EQU NUM_PRINT_BUFF + 8
ARG2_BUFF	EQU ARG1_BUFF + URL_SIZE
ARG3_BUFF	EQU ARG2_BUFF + URL_SIZE
URL_BUFF	EQU ARG3_BUFF + URL_SIZE
HOST_BUFF	EQU URL_BUFF + URL_SIZE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
REMOTE_FILE	EQU PORT_BUFF + PORT_SIZE
OUT_FILE	EQU REMOTE_FILE + REMOTE_FILE_SIZE
TFTP_BSS_END	EQU OUT_FILE + LOCAL_FILE_SIZE
PACKET_BUFFER	EQU WIN2_BASE
ACK_BUFFER	EQU PACKET_BUFFER + TFTP_PACKET_SIZE
	; PACKET_BUFFER is the DSS_WRITE source on download and DSS_READ_FILE
	; target on upload and uses allocated WIN2. Stack stays at #8000 and
	; grows downward in WIN1.
	ASSERT	TFTP_BSS_END < 0xC000
	ASSERT	ACK_BUFFER + 4 <= 0xC000

	ENDMODULE

	END MAIN.START
