; ======================================================
; UDPTEST for Sprinter ESP Network Kit
; Minimal UDP smoke test over ESP-AT.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
RECV_TIMEOUT		EQU 5000
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
MESSAGE_SIZE		EQU 128
RECV_BUFFER_SIZE	EQU 512

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	; Full 512-byte DSS EXE header. Long command lines are written
	; at 0x8080, so these tools must not use the compact header.
	ORG 0x7F00

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0200
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 490, 0

	ORG 0x8100
@STACK_TOP

START
	; DSS passes the command-line buffer pointer in IX at entry; capture it
	; before any CALL clobbers IX (load-#80 = 0x8080 is the default, not assumed).
	LD	(CMDLINE_PTR),IX
	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	INIT_DEFAULT_ARGS
	CALL	PARSE_CMD_LINE
	JP	C,USAGE

	PRINT	MSG_TARGET
	PRINT	HOST_BUFF
	PRINT	MSG_COLON
	PRINT	REMOTE_PORT_BUFF
	PRINT	MSG_LOCAL
	PRINT	LOCAL_PORT_BUFF
	PRINT	WCOMMON.LINE_END

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI
	CALL	WCOMMON.REQUIRE_NET_UP

	LD	A,(ISA.ISA_SLOT)
	ADD	A,'1'
	LD	(MSG_SLOT_NO),A
	PRINTLN MSG_WIFI_FOUND

	CALL	WCOMMON.APPLY_NET_BAUD		; baud from env NET_BAUD (NETUP session); utilities never read NET.CFG
	CALL	WIFI.UART_INIT
	PRINTLN MSG_UART_READY

	LD	HL,CMD_AT
	CALL	SEND_CMD_RECOVER

	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD

	; Verify the UART mode already selected from NET_ESP_FLOW.
	CALL	WCOMMON.SETUP_UART_FLOW
	AND	A
	JR	Z,.UART_FLOW_OK
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_COMM_ERROR
	LD	B,3
	JP	WCOMMON.EXIT
.UART_FLOW_OK

	CALL	WCOMMON.CLEAN_ESP_LINKS		; drop any link a prior run left open
	LD	HL,CMD_CIPMUX_0
	CALL	SEND_CMD

	PRINT MSG_CONNECTING
	PRINT HOST_BUFF
	PRINT WCOMMON.LINE_END
	LD	HL,HOST_BUFF
	LD	DE,REMOTE_PORT_BUFF
	LD	IX,LOCAL_PORT_BUFF
	CALL	UDP.OPEN_LOCAL
	CALL	CHECK_NET_ERROR
	LD	A,1
	LD	(SOCKET_OPEN),A
	CALL	VERIFY_UDP_OPEN
	CALL	CHECK_NET_ERROR

	PRINT MSG_SENDING
	PRINT MESSAGE_BUFF
	PRINT WCOMMON.LINE_END
	LD	HL,MESSAGE_BUFF
	CALL	UTIL.STRLEN
	CALL	UDP.SEND_BUFFER
	CALL	CHECK_NET_ERROR

	PRINTLN MSG_WAITING
	LD	HL,RECV_BUFFER
	LD	BC,RECV_BUFFER_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	UDP.RECEIVE
	CALL	CHECK_NET_ERROR
	LD	(RECV_LEN),BC
	LD	A,B
	OR	C
	JR	Z,.NO_REPLY

	PRINTLN MSG_RESPONSE
	LD	HL,RECV_BUFFER
	LD	BC,(RECV_LEN)
	CALL	PRINT_BUFFER
	PRINT WCOMMON.LINE_END
	JR	.CLOSE_OK

.NO_REPLY
	PRINTLN MSG_NO_REPLY
	JR	.CLOSE_OK

.CLOSE_OK
	CALL	UDP.CLOSE
	XOR	A
	LD	(SOCKET_OPEN),A
	PRINTLN MSG_DONE
	LD	B,0
	JP	WCOMMON.EXIT

NO_WIFI
	PRINTLN MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

USAGE
	PRINTLN MSG_USAGE
	LD	B,1
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Optional command line: UDPTEST.EXE host port [message [local_port]]
; ------------------------------------------------------
INIT_DEFAULT_ARGS
	LD	HL,DEFAULT_HOST
	LD	DE,HOST_BUFF
	CALL	COPY_ASCIIZ_DE
	LD	HL,DEFAULT_REMOTE_PORT
	LD	DE,REMOTE_PORT_BUFF
	CALL	COPY_ASCIIZ_DE
	LD	HL,DEFAULT_LOCAL_PORT
	LD	DE,LOCAL_PORT_BUFF
	CALL	COPY_ASCIIZ_DE
	LD	HL,DEFAULT_MESSAGE
	LD	DE,MESSAGE_BUFF
	JP	COPY_ASCIIZ_DE

PARSE_CMD_LINE
	LD	HL,(CMDLINE_PTR)
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,REMOTE_PORT_BUFF
	LD	C,PORT_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	PUSH	HL
	CALL	VALIDATE_REMOTE_PORT
	POP	HL
	JR	C,.ERR
	CALL	SKIP_SPACES
	RET	C
	LD	DE,MESSAGE_BUFF
	LD	C,MESSAGE_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	CALL	SKIP_SPACES
	JR	C,.OK
	LD	DE,LOCAL_PORT_BUFF
	LD	C,PORT_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	PUSH	HL
	CALL	VALIDATE_LOCAL_PORT
	POP	HL
	JR	C,.ERR
	CALL	SKIP_SPACES
	JR	NC,.ERR
.OK
	AND	A
	RET
.ERR
	SCF
	RET

SKIP_SPACES
	LD	A,B
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	XOR	A
	LD	(ARG_LEN),A
.NEXT
	LD	A,B
	AND	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	DEC	C
	LD	A,(ARG_LEN)
	INC	A
	LD	(ARG_LEN),A
	JR	.NEXT
.END
	XOR	A
	LD	(DE),A
	LD	A,(ARG_LEN)
	AND	A
	RET	NZ
.ERR
	SCF
	RET

VALIDATE_REMOTE_PORT
	LD	HL,REMOTE_PORT_BUFF
	JR	VALIDATE_PORT

VALIDATE_LOCAL_PORT
	LD	HL,LOCAL_PORT_BUFF

VALIDATE_PORT
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
.NEXT
	LD	A,(HL)
	AND	A
	RET	Z
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	INC	HL
	JR	.NEXT
.ERR
	SCF
	RET

COPY_ASCIIZ_DE
	LD	A,(HL)
	LD	(DE),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ_DE

; ------------------------------------------------------
; Send command in HL with default timeout.
; ------------------------------------------------------
SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	RET	Z
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_COMM_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Synchronize non-destructively, then send the command.
; ------------------------------------------------------
SEND_CMD_RECOVER
	PUSH	HL
	CALL	WCOMMON.SYNC_ESP_COMMAND
	POP	HL
	JP	SEND_CMD

; ------------------------------------------------------
; Exit on UDP helper failure.
; ------------------------------------------------------
CHECK_NET_ERROR
	RET	NC
	PUSH	AF
	CALL	PRINT_UDP_DEBUG
	LD	A,(SOCKET_OPEN)
	AND	A
	CALL	NZ,UDP.CLOSE
	XOR	A
	LD	(SOCKET_OPEN),A
	POP	AF
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_COMM_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

PRINT_UDP_DEBUG
	PRINT	MSG_DEBUG
	PRINT	MSG_DEBUG_IPD
	LD	HL,(TCP.LAST_IPD_LEN)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_BAD
	LD	A,(TCP.IPD_BAD_CHAR)
	CALL	PRINT_A_HEX
	PRINT	MSG_DEBUG_LSR
	LD	A,(TCP.LAST_LSR)
	CALL	PRINT_A_HEX
	PRINT	MSG_DEBUG_ACC
	LD	A,(TCP.LSR_ACCUM)
	CALL	PRINT_A_HEX
	PRINT	WCOMMON.LINE_END
	RET

PRINT_HL_DEC
	LD	DE,NUM_PRINT_BUFF
	CALL	UTIL.UTOA
	PRINT	NUM_PRINT_BUFF
	RET

PRINT_A_HEX
	LD	C,A
	LD	DE,HEX_PRINT_BUFF
	CALL	UTIL.HEXB
	PRINT	HEX_PRINT_BUFF
	RET

; ------------------------------------------------------
; Confirm that ESP-AT really opened a UDP socket. Some emulators may return
; OK for unsupported AT+CIPSTART="UDP",... and then fail hard on CIPSEND.
; ------------------------------------------------------
VERIFY_UDP_OPEN
	LD	HL,CMD_CIPSTATUS
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	NZ,.ERR
	LD	HL,WIFI.RS_BUFF
	LD	DE,UDP_STATUS_TOKEN
	CALL	FIND_SUBSTR
	RET	NC
	PRINTLN MSG_UDP_NOT_CONFIRMED
.ERR
	LD	A,RES_ERROR
	SCF
	RET

; ------------------------------------------------------
; Find ASCIIZ substring.
; In: HL - haystack, DE - needle.
; Out: CF=0 if found, CF=1 otherwise.
; ------------------------------------------------------
FIND_SUBSTR
	LD	A,(DE)
	AND	A
	RET	Z
.NEXT_START
	LD	A,(HL)
	AND	A
	JR	Z,.NOT_FOUND
	PUSH	HL
	PUSH	DE
.MATCH
	LD	A,(DE)
	AND	A
	JR	Z,.FOUND_POP
	LD	B,A
	LD	A,(HL)
	AND	A
	JR	Z,.NO_MATCH_POP
	CP	B
	JR	NZ,.NO_MATCH_POP
	INC	HL
	INC	DE
	JR	.MATCH
.FOUND_POP
	POP	DE
	POP	HL
	XOR	A
	RET
.NO_MATCH_POP
	POP	DE
	POP	HL
	INC	HL
	JR	.NEXT_START
.NOT_FOUND
	SCF
	RET

; ------------------------------------------------------
; Print raw UDP data as console text.
; In: HL - data, BC - length.
; ------------------------------------------------------
PRINT_BUFFER
	LD	A,B
	OR	C
	RET	Z
	LD	A,(HL)
	INC	HL
	DEC	BC
	CP	13
	JR	Z,PRINT_BUFFER
	CP	10
	JR	NZ,.CHAR
	LD	A,13
	CALL	PUT_CHAR
	LD	A,10
	JR	.PUT
.CHAR
	CP	32
	JR	NC,.PUT
	LD	A,'.'
.PUT
	CALL	PUT_CHAR
	JR	PRINT_BUFFER

PUT_CHAR
	PUSH	BC,HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL,BC
	RET

MSG_START
	DB "UDPTEST "
	PACKAGE_VERSION_TAG
	DB " - ESP-AT UDP smoke test"
	DB 0
MSG_USAGE
	DB "Usage: UDPTEST.EXE host port [message [local_port]]",0
MSG_TARGET
	DB "Run NETUP first. UDP target is ",0
MSG_LOCAL
	DB ", local ",0
MSG_WIFI_FOUND
	DB "Sprinter-WiFi found in ISA#"
MSG_SLOT_NO
	DB "n slot.",0
MSG_WIFI_NOT_FOUND
	DB "Sprinter-WiFi not found!",0
MSG_UART_READY
	DB "UART initialized.",0
MSG_CONNECTING
	DB "Opening UDP endpoint to ",0
MSG_COLON
	DB ":",0
MSG_SENDING
	DB "Sending: ",0
MSG_WAITING
	DB "Waiting for UDP reply.",0
MSG_RESPONSE
	DB "Response:",0
MSG_NO_REPLY
	DB "No UDP reply received.",0
MSG_DONE
	DB "UDPTEST done.",0
MSG_COMM_ERROR
	DB "ESP/UDP communication error #"
MSG_ERROR_NO
	DB "n!",0
MSG_DEBUG
	DB "UDP debug:",0
MSG_DEBUG_IPD
	DB " ipd=",0
MSG_DEBUG_BAD
	DB " bad=0x",0
MSG_DEBUG_LSR
	DB " lsr=0x",0
MSG_DEBUG_ACC
	DB " acc=0x",0
MSG_UDP_NOT_CONFIRMED
	DB "UDP socket was not confirmed by ESP status.",0

CMD_AT
	DB "AT",13,10,0
CMD_ECHO_OFF
	DB "ATE0",13,10,0
CMD_CIPMUX_0
	DB "AT+CIPMUX=0",13,10,0
CMD_CIPSTATUS
	DB "AT+CIPSTATUS",13,10,0
UDP_STATUS_TOKEN
	DB "UDP",0

DEFAULT_HOST
	DB "127.0.0.1",0
DEFAULT_REMOTE_PORT
	DB "7",0
DEFAULT_LOCAL_PORT
	DB "1069",0
DEFAULT_MESSAGE
	DB "Sprinter UDP test",0

ARG_LEN
	DB 0
CMDLINE_PTR
	DW 0			; arg buffer ptr captured from IX at entry
SOCKET_OPEN
	DB 0
HEX_PRINT_BUFF
	DB "xx",0
RECV_LEN
	DW 0

	ENDMODULE

; Keep ESP helper scratch buffers outside UDPTEST code/data.  The default
; TCP base depends on WIFI.RS_BUFF, which is defined in esplib.asm after the
; TCP/UDP helpers are assembled here.
	DEFINE ESP_TCP_BSS_BASE_OVERRIDE
ESP_TCP_BSS_BASE	EQU 0xB000

	INCLUDE "netcfg_lib.asm"
	DEFINE WCOMMON_USE_NETCFG
	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "esp_tcp.asm"
	INCLUDE "esp_udp.asm"
	INCLUDE "esplib.asm"

	MODULE MAIN

; Place UDPTEST buffers AFTER TCP/UDP buffers — see analogous comment in
; tftp.asm. RECV_BUFFER would otherwise overlap UDP CMD_BUFFER and either
; corrupt incoming packets or feed garbage back into ESP commands.
NUM_PRINT_BUFF	EQU UDP.UDP_BSS_END
HOST_BUFF	EQU NUM_PRINT_BUFF + 8
REMOTE_PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
LOCAL_PORT_BUFF	EQU REMOTE_PORT_BUFF + PORT_SIZE
MESSAGE_BUFF	EQU LOCAL_PORT_BUFF + PORT_SIZE
RECV_BUFFER	EQU MESSAGE_BUFF + MESSAGE_SIZE
UDPTEST_BSS_END	EQU RECV_BUFFER + RECV_BUFFER_SIZE

	ENDMODULE

	END MAIN.START
