; ======================================================
; WGET for Sprinter ESP Network Kit
; Minimal HTTP/1.0 downloader over ESP-AT TCP.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
RECV_TIMEOUT		EQU 7000
CLOSED_DRAIN_TIMEOUT	EQU 1500
TCP_OPEN_RETRY_DELAY	EQU 500
MUX_RECOVERY_DELAY	EQU 250
RECV_BUFFER_SIZE	EQU 16384
; Retain-tail margin: once the announced body is within this many bytes of
; completion we stop pausing for DSS_WRITE and instead accumulate the final
; bytes in RECV_BUFFER, flushing only after the transfer ends. This keeps RTS
; asserted (ESP drained) across the connection close, so ESP-AT never discards
; queued-but-unsent +IPD data on FIN. Must be < RECV_BUFFER_SIZE and safely
; larger than the largest tail ESP can drop in one close (~1-2 KB observed).
HOLD_TAIL_MARGIN	EQU 8192
URL_SIZE		EQU 160
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
PATH_SIZE		EQU 128
FILE_SIZE		EQU 80
; Maximum request is below 280 bytes even with every configured URL/host/port
; field populated and a 32-bit Range header. 304 keeps that margin while
; preserving the required WIN1 stack headroom after the shared UART setup.
REQ_SIZE		EQU 304
HEADER_LINE_SIZE	EQU 80
REDIRECT_LIMIT		EQU 5
RESUME_LIMIT		EQU 5
DSS_CREATE_OVERWRITE	EQU 0x0A
NO_HANDLE		EQU 0xFF
HTTP_UNSUPPORTED_NONE	EQU 0
HTTP_UNSUPPORTED_REDIRECT EQU 1
HTTP_UNSUPPORTED_HTTPS	EQU 2
HTTP_UNSUPPORTED_CHUNKED EQU 3
HTTP_UNSUPPORTED_GZIP	EQU 4

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	; Load this utility at 0x4100 so all code+BSS+stack live below
	; 0xC000, well clear of the ISA banking window. Long command lines
	; live at load_addr-0x80 = 0x4080.
LOAD_ADDR	EQU 0x4100
; Cmdline buffer pointer is taken from IX at entry (see START); load-#80
; (=0x4080) is the documented default but not assumed.
STACK_TOP	EQU 0x8000
WIN2_BASE	EQU 0x8000

	; Full 512-byte DSS EXE header.
	ORG LOAD_ADDR - 0x0200

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0200
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START			; load address (offset 16)
	DW START			; entry point  (offset 18)
	DW STACK_TOP
	DS 490, 0

	ORG LOAD_ADDR

START
	; DSS passes the command-line buffer pointer in IX at entry
	; ([IX+0]=length, [IX+1..]=text). Capture it first, before any CALL clobbers
	; IX, instead of assuming the load-#80 address. CMDLINE_PTR is a code-segment
	; var, so CLEAR_BSS (WIN2) does not wipe it.
	LD	(CMDLINE_PTR),IX
	CALL	INIT_RUNTIME_PAGE
	JP	C,INIT_MEMORY_ERROR
	CALL	CLEAR_BSS
	LD	A,NO_HANDLE
	LD	(OUT_FH),A
	XOR	A
	LD	(TCP_IS_OPEN),A

	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	PARSE_CMD_LINE
	JP	C,USAGE
	LD	A,(HELP_REQUESTED)
	AND	A
	JP	NZ,SHOW_HELP
	CALL	PARSE_URL
	JP	C,USAGE
	CALL	ENSURE_OUTPUT_FILE
	JP	C,USAGE
	CALL	SET_PORT_FLAG
	CALL	PRINT_SOURCE_INFO

	CALL	OPEN_OUTPUT_FILE
	JP	C,FILE_ERROR_EXIT

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI
	CALL	WCOMMON.REQUIRE_NET_UP

	CALL	WCOMMON.APPLY_NET_BAUD		; baud from env NET_BAUD (NETUP session); utilities never read NET.CFG
	CALL	WIFI.UART_INIT
	PRINTLN MSG_UART_READY

	LD	HL,CMD_AT
	CALL	SEND_CMD_RECOVER

	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD

	; NETUP owns the ESP UART configuration. Apply its published values only
	; to the local 16550 and verify that ESP remains in command mode.
	CALL	WCOMMON.SETUP_UART_FLOW
	AND	A
	JP	NZ,TCP_ERROR_EXIT

	; WGET is a single-connection client. Let any asynchronous link-close from
	; a preceding FTP/Telnet run settle before selecting CIPMUX=0.
	CALL	WCOMMON.CLEAN_ESP_LINKS
	LD	HL,MUX_RECOVERY_DELAY
	CALL	UTIL.DELAY
	LD	HL,CMD_CIPMUX_0
	CALL	SEND_CMD

	CALL	TPUT.START			; start the transfer timer
	; Remember the starting offset (resume-prompt seed, or 0) so the final
	; speed covers all bytes fetched THIS run across every fragment/redirect,
	; not just the last fragment.
	LD	HL,(TOTAL_BYTES)
	LD	(SESSION_BASE),HL
	LD	HL,(TOTAL_BYTES+2)
	LD	(SESSION_BASE+2),HL

.REQUEST_LOOP
	PRINT MSG_CONNECTING
	PRINT HOST_BUFF
	LD	A,(PORT_IS_DEFAULT)
	AND	A
	JR	NZ,.CONNECT_DEFAULT_PORT
	PRINT MSG_COLON
	PRINT PORT_BUFF
.CONNECT_DEFAULT_PORT
	PRINT WCOMMON.LINE_END
	LD	HL,HOST_BUFF
	LD	DE,PORT_BUFF
	CALL	OPEN_TCP_RECOVER
	JP	C,TCP_ERROR_EXIT
	LD	A,1
	LD	(TCP_IS_OPEN),A

	CALL	BUILD_HTTP_REQUEST
	LD	HL,REQ_BUFF
	CALL	UTIL.STRLEN
	; A fast server can start sending the HTTP response before ESP prints
	; SEND OK. Do not wait here: RECEIVE_HTTP scans past SEND OK text and
	; keeps the first +IPD payload instead of discarding it in WAIT_SEND_OK.
	CALL	TCP.SEND_BUFFER_NO_WAIT
	JP	C,TCP_ERROR_EXIT

	CALL	RECEIVE_HTTP
	PUSH	AF
	CALL	WIFI.UART_RX_RESUME
	POP	AF
	JR	NC,.RECEIVE_OK
	LD	A,(HTTP_INCOMPLETE)
	AND	A
	JP	Z,TCP_ERROR_EXIT
	CALL	PREPARE_RESUME_RETRY
	JP	C,TCP_ERROR_EXIT
	JR	.REQUEST_LOOP
.RECEIVE_OK

	; If RECEIVE_HTTP saw the remote close the connection, the ESP socket
	; is already gone. Skip CIPCLOSE — it would just sit waiting for an
	; OK/ERROR that the firmware may take a long time to deliver.
	LD	A,(SAW_CLOSED)
	AND	A
	JR	NZ,.SKIP_CLOSE
	LD	A,(LAST_TCP_ERR)
	CP	RES_NOT_CONN
	JR	Z,.SKIP_CLOSE
	CALL	TCP.CLOSE
.SKIP_CLOSE
	XOR	A
	LD	(TCP_IS_OPEN),A
	LD	A,(REDIRECT_PENDING)
	AND	A
	JR	Z,.REQUEST_DONE
	CALL	FOLLOW_REDIRECT
	JP	C,HTTP_ERROR_EXIT
	JR	.REQUEST_LOOP

.REQUEST_DONE
	CALL	CLOSE_OUTPUT_FILE
	JP	C,FILE_ERROR_EXIT

	PRINT WCOMMON.LINE_END
	CALL	PRINT_DOWNLOADED_BYTES
	; Report speed over ALL bytes fetched this run (TOTAL_BYTES - SESSION_BASE),
	; summed across every fragment/redirect, not just the last fragment.
	LD	HL,(TOTAL_BYTES)
	LD	DE,(SESSION_BASE)
	OR	A
	SBC	HL,DE			; HL = low16 of (TOTAL - base)
	EX	DE,HL			; DE = low16
	LD	HL,(TOTAL_BYTES+2)
	LD	BC,(SESSION_BASE+2)
	SBC	HL,BC			; HL = high16 (borrow chained)
	EX	DE,HL			; HL = low16, DE = high16
	CALL	TPUT.REPORT
	PRINTLN MSG_DONE
	LD	B,0
	JP	WCOMMON.EXIT

NO_WIFI
	CALL	CLOSE_OUTPUT_FILE
	PRINTLN MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

USAGE
	PRINTLN MSG_USAGE
	LD	B,1
	JP	WCOMMON.EXIT

SHOW_HELP
	PRINTLN MSG_USAGE
	LD	B,0
	JP	WCOMMON.EXIT

TCP_ERROR_EXIT
	; Save inbound error code BEFORE reading CANCELLED — otherwise A is
	; clobbered and every network error gets printed as #0.
	PUSH	AF
	LD	A,(WCOMMON.CANCELLED)
	AND	A
	JR	Z,.NOT_CANCELLED
	POP	AF
	JP	CANCEL_EXIT
.NOT_CANCELLED
	LD	A,(TCP_IS_OPEN)
	AND	A
	CALL	NZ,TCP.CLOSE
	CALL	CLOSE_OUTPUT_FILE
	POP	AF
	PUSH	AF
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_NET_ERROR
	POP	AF
	CALL	PRINT_NET_REASON		; plain-language hint for the RES_* code
	LD	B,3
	JP	WCOMMON.EXIT

; Print a human-readable explanation line for the RES_* network error code in A
; (esplib.asm), so "#3" is not the only thing a tester sees. Unknown/benign
; codes print nothing. Trashes A,HL,DE.
PRINT_NET_REASON
	CP	NET_REASON_COUNT
	RET	NC
	LD	L,A
	LD	H,0
	ADD	HL,HL				; code * 2 (word table)
	LD	DE,NET_REASON_TABLE
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	A,D
	OR	E				; null entry -> no extra line
	RET	Z
	EX	DE,HL
	PRINTLN_HL
	RET

FILE_ERROR_EXIT
	LD	A,(OUTPUT_ABORTED)
	AND	A
	JR	NZ,OUTPUT_ABORT_EXIT
	CALL	PRINT_FILE_ERROR
	LD	B,5
	JP	WCOMMON.EXIT

OUTPUT_ABORT_EXIT
	PRINTLN	MSG_ABORTED
	LD	B,1
	JP	WCOMMON.EXIT

HTTP_ERROR_EXIT
	LD	A,(TCP_IS_OPEN)
	AND	A
	CALL	NZ,TCP.CLOSE
	CALL	CLOSE_OUTPUT_FILE
	CALL	PRINT_HTTP_STATUS
	CALL	PRINT_HTTP_UNSUPPORTED
	LD	B,3
	JP	WCOMMON.EXIT

CANCEL_EXIT
	LD	A,(TCP_IS_OPEN)
	AND	A
	CALL	NZ,TCP.CLOSE
	CALL	CLOSE_OUTPUT_FILE
	PRINT	WCOMMON.LINE_END
	PRINTLN	MSG_CANCELLED
	LD	B,7
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Parse command line:
;   WGET.EXE url [-o output] [-y|-f overwrite] [-r resume]
;   WGET.EXE url FILE              ; legacy compatible alias for -o FILE
; ------------------------------------------------------
PARSE_CMD_LINE
	XOR	A
	LD	(HELP_REQUESTED),A
	LD	(FORCE_OVERWRITE),A
	LD	HL,(CMDLINE_PTR)
	LD	A,(HL)
	AND	A
	JP	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR

	PUSH	HL
	PUSH	BC
	CALL	IS_HELP_TOKEN_URL
	POP	BC
	POP	HL
	JR	NC,.HELP
.NEXT_OPT
	CALL	SKIP_SPACES
	JR	C,.DONE
	LD	DE,HOST_BUFF
	LD	C,FILE_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	PUSH	HL
	PUSH	BC
	CALL	IS_OPT_OUTPUT
	POP	BC
	POP	HL
	JR	NC,.OUTPUT
	PUSH	HL
	PUSH	BC
	CALL	IS_OPT_YES
	POP	BC
	POP	HL
	JR	NC,.YES
	PUSH	HL
	PUSH	BC
	CALL	IS_OPT_RESUME
	POP	BC
	POP	HL
	JR	NC,.RESUME_OPT
	PUSH	HL
	PUSH	BC
	CALL	IS_HELP_TOKEN_TMP
	POP	BC
	POP	HL
	JR	NC,.HELP
	LD	A,(OUT_FILE)
	AND	A
	JR	NZ,.ERR
	; COPY_ASCIIZ_LIMIT clobbers HL/BC, which still hold the cmdline cursor and
	; remaining-length. Preserve them so a flag after a positional output name
	; (e.g. `WGET url OUT -y`) is not read from garbage and lost.
	PUSH	HL
	PUSH	BC
	LD	HL,HOST_BUFF
	LD	DE,OUT_FILE
	LD	C,FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	POP	BC
	POP	HL
	JR	NC,.NEXT_OPT
	JR	.ERR
.OUTPUT
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,OUT_FILE
	LD	C,FILE_SIZE-1
	CALL	COPY_ARG
	JR	NC,.NEXT_OPT
	JR	.ERR
.YES
	LD	A,1
	LD	(FORCE_OVERWRITE),A
	JR	.NEXT_OPT
.RESUME_OPT
	LD	A,1
	LD	(FORCE_RESUME),A
	JR	.NEXT_OPT
.HELP
	LD	A,1
	LD	(HELP_REQUESTED),A
	RET
.DONE
	AND	A
	RET
.ERR
	SCF
	RET

IS_HELP_TOKEN_URL
	LD	DE,URL_BUFF
	JR	IS_HELP_TOKEN

IS_HELP_TOKEN_TMP
	LD	DE,HOST_BUFF
IS_HELP_TOKEN
	LD	HL,SWITCH_HELP_Q_SLASH
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_HELP_Q_DASH
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_HELP_H_SLASH
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_HELP_H_DASH
	JP	UTIL.STRCMP_CI

IS_OPT_OUTPUT
	LD	HL,SWITCH_OUTPUT_DASH
	LD	DE,HOST_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_OUTPUT_SLASH
	LD	DE,HOST_BUFF
	JP	UTIL.STRCMP_CI

; Overwrite flag: -y / /y, plus -f / /f as a clearer "force" alias.
IS_OPT_YES
	LD	HL,SWITCH_YES_DASH
	LD	DE,HOST_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_YES_SLASH
	LD	DE,HOST_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_FORCE_DASH
	LD	DE,HOST_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_FORCE_SLASH
	LD	DE,HOST_BUFF
	JP	UTIL.STRCMP_CI

; Resume flag: -r / /r (force append to an existing file, no prompt).
IS_OPT_RESUME
	LD	HL,SWITCH_RESUME_DASH
	LD	DE,HOST_BUFF
	CALL	UTIL.STRCMP_CI
	RET	NC
	LD	HL,SWITCH_RESUME_SLASH
	LD	DE,HOST_BUFF
	JP	UTIL.STRCMP_CI

SKIP_SPACES
	LD	A,B
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	XOR	A
	LD	(ARG_LEN),A
.NEXT
	LD	A,B
	AND	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	DEC	C
	LD	A,(ARG_LEN)
	INC	A
	LD	(ARG_LEN),A
	JR	.NEXT
.END
	XOR	A
	LD	(DE),A
	LD	A,(ARG_LEN)
	AND	A
	RET	NZ
.ERR
	SCF
	RET

; ------------------------------------------------------
; Parse URL_BUFF into HOST_BUFF, PORT_BUFF and PATH_BUFF.
; ------------------------------------------------------
PARSE_URL
	XOR	A
	LD	(URL_SCHEME_ADDED),A
	LD	HL,URL_BUFF
	LD	DE,HTTP_PREFIX
	CALL	UTIL.STARTSWITH
	JR	Z,.HAS_HTTP
	LD	A,1
	LD	(URL_SCHEME_ADDED),A
	LD	HL,URL_BUFF
	JR	.PARSE_HOST
.HAS_HTTP
	LD	BC,7
	ADD	HL,BC

.PARSE_HOST
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
.HOST
	LD	A,(HL)
	AND	A
	JR	Z,.HOST_DONE
	CP	'/'
	JR	Z,.HOST_DONE
	CP	':'
	JR	Z,.PORT_START
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	C
	JR	.HOST

.HOST_DONE
	XOR	A
	LD	(DE),A
	LD	A,(HOST_BUFF)
	AND	A
	JR	Z,.ERR
	PUSH	HL
	LD	DE,DEFAULT_PORT
	CALL	COPY_PORT_DEFAULT
	POP	HL
	JR	.PATH_START

.PORT_START
	XOR	A
	LD	(DE),A
	INC	HL
	LD	DE,PORT_BUFF
	LD	C,PORT_SIZE-1
.PORT
	LD	A,(HL)
	AND	A
	JR	Z,.PORT_DONE
	CP	'/'
	JR	Z,.PORT_DONE
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	C
	JR	.PORT
.PORT_DONE
	XOR	A
	LD	(DE),A
	LD	A,(PORT_BUFF)
	AND	A
	JR	Z,.ERR

.PATH_START
	LD	A,(HL)
	CP	'/'
	JR	Z,.COPY_PATH
	LD	HL,DEFAULT_PATH
	LD	DE,PATH_BUFF
	JP	COPY_ASCIIZ_DE

.COPY_PATH
	LD	DE,PATH_BUFF
	LD	C,PATH_SIZE-1
.PATH
	LD	A,(HL)
	AND	A
	JR	Z,.PATH_DONE
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	C
	JR	.PATH
.PATH_DONE
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET

COPY_PORT_DEFAULT
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	JP	COPY_ASCIIZ_DE

COPY_ASCIIZ_DE
	LD	A,(HL)
	LD	(DE),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ_DE

COPY_ASCIIZ_LIMIT
	LD	A,(HL)
	AND	A
	JR	Z,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	COPY_ASCIIZ_LIMIT
.END
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET

ENSURE_OUTPUT_FILE
	LD	A,(OUT_FILE)
	AND	A
	RET	NZ
	LD	IX,PATH_BUFF
	LD	HL,PATH_BUFF
.SCAN
	LD	A,(HL)
	AND	A
	JR	Z,.FOUND
	CP	'/'
	JR	Z,.SLASH
	CP	'\'
	JR	Z,.SLASH
	INC	HL
	JR	.SCAN
.SLASH
	INC	HL
	PUSH	HL
	POP	IX
	JR	.SCAN
.FOUND
	LD	A,(IX+0)
	AND	A
	JR	Z,.DEFAULT
	PUSH	IX
	POP	HL
	LD	DE,OUT_FILE
	LD	C,FILE_SIZE-1
	JP	COPY_ASCIIZ_LIMIT
.DEFAULT
	LD	HL,DEFAULT_OUT_FILE
	LD	DE,OUT_FILE
	LD	C,FILE_SIZE-1
	JP	COPY_ASCIIZ_LIMIT

; ------------------------------------------------------
; Print source URL details after parsing.
; ------------------------------------------------------
PRINT_SOURCE_INFO
	PRINT	MSG_SOURCE
	PRINT	URL_BUFF
	PRINT	WCOMMON.LINE_END
	LD	A,(URL_SCHEME_ADDED)
	AND	A
	JR	Z,.NO_WARN
	PRINTLN	MSG_SCHEME_ADDED
.NO_WARN
	RET

; ------------------------------------------------------
; Clear runtime-only buffers placed after the loaded EXE image.
; ------------------------------------------------------
INIT_RUNTIME_PAGE
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	RET	C
	LD	B,0
	LD	C,DSS_SETWIN2
	RST	DSS
	RET

INIT_MEMORY_ERROR
	LD	B,3
	LD	C,DSS_EXIT
	RST	DSS

CLEAR_BSS
	LD	HL,WGET_BSS_BASE
	LD	DE,WGET_BSS_BASE+1
	LD	BC,WGET_BSS_END-WGET_BSS_BASE-1
	LD	(HL),0
	LDIR
	RET

; ------------------------------------------------------
; Local output file helpers.
; ------------------------------------------------------
OPEN_OUTPUT_FILE
	PRINT MSG_OUTPUT
	PRINT OUT_FILE
	PRINT WCOMMON.LINE_END
	LD	HL,OUT_FILE
	LD	A,FA_READONLY
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.CREATE			; does not exist -> fresh download
	LD	C,DSS_CLOSE_FILE
	RST	DSS				; close the existence-test handle
	LD	A,(FORCE_OVERWRITE)
	AND	A
	JR	NZ,.DELETE			; -y/-f forces overwrite
	LD	A,(FORCE_RESUME)
	AND	A
	JR	NZ,.RESUME			; -r forces resume (append)
	CALL	CONFIRM_EXISTING		; A = 'R' resume / 'O' overwrite / 'C' cancel
	CP	'R'
	JR	Z,.RESUME
	CP	'O'
	JR	Z,.DELETE
	JR	.ABORT				; cancel
.RESUME
	; Reopen the existing file read/write and seek to its end so the new bytes
	; append; seed TOTAL_BYTES with the current size so BUILD_HTTP_REQUEST asks
	; for "Range: bytes=<size>-" and the server resumes from there.
	LD	HL,OUT_FILE
	LD	A,0				; FileMode RW
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.CREATE			; cannot reopen -> fall back to fresh
	LD	(OUT_FH),A
	LD	A,(OUT_FH)
	LD	B,SEEK_END
	LD	HL,0
	LD	IX,0
	LD	C,DSS_MOVE_FP
	RST	DSS				; HL:IX = size (HL high, IX low)
	LD	(TOTAL_BYTES),IX
	LD	(TOTAL_BYTES+2),HL
	XOR	A
	LD	(OUTPUT_ABORTED),A
	PRINT	MSG_RESUME_AT
	LD	HL,TOTAL_BYTES
	CALL	PRINT_U32_AT_HL
	PRINTLN	MSG_BYTES
	RET
.DELETE
	LD	HL,OUT_FILE
	LD	C,DSS_DELETE
	RST	DSS
.CREATE
	LD	HL,OUT_FILE
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	RET	C
	LD	(OUT_FH),A
	XOR	A
	LD	(OUTPUT_ABORTED),A
	RET
.ABORT
	LD	A,1
	LD	(OUTPUT_ABORTED),A
	SCF
	RET

; Ask what to do about an existing output file. Returns A = 'R' (resume),
; 'O' (overwrite) or 'C' (cancel). Y=overwrite, N/Esc=cancel for familiarity.
CONFIRM_EXISTING
	PRINT	MSG_OVERWRITE_PRE
	PRINT	OUT_FILE
	PRINT	MSG_OVERWRITE_POST
.ASK
	; Drop the Enter that launched the command (and any other stale keys)
	; so WAITKEY blocks for a fresh choice instead of consuming the leftover.
	LD	C,DSS_KCLEAR
	RST	DSS
	LD	C,DSS_WAITKEY
	RST	DSS
	PUSH	AF
	LD	C,DSS_PUTCHAR
	RST	DSS
	LD	A,13
	LD	C,DSS_PUTCHAR
	RST	DSS
	LD	A,10
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	AF
	CP	'R'
	JR	Z,.RES
	CP	'r'
	JR	Z,.RES
	CP	'O'
	JR	Z,.OVR
	CP	'o'
	JR	Z,.OVR
	CP	'Y'
	JR	Z,.OVR
	CP	'y'
	JR	Z,.OVR
	CP	'C'
	JR	Z,.CAN
	CP	'c'
	JR	Z,.CAN
	CP	'N'
	JR	Z,.CAN
	CP	'n'
	JR	Z,.CAN
	CP	0x1B				; Esc
	JR	Z,.CAN
	JR	.ASK				; unrecognised -> ask again
.RES
	LD	A,'R'
	RET
.OVR
	LD	A,'O'
	RET
.CAN
	LD	A,'C'
	RET

CLOSE_OUTPUT_FILE
	LD	A,(OUT_FH)
	CP	NO_HANDLE
	RET	Z
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,NO_HANDLE
	LD	(OUT_FH),A
	RET

WRITE_OUTPUT
	LD	A,B
	OR	C
	RET	Z
	LD	A,(OUT_FH)
	LD	D,B
	LD	E,C
	LD	C,DSS_WRITE
	RST	DSS
	RET

PRINT_FILE_ERROR
	PRINT	MSG_FILE_ERROR
	CALL	DSS_ERROR.GET_ERR_MSG
	PRINTLN_HL
	RET

; ------------------------------------------------------
; ESP/TCP command helpers.
; ------------------------------------------------------
SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	RET	Z
	JP	TCP_ERROR_EXIT

SEND_CMD_RECOVER
	PUSH	HL
	CALL	WCOMMON.SYNC_ESP_COMMAND
	POP	HL
	JP	SEND_CMD

PREPARE_TCP_OPEN
	CALL	WIFI.UART_RX_RESUME
	; Normalize both mux variants, not just a stale single connection. This
	; matters after FTP, which runs CIPMUX=1 and may leave a late CLOSED event.
	CALL	WCOMMON.CLEAN_ESP_LINKS
	XOR	A
	LD	(TCP_IS_OPEN),A
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	XOR	A
	LD	(TCP.LSR_ACCUM),A
	CALL	WIFI.UART_EMPTY_RS
	LD	HL,CMD_AT
	CALL	SEND_CMD
	LD	HL,CMD_CIPMUX_0
	JP	SEND_CMD

OPEN_TCP_RECOVER
	PUSH	HL
	PUSH	DE
	CALL	PREPARE_TCP_OPEN
	POP	DE
	POP	HL
	RET	C
	CALL	TCP.OPEN
	RET	NC
	PUSH	AF
	CALL	WIFI.UART_RX_RESUME
	CALL	TCP.CLOSE
	XOR	A
	LD	(TCP_IS_OPEN),A
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	XOR	A
	LD	(TCP.LSR_ACCUM),A
	CALL	WIFI.UART_EMPTY_RS
	LD	HL,TCP_OPEN_RETRY_DELAY
	CALL	UTIL.DELAY
	CALL	PREPARE_TCP_OPEN
	POP	AF
	LD	HL,HOST_BUFF
	LD	DE,PORT_BUFF
	JP	TCP.OPEN

; ------------------------------------------------------
; Build HTTP/1.0 GET request in REQ_BUFF.
; ------------------------------------------------------
BUILD_HTTP_REQUEST
	CALL	SET_PORT_FLAG
	LD	HL,REQ_BUFF
	XOR	A
	LD	(RANGE_ACTIVE),A
	LD	DE,REQ_GET
	CALL	APPEND_STR
	LD	IX,PATH_BUFF
	CALL	APPEND_IX_STR
	LD	DE,REQ_HTTP
	CALL	APPEND_STR
	LD	IX,HOST_BUFF
	CALL	APPEND_IX_STR
	LD	A,(PORT_IS_DEFAULT)
	AND	A
	JR	NZ,.NO_HOST_PORT
	LD	DE,REQ_PORT_SEP
	CALL	APPEND_STR
	LD	IX,PORT_BUFF
	CALL	APPEND_IX_STR
.NO_HOST_PORT
	CALL	APPEND_RANGE_HEADER_IF_NEEDED
	LD	DE,REQ_END
	JP	APPEND_STR

APPEND_RANGE_HEADER_IF_NEEDED
	CALL	TOTAL_BYTES_IS_ZERO
	RET	Z
	LD	A,1
	LD	(RANGE_ACTIVE),A
	LD	DE,REQ_RANGE
	CALL	APPEND_STR
	LD	DE,TOTAL_BYTES
	CALL	APPEND_U32_FROM_DE
	LD	DE,REQ_RANGE_END
	JP	APPEND_STR

; ------------------------------------------------------
; Set PORT_IS_DEFAULT=1 when port is "80", otherwise 0.
; ------------------------------------------------------
SET_PORT_FLAG
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	CALL	UTIL.STRCMP
	JR	C,.CUSTOM
	LD	A,1
	LD	(PORT_IS_DEFAULT),A
	RET
.CUSTOM
	XOR	A
	LD	(PORT_IS_DEFAULT),A
	RET

; ------------------------------------------------------
; Receive HTTP response, skip headers and write body to file.
; ------------------------------------------------------
RECEIVE_HTTP
	XOR	A
	LD	(GOT_RESPONSE),A
	LD	(HEADER_DONE),A
	LD	(HDR_STATE),A
	LD	(HAVE_BODY),A
	LD	(HTTP_STATUS_PTR),A
	LD	(HTTP_STATUS_PTR+1),A
	LD	(ADJUST_RESPONSE),A
	LD	(CONTENT_LENGTH),A
	LD	(CONTENT_LENGTH+1),A
	LD	(CONTENT_LENGTH+2),A
	LD	(CONTENT_LENGTH+3),A
	LD	(CONTENT_LENGTH_SEEN),A
	LD	(BODY_BYTES),A
	LD	(BODY_BYTES+1),A
	LD	(BODY_BYTES+2),A
	LD	(BODY_BYTES+3),A
	LD	(HTTP_INCOMPLETE),A
	LD	(BODY_LOG_PRINTED),A
	LD	(DEBUG_PRINTED),A
	LD	(HEADER_LINE_LEN),A
	LD	(SAW_CLOSED),A
	LD	(HTTP_STATUS_CLASS),A
	LD	(REDIRECT_PENDING),A
	LD	(LOCATION_SEEN),A
	LD	(HTTP_UNSUPPORTED_REASON),A
	LD	(HOLD_MODE),A
	LD	(HOLD_LEN),A
	LD	(HOLD_LEN+1),A

.LOOP
	CALL	WCOMMON.CHECK_CANCEL
	JP	C,.CANCELLED
		CALL	WIFI.UART_RX_RESUME
		; Switch to retain-tail mode before the read once the body is within
		; HOLD_TAIL_MARGIN of completion; SETUP_RECV_DEST then accumulates into
		; RECV_BUFFER at a growing offset instead of overwriting from the start.
		CALL	UPDATE_HOLD_MODE
		CALL	SETUP_RECV_DEST
		LD	A,(SAW_CLOSED)
		AND	A
		JR	NZ,.AFTER_CLOSE_TIMEOUT
		LD	DE,RECV_TIMEOUT
		JR	.RECV
.AFTER_CLOSE_TIMEOUT
		LD	DE,CLOSED_DRAIN_TIMEOUT
.RECV
		LD	HL,(RECV_DEST)
		LD	BC,(RECV_CAP)
		CALL	TCP.RECEIVE
	; Pause RX immediately so ESP stops sending while we run the (slow)
	; HTTP parser, debug print, file write etc. Resumed at .LOOP top.
	PUSH	AF,BC
	CALL	WIFI.UART_RX_PAUSE
	CALL	STORE_RECV_DEBUG
	POP	BC,AF
	JP	C,.RX_ERROR
	CALL	UART_RX_ERROR_SEEN
	JP	NZ,.RX_UART_ERROR
	LD	A,B
	OR	C
	JR	Z,.RX_DONE
	CALL	TRIM_CLOSED_SUFFIX
	LD	A,B
	OR	C
	JR	Z,.RX_DONE

	PUSH	BC
	LD	A,(GOT_RESPONSE)
	AND	A
	JR	NZ,.STATUS_DONE
	LD	A,1
	LD	(GOT_RESPONSE),A
	LD	HL,RECV_BUFFER
	CALL	CHECK_HTTP_STATUS
	JR	C,.HTTP_ERR_POP
	LD	A,1
	LD	(ADJUST_RESPONSE),A
.STATUS_DONE
	POP	BC
	LD	A,(ADJUST_RESPONSE)
	AND	A
	JR	Z,.PROCESS_FROM_START
	XOR	A
	LD	(ADJUST_RESPONSE),A
	CALL	ADJUST_TO_HTTP_STATUS
	JR	.PROCESS_DATA
.PROCESS_FROM_START
	LD	HL,(RECV_DEST)
.PROCESS_DATA
		CALL	PROCESS_HTTP_DATA
		JR	C,.PROCESS_ERR
		; Finish as soon as the whole announced body is in, without waiting for
		; the server to close. Required for keep-alive (no CLOSED arrives) and a
		; useful speedup otherwise.
		CALL	BODY_IS_COMPLETE
		JP	Z,.RX_DONE
		LD	A,(SAW_CLOSED)
		AND	A
		JP	Z,.LOOP
		CALL	SHOULD_FINISH_AFTER_CLOSED
		JR	Z,.RX_DONE
		JP	.LOOP

.PROCESS_ERR
	CALL	WIFI.UART_RX_RESUME
	LD	A,(HTTP_UNSUPPORTED_REASON)
	AND	A
	JP	NZ,HTTP_ERROR_EXIT
	JR	.ERR

.HTTP_ERR_POP
	POP	BC
	CALL	WIFI.UART_RX_RESUME
	JP	HTTP_ERROR_EXIT

.RX_DONE
	LD	A,(REDIRECT_PENDING)
	AND	A
	JR	NZ,.REDIRECT_DONE
	XOR	A
	LD	(LAST_TCP_ERR),A
.RX_ERROR_DONE
	LD	A,(HAVE_BODY)
	AND	A
	JR	Z,.NO_BODY
	CALL	FLUSH_HOLD
	JP	C,FILE_ERROR_EXIT
	JP	CHECK_CONTENT_LENGTH
.RX_ERROR
	LD	(LAST_TCP_ERR),A
	CP	RES_NOT_CONN
	JR	NZ,.RX_ERROR_NOT_CLOSED
	LD	A,1
	LD	(SAW_CLOSED),A
.RX_ERROR_NOT_CLOSED
		PRINT	WCOMMON.LINE_END
		CALL	PRINT_RECV_DEBUG
		CALL	PRINT_UART_OVERRUN_HINT
		LD	A,1
		LD	(DEBUG_PRINTED),A
		LD	A,(LAST_TCP_ERR)
		CP	RES_NOT_CONN
		JR	NZ,.RX_ERROR_DONE
		CALL	SHOULD_FINISH_AFTER_CLOSED
		JP	NZ,.LOOP
		JR	.RX_ERROR_DONE
.RX_UART_ERROR
	LD	A,RES_RS_TIMEOUT
	JR	.RX_ERROR
.NO_BODY
	LD	A,(GOT_RESPONSE)
	AND	A
	JR	Z,.NO_RESPONSE
	PRINTLN MSG_NO_BODY
	JR	.NO_BODY_ERR
.NO_RESPONSE
	PRINTLN MSG_NO_RESPONSE
.NO_BODY_ERR
	LD	A,(LAST_TCP_ERR)
	AND	A
	JR	NZ,.ERR
	LD	A,RES_RS_TIMEOUT
.ERR
	SCF
	RET
.REDIRECT_DONE
	XOR	A
	RET
.CANCELLED
	JP	CANCEL_EXIT

CHECK_HTTP_STATUS
	LD	A,B
	OR	C
	JR	Z,.ERR

.FIND_STATUS
	LD	A,B
	OR	A
	JR	NZ,.ENOUGH_BYTES
	LD	A,C
	CP	5
	JR	C,.ERR
.ENOUGH_BYTES
	CALL	MATCH_HTTP_PREFIX
	JR	Z,.FOUND
	INC	HL
	DEC	BC
	JR	.FIND_STATUS

.FOUND
	LD	(HTTP_STATUS_PTR),HL
	CALL	HTTP_STATUS_ACCEPTED
	RET	NC
.ERR
	SCF
	RET

MATCH_HTTP_PREFIX
	PUSH	HL,DE,BC
	LD	DE,HTTP_STATUS_PREFIX
	LD	B,5
.NEXT
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.NO_MATCH
	INC	DE
	INC	HL
	DJNZ	.NEXT
	XOR	A
	POP	BC,DE,HL
	RET
.NO_MATCH
	LD	A,1
	OR	A
	POP	BC,DE,HL
	RET

HTTP_STATUS_ACCEPTED
	LD	B,16
.FIND_SPACE
	LD	A,(HL)
	CP	' '
	JR	Z,.SKIP_SPACES
	CP	13
	JR	Z,.ERR
	CP	10
	JR	Z,.ERR
	AND	A
	JR	Z,.ERR
	INC	HL
	DJNZ	.FIND_SPACE
	JR	.ERR
.SKIP_SPACES
	INC	HL
	LD	A,(HL)
	CP	' '
	JR	Z,.SKIP_SPACES
	LD	(HTTP_STATUS_CLASS),A
	LD	A,(RANGE_ACTIVE)
	AND	A
	JR	Z,.ACCEPT_CLASS
	LD	A,(HL)
	CP	'2'
	JR	NZ,.ERR
	INC	HL
	LD	A,(HL)
	CP	'0'
	JR	NZ,.ERR
	INC	HL
	LD	A,(HL)
	CP	'6'
	JR	NZ,.ERR
	XOR	A
	RET
.ACCEPT_CLASS
	LD	A,(HTTP_STATUS_CLASS)
	CP	'2'
	RET	Z
	CP	'3'
	RET	Z
.ERR
	SCF
	RET

ADJUST_TO_HTTP_STATUS
	LD	DE,(HTTP_STATUS_PTR)
	PUSH	DE
	LD	HL,RECV_BUFFER
	ADD	HL,BC
	POP	DE
	AND	A
	SBC	HL,DE
	LD	B,H
	LD	C,L
	EX	DE,HL
	RET

PROCESS_HTTP_DATA
	LD	A,(HEADER_DONE)
	AND	A
	JR	Z,.SCAN_HEADER
	CALL	CHECK_REDIRECT_HEADER
	RET	C
	LD	A,(REDIRECT_PENDING)
	AND	A
	RET	NZ
	CALL	CHECK_UNSUPPORTED_HTTP
	RET	C
	JP	WRITE_BODY

.SCAN_HEADER
	LD	A,B
	OR	C
	RET	Z
	LD	A,(HL)
	INC	HL
	DEC	BC
	PUSH	AF
	CALL	CAPTURE_HEADER_CHAR
	POP	AF
	CALL	UPDATE_HEADER_STATE
	LD	A,(HEADER_DONE)
	AND	A
	JR	Z,.SCAN_HEADER
	CALL	CHECK_REDIRECT_HEADER
	RET	C
	LD	A,(REDIRECT_PENDING)
	AND	A
	RET	NZ
	CALL	CHECK_UNSUPPORTED_HTTP
	RET	C
	JP	WRITE_BODY

CAPTURE_HEADER_CHAR
	PUSH	BC,DE,HL
	LD	E,A
	CP	13
	JR	Z,.DONE
	CP	10
	JR	Z,.LINE_DONE
	LD	A,(HEADER_LINE_LEN)
	CP	HEADER_LINE_SIZE-1
	JR	NC,.DONE
	LD	C,A
	LD	B,0
	LD	HL,HEADER_LINE
	ADD	HL,BC
	LD	(HL),E
	INC	A
	LD	(HEADER_LINE_LEN),A
	JR	.DONE
.LINE_DONE
	LD	A,(HEADER_LINE_LEN)
	LD	C,A
	LD	B,0
	LD	HL,HEADER_LINE
	ADD	HL,BC
	LD	(HL),0
	CALL	PARSE_HEADER_LINE
	XOR	A
	LD	(HEADER_LINE_LEN),A
.DONE
	POP	HL,DE,BC
	RET

PARSE_HEADER_LINE
	LD	HL,HEADER_LINE
	LD	DE,CONTENT_LENGTH_PREFIX
	CALL	MATCH_HEADER_PREFIX
	JR	NZ,.TRY_TRANSFER_ENCODING
.FOUND
	CALL	SKIP_HEADER_SPACES
	LD	A,(HL)
	CP	'0'
	RET	C
	CP	'9'+1
	RET	NC
	CALL	PARSE_CONTENT_LENGTH_U32
	LD	A,1
	LD	(CONTENT_LENGTH_SEEN),A
	RET

.TRY_TRANSFER_ENCODING
	LD	HL,HEADER_LINE
	LD	DE,TRANSFER_ENCODING_PREFIX
	CALL	MATCH_HEADER_PREFIX
	JR	NZ,.TRY_CONTENT_ENCODING
	CALL	SKIP_HEADER_SPACES
	LD	DE,CHUNKED_VALUE
	CALL	MATCH_TOKEN_CI
	RET	NZ
	LD	A,HTTP_UNSUPPORTED_CHUNKED
	LD	(HTTP_UNSUPPORTED_REASON),A
	RET

.TRY_CONTENT_ENCODING
	LD	HL,HEADER_LINE
	LD	DE,CONTENT_ENCODING_PREFIX
	CALL	MATCH_HEADER_PREFIX
	JR	NZ,.TRY_LOCATION
	CALL	SKIP_HEADER_SPACES
	LD	DE,GZIP_VALUE
	CALL	MATCH_TOKEN_CI
	RET	NZ
	LD	A,HTTP_UNSUPPORTED_GZIP
	LD	(HTTP_UNSUPPORTED_REASON),A
	RET

.TRY_LOCATION
	LD	HL,HEADER_LINE
	LD	DE,LOCATION_PREFIX
	CALL	MATCH_HEADER_PREFIX
	RET	NZ
.LOC_FOUND
	CALL	SKIP_HEADER_SPACES
	LD	DE,LOCATION_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_HEADER_VALUE
	LD	A,1
	LD	(LOCATION_SEEN),A
	RET

MATCH_HEADER_PREFIX
	LD	A,(DE)
	AND	A
	RET	Z
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	JR	MATCH_HEADER_PREFIX

MATCH_TOKEN_CI
	LD	A,(DE)
	AND	A
	RET	Z
	LD	C,A
	LD	A,(HL)
	CALL	ASCII_TO_LOWER
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	JR	MATCH_TOKEN_CI

ASCII_TO_LOWER
	CP	'A'
	RET	C
	CP	'Z'+1
	RET	NC
	ADD	A,32
	RET

SKIP_HEADER_SPACES
	LD	A,(HL)
	CP	' '
	JR	Z,.NEXT
	CP	9
	RET	NZ
.NEXT
	INC	HL
	JR	SKIP_HEADER_SPACES

COPY_HEADER_VALUE
	LD	A,(HL)
	AND	A
	JR	Z,.DONE
	LD	A,C
	AND	A
	JR	Z,.DONE
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	COPY_HEADER_VALUE
.DONE
	XOR	A
	LD	(DE),A
	RET

CHECK_UNSUPPORTED_HTTP
	LD	A,(HTTP_UNSUPPORTED_REASON)
	AND	A
	RET	Z
	SCF
	RET

CHECK_REDIRECT_HEADER
	LD	A,(HTTP_STATUS_CLASS)
	CP	'3'
	JR	Z,.REDIRECT
	XOR	A
	RET
.REDIRECT
	LD	A,(LOCATION_SEEN)
	AND	A
	JR	Z,.ERR
	LD	A,1
	LD	(REDIRECT_PENDING),A
	XOR	A
	RET
.ERR
	LD	A,HTTP_UNSUPPORTED_REDIRECT
	LD	(HTTP_UNSUPPORTED_REASON),A
	LD	A,RES_ERROR
	SCF
	RET

FOLLOW_REDIRECT
	LD	A,(REDIRECT_COUNT)
	CP	REDIRECT_LIMIT
	JR	NC,.ERR
	INC	A
	LD	(REDIRECT_COUNT),A

	PRINT	MSG_REDIRECT
	PRINT	LOCATION_BUFF
	PRINT	WCOMMON.LINE_END

	LD	HL,LOCATION_BUFF
	LD	DE,HTTP_PREFIX
	CALL	UTIL.STARTSWITH
	JR	Z,.HTTP

	LD	HL,LOCATION_BUFF
	LD	DE,HTTPS_PREFIX
	CALL	UTIL.STARTSWITH
	JR	Z,.HTTPS

	LD	A,HTTP_UNSUPPORTED_REDIRECT
	LD	(HTTP_UNSUPPORTED_REASON),A
	JR	.ERR

.HTTP
	LD	HL,LOCATION_BUFF
	LD	DE,URL_BUFF
	CALL	COPY_ASCIIZ_DE
	CALL	PARSE_URL
	JR	C,.ERR
	CALL	SET_PORT_FLAG
	XOR	A
	RET

.HTTPS
	LD	A,HTTP_UNSUPPORTED_HTTPS
	LD	(HTTP_UNSUPPORTED_REASON),A
.ERR
	LD	A,RES_ERROR
	SCF
	RET

; ------------------------------------------------------
; Remove ESP-AT connection-close notification from the end of a receive block.
; Some ESP/jesperl streams append CLOSED after TCP payload bytes. It is not
; HTTP body and must never be written to the output file.
;
; Guard: only attempt the trim when we are past HTTP headers AND a
; Content-Length is known AND BODY_BYTES + BC strictly exceeds
; Content-Length. Without that, an HTTP body that legitimately ends with
; "CLOSED" plus CR/LF (text payload, log file, etc.) would be silently
; truncated. With the guard we only ever trim bytes that already overflow
; the announced body size.
; In/Out: BC - received byte count.
; ------------------------------------------------------
TRIM_CLOSED_SUFFIX
	LD	(TRIM_ORIG_LEN),BC
	LD	(TRIM_CAND_LEN),BC
	LD	A,(HEADER_DONE)
	AND	A
	JR	Z,.NO_MATCH
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	JR	Z,.NO_MATCH
	CALL	BODY_PLUS_BC_OVER_CL
	JR	NC,.NO_MATCH
	LD	HL,(RECV_DEST)
	ADD	HL,BC
.SKIP_TAIL_CRLF
	LD	BC,(TRIM_CAND_LEN)
	LD	A,B
	OR	C
	JR	Z,.NO_MATCH
	DEC	HL
	LD	A,(HL)
	CP	13
	JR	Z,.DROP_TAIL
	CP	10
	JR	Z,.DROP_TAIL
	INC	HL
	JR	.CHECK_CLOSED
.DROP_TAIL
	DEC	BC
	LD	(TRIM_CAND_LEN),BC
	JR	.SKIP_TAIL_CRLF
.CHECK_CLOSED
	LD	BC,(TRIM_CAND_LEN)
	LD	A,B
	AND	A
	JR	NZ,.HAVE_ENOUGH
	LD	A,C
	CP	6
	JR	C,.NO_MATCH
.HAVE_ENOUGH
	PUSH	HL
	LD	DE,6
	AND	A
	SBC	HL,DE
	LD	DE,CLOSED_WORD
	LD	B,6
.MATCH
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.RESTORE_NO_MATCH
	INC	DE
	INC	HL
	DJNZ	.MATCH
	POP	HL
	LD	HL,(TRIM_CAND_LEN)
	LD	DE,6
	AND	A
	SBC	HL,DE
	LD	B,H
	LD	C,L
	LD	A,1
	LD	(SAW_CLOSED),A
	RET
.RESTORE_NO_MATCH
	POP	HL
.NO_MATCH
	LD	BC,(TRIM_ORIG_LEN)
	RET

; ------------------------------------------------------
; CF=1 iff (BODY_BYTES + BC) > CONTENT_LENGTH (32-bit unsigned, strict).
; Preserves BC. Trashes A, DE, HL.
; ------------------------------------------------------
BODY_PLUS_BC_OVER_CL
	PUSH	BC
	LD	HL,(BODY_BYTES)
	ADD	HL,BC
	LD	(TRIM_TMP),HL
	LD	HL,(BODY_BYTES+2)
	JR	NC,.NO_CARRY
	INC	HL
.NO_CARRY
	LD	(TRIM_TMP+2),HL

	; Compare 32-bit TRIM_TMP > CONTENT_LENGTH; high words first.
	LD	HL,(CONTENT_LENGTH+2)
	LD	DE,(TRIM_TMP+2)
	OR	A
	SBC	HL,DE
	JR	C,.OVER				; CL_hi < TMP_hi -> over
	JR	NZ,.NOT_OVER			; CL_hi > TMP_hi -> not over
	; equal high words; compare low
	LD	HL,(CONTENT_LENGTH)
	LD	DE,(TRIM_TMP)
	OR	A
	SBC	HL,DE
	JR	C,.OVER				; CL_lo < TMP_lo -> over
	; CL_lo >= TMP_lo (including equal) -> not strictly over
.NOT_OVER
	POP	BC
	AND	A
	RET
.OVER
	POP	BC
	SCF
	RET

UPDATE_HEADER_STATE
	LD	E,A
	LD	A,(HDR_STATE)
	AND	A
	JR	Z,.STATE0
	CP	1
	JR	Z,.STATE1
	CP	2
	JR	Z,.STATE2

; State 3: CR LF CR seen, waiting for LF.
.STATE3
	LD	A,E
	CP	10
	JR	Z,.DONE
	CP	13
	JR	Z,.SET3
	XOR	A
	JR	.STORE
.STATE0
	LD	A,E
	CP	13
	JR	Z,.SET1
	XOR	A
	JR	.STORE
.STATE1
	LD	A,E
	CP	10
	JR	Z,.SET2
	CP	13
	JR	Z,.SET1
	XOR	A
	JR	.STORE
.STATE2
	LD	A,E
	CP	13
	JR	Z,.SET3
	XOR	A
	JR	.STORE
.SET1
	LD	A,1
	JR	.STORE
.SET2
	LD	A,2
	JR	.STORE
.SET3
	LD	A,3
	JR	.STORE
.DONE
	LD	A,1
	LD	(HEADER_DONE),A
	RET
.STORE
	LD	(HDR_STATE),A
	RET

WRITE_BODY
	; RX is already paused by RECEIVE_HTTP main loop; resume happens at .LOOP top.
	LD	A,B
	OR	C
	RET	Z
	LD	A,(BODY_LOG_PRINTED)
	AND	A
	JR	NZ,.LOG_DONE
	PUSH	HL
	PUSH	BC
	CALL	Z,PRINT_BODY_LOG_HEADER
	POP	BC
	POP	HL
.LOG_DONE
	LD	A,(HOLD_MODE)
	AND	A
	JR	NZ,.HOLD
	; Safe zone: still more than HOLD_TAIL_MARGIN bytes to come (and reads are
	; capped to stop exactly at that boundary), so a DSS_WRITE pause here can
	; never coincide with the connection close.
	PUSH	BC
	CALL	WRITE_OUTPUT
	POP	BC
	RET	C
	CALL	ADD_BODY_BYTES
	LD	HL,BODY_BYTES
	LD	DE,CONTENT_LENGTH
	CALL	TPUT.PROGRESS
	LD	A,1
	LD	(HAVE_BODY),A
	RET
.HOLD
	; Retain-tail: do NOT write to disk. Hold mode is entered at the loop top
	; before the read, so RECEIVE already placed these bytes contiguously at
	; RECV_BUFFER+HOLD_LEN (HL == RECV_DEST). They are flushed once the
	; transfer completes (FLUSH_HOLD). With no write pause RTS stays asserted,
	; so ESP delivers every +IPD before CLOSED and drops nothing.
	LD	HL,(HOLD_LEN)
	ADD	HL,BC
	LD	(HOLD_LEN),HL
	CALL	ADD_BODY_BYTES
	LD	HL,BODY_BYTES
	LD	DE,CONTENT_LENGTH
	CALL	TPUT.PROGRESS
	LD	A,1
	LD	(HAVE_BODY),A
	RET

; ------------------------------------------------------
; Enter retain-tail (hold) mode once the announced body has at most
; HOLD_TAIL_MARGIN bytes left to receive. Called at the loop top BEFORE the
; read so the final bytes are accumulated, never written under an RTS-off
; pause. Latches HOLD_MODE; never clears it mid-transfer. No-op without a
; known Content-Length.
; ------------------------------------------------------
UPDATE_HOLD_MODE
	LD	A,(HOLD_MODE)
	AND	A
	RET	NZ
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	RET	Z
	CALL	BODY_REMAINING			; HL=low, A=0 and Z if <65536 & not negative
	RET	NZ				; remaining >= 65536 or CL < BODY -> not yet
	LD	A,H
	OR	L
	RET	Z				; remaining 0 -> done, no need to hold
	EX	DE,HL				; DE = remaining
	LD	HL,HOLD_TAIL_MARGIN
	OR	A
	SBC	HL,DE				; MARGIN - remaining; CF=1 -> MARGIN < remaining
	RET	C				; remaining > MARGIN -> not yet
	LD	A,1
	LD	(HOLD_MODE),A
	LD	HL,0
	LD	(HOLD_LEN),HL
	RET

; ------------------------------------------------------
; remaining = CONTENT_LENGTH - BODY_BYTES (32-bit).
; Out: if the high word is 0 and CL>=BODY: Z=1, A=0, HL=remaining low word.
;      otherwise NZ (remaining >= 65536, or CL < BODY). Trashes BC,DE.
; ------------------------------------------------------
BODY_REMAINING
	OR	A
	LD	HL,(CONTENT_LENGTH)
	LD	DE,(BODY_BYTES)
	SBC	HL,DE
	PUSH	HL				; remaining low
	LD	HL,(CONTENT_LENGTH+2)
	LD	DE,(BODY_BYTES+2)
	SBC	HL,DE				; remaining high, CF=borrow if CL<BODY
	JR	C,.NEG
	LD	A,H
	OR	L				; Z iff high word 0
	POP	HL				; remaining low (preserves flags)
	RET
.NEG
	POP	HL
	OR	1				; force NZ
	RET

; ------------------------------------------------------
; Compute RECV_DEST / RECV_CAP for the next TCP.RECEIVE. In hold mode data is
; appended at RECV_BUFFER+HOLD_LEN. In stream mode it overwrites from the start,
; but the capacity is clamped so a read never crosses into the final
; HOLD_TAIL_MARGIN bytes (that tail is always taken in hold mode instead).
; ------------------------------------------------------
SETUP_RECV_DEST
	LD	A,(HOLD_MODE)
	AND	A
	JR	Z,.STREAM
	; hold: dest = RECV_BUFFER + HOLD_LEN, cap = RECV_BUFFER_SIZE - HOLD_LEN
	LD	HL,RECV_BUFFER
	LD	DE,(HOLD_LEN)
	ADD	HL,DE
	LD	(RECV_DEST),HL
	EX	DE,HL
	LD	HL,RECV_BUFFER+RECV_BUFFER_SIZE
	OR	A
	SBC	HL,DE
	LD	(RECV_CAP),HL
	RET
.STREAM
	LD	HL,RECV_BUFFER
	LD	(RECV_DEST),HL
	LD	HL,RECV_BUFFER_SIZE
	LD	(RECV_CAP),HL
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	RET	Z
	CALL	BODY_REMAINING
	RET	NZ				; remaining >= 65536 -> full buffer
	; allowed = remaining - HOLD_TAIL_MARGIN; if <= 0 hold mode handles it
	LD	DE,HOLD_TAIL_MARGIN
	OR	A
	SBC	HL,DE
	RET	C				; remaining < MARGIN -> next loop enters hold
	RET	Z				; remaining == MARGIN -> next loop enters hold
	; cap = min(RECV_BUFFER_SIZE, allowed) so the last stream read ends exactly
	; HOLD_TAIL_MARGIN before the body end.
	LD	DE,RECV_BUFFER_SIZE
	PUSH	HL
	OR	A
	SBC	HL,DE
	POP	HL				; HL = allowed
	RET	NC				; allowed >= buffer -> keep full buffer cap
	LD	(RECV_CAP),HL
	RET

; ------------------------------------------------------
; Write any retained tail (HOLD_LEN bytes from RECV_BUFFER) to the output file
; and leave hold mode. Called once the transfer body is complete. CF=1 on a
; DSS_WRITE error.
; ------------------------------------------------------
FLUSH_HOLD
	LD	A,(HOLD_MODE)
	AND	A
	RET	Z
	LD	BC,(HOLD_LEN)
	LD	A,B
	OR	C
	JR	Z,.CLEAR
	LD	HL,RECV_BUFFER
	CALL	WRITE_OUTPUT
	RET	C
.CLEAR
	XOR	A
	LD	(HOLD_MODE),A
	LD	HL,0
	LD	(HOLD_LEN),HL
	XOR	A
	RET

PRINT_BODY_LOG_HEADER
	LD	A,1
	LD	(BODY_LOG_PRINTED),A
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	JR	Z,.UNKNOWN
	PRINT	MSG_CONTENT_LENGTH
	LD	HL,CONTENT_LENGTH
	CALL	PRINT_U32_AT_HL
	PRINTLN	MSG_BYTES
	JR	.DOWNLOAD
.UNKNOWN
	PRINTLN	MSG_CONTENT_UNKNOWN
.DOWNLOAD
	PRINT	MSG_DOWNLOADING
	RET

PRINT_DOWNLOADED_BYTES
	PRINT	MSG_DOWNLOADED
	LD	HL,TOTAL_BYTES
	CALL	PRINT_U32_AT_HL
	PRINTLN	MSG_BYTES
	RET

PREPARE_RESUME_RETRY
	; Persist any retained tail before resuming: BODY_BYTES counts the held
	; bytes as received, so the file must contain them before a Range refetch
	; continues from BODY_BYTES.
	CALL	FLUSH_HOLD
	JP	C,FILE_ERROR_EXIT
	LD	A,(RESUME_COUNT)
	CP	RESUME_LIMIT
	JR	NC,.GIVE_UP
	CALL	TOTAL_BYTES_IS_ZERO
	JR	Z,.GIVE_UP
	LD	A,(BODY_BYTES)
	LD	E,A
	LD	A,(BODY_BYTES+1)
	OR	E
	LD	E,A
	LD	A,(BODY_BYTES+2)
	OR	E
	LD	E,A
	LD	A,(BODY_BYTES+3)
	OR	E
	JR	Z,.GIVE_UP

	LD	A,(RESUME_COUNT)
	INC	A
	LD	(RESUME_COUNT),A

	LD	A,(TCP_IS_OPEN)
	AND	A
	JR	Z,.CLOSED
	LD	A,(SAW_CLOSED)
	AND	A
	CALL	Z,TCP.CLOSE
.CLOSED
	XOR	A
	LD	(TCP_IS_OPEN),A
	LD	(HTTP_INCOMPLETE),A

	PRINT	WCOMMON.LINE_END
	PRINT	MSG_RESUME
	LD	HL,TOTAL_BYTES
	CALL	PRINT_U32_AT_HL
	PRINTLN	MSG_BYTES
	XOR	A
	RET
.GIVE_UP
	CALL	PRINT_CONTENT_LENGTH_MISMATCH
	RET

TOTAL_BYTES_IS_ZERO
	LD	A,(TOTAL_BYTES)
	LD	E,A
	LD	A,(TOTAL_BYTES+1)
	OR	E
	LD	E,A
	LD	A,(TOTAL_BYTES+2)
	OR	E
	LD	E,A
	LD	A,(TOTAL_BYTES+3)
	OR	E
	RET

STORE_RECV_DEBUG
	LD	(DEBUG_RECV_RESULT),A
	LD	(DEBUG_RECV_BYTES),BC
	AND	A
	JR	Z,.BYTES_READY
	LD	HL,(TCP.RECV_STORED)
	LD	(DEBUG_RECV_BYTES),HL
.BYTES_READY
	LD	A,(DEBUG_RECV_RESULT)
	RET

PRINT_RECV_DEBUG
	PRINT	MSG_DBG_RECV
	LD	A,(DEBUG_RECV_RESULT)
	CALL	PRINT_A_DEC
	LD	A,(DEBUG_RECV_RESULT)
	CALL	PRINT_RESULT_REASON
	PRINT	MSG_DBG_GOT
	LD	HL,(DEBUG_RECV_BYTES)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DBG_IPD
	LD	HL,(TCP.LAST_IPD_LEN)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DBG_LEFT
	LD	HL,(TCP.PAYLOAD_LEFT)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DBG_LSR
	LD	A,(TCP.LAST_LSR)
	LD	C,A
	LD	DE,DEBUG_LSR_HEX
	CALL	UTIL.HEXB
	PRINT	DEBUG_LSR_HEX
	PRINT	MSG_DBG_LSR_ACC
	LD	A,(TCP.LSR_ACCUM)
	LD	C,A
	LD	DE,DEBUG_LSR_ACC_HEX
	CALL	UTIL.HEXB
	PRINT	DEBUG_LSR_ACC_HEX
	PRINT	MSG_DBG_TOTAL
	LD	HL,TOTAL_BYTES
	CALL	PRINT_U32_AT_HL
	PRINT	WCOMMON.LINE_END
	RET

; Print " (<plain-language reason>)" for the RES_* code in A so testers can read
; the diagnostic without the esplib code table. Trashes A,HL,DE.
PRINT_RESULT_REASON
	PUSH	AF
	PRINT	MSG_REASON_OPEN			; " ("
	POP	AF
	CP	RES_REASON_COUNT
	JR	C,.KNOWN
	LD	HL,MSG_REASON_UNKNOWN
	JR	.PRINT
.KNOWN
	LD	L,A
	LD	H,0
	ADD	HL,HL				; code * 2 (word table)
	LD	DE,RESULT_REASON_TABLE
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
.PRINT
	PRINT_HL
	PRINT	MSG_REASON_CLOSE		; ")"
	RET

RES_REASON_COUNT	EQU 9
RESULT_REASON_TABLE
	DW MSG_R_OK, MSG_R_ERROR, MSG_R_FAIL, MSG_R_TXTO, MSG_R_RXTO
	DW MSG_R_CONN, MSG_R_NOTCONN, MSG_R_ENABLED, MSG_R_DISABLED

PRINT_A_DEC
	LD	L,A
	LD	H,0
	JR	PRINT_HL_DEC

PRINT_HL_DEC
	LD	DE,NUM_PRINT_BUFF
	CALL	UTIL.UTOA
	PRINT	NUM_PRINT_BUFF
	RET

ADD_BODY_BYTES
	LD	HL,(BODY_BYTES)
	ADD	HL,BC
	LD	(BODY_BYTES),HL
	JR	NC,.ADD_TOTAL
	LD	HL,(BODY_BYTES+2)
	INC	HL
	LD	(BODY_BYTES+2),HL
.ADD_TOTAL
	LD	HL,(TOTAL_BYTES)
	ADD	HL,BC
	LD	(TOTAL_BYTES),HL
	RET	NC
	LD	HL,(TOTAL_BYTES+2)
	INC	HL
	LD	(TOTAL_BYTES+2),HL
	RET

CHECK_CONTENT_LENGTH
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	JR	Z,CHECK_CL_OK
	CALL	CMP_BODY_TO_CONTENT
	JR	Z,CHECK_CL_OK
	JR	C,CHECK_CL_INCOMPLETE
	JR	PRINT_CONTENT_LENGTH_MISMATCH
PRINT_CONTENT_LENGTH_MISMATCH
	PRINT	WCOMMON.LINE_END
	PRINTLN MSG_INCOMPLETE
	PRINT	MSG_EXPECTED
	LD	HL,CONTENT_LENGTH
	CALL	PRINT_U32_AT_HL
	PRINTLN	MSG_BYTES
	CALL	PRINT_DOWNLOADED_BYTES
	LD	A,(DEBUG_PRINTED)
	AND	A
	JR	NZ,.DEBUG_DONE
	CALL	PRINT_RECV_DEBUG
.DEBUG_DONE
	CALL	PRINT_UART_OVERRUN_HINT
	LD	A,RES_RS_TIMEOUT
	SCF
	RET
CHECK_CL_INCOMPLETE
	LD	A,1
	LD	(HTTP_INCOMPLETE),A
	LD	A,RES_RS_TIMEOUT
	SCF
	RET
CHECK_CL_OK
	XOR	A
	RET

; Compare BODY_BYTES to CONTENT_LENGTH as unsigned 32-bit values.
; Out: Z=1 if equal; CF=1 if BODY_BYTES < CONTENT_LENGTH.
CMP_BODY_TO_CONTENT
	LD	HL,CONTENT_LENGTH+3
	LD	DE,BODY_BYTES+3
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	DEC	DE
	DEC	HL
	DJNZ	.CMP
	XOR	A
	RET

PRINT_UART_OVERRUN_HINT
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE
	RET	Z
	PRINTLN	MSG_UART_OVERRUN
	RET

; Z=1 iff Content-Length is known and BODY_BYTES >= CONTENT_LENGTH.
BODY_IS_COMPLETE
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	JR	Z,.INCOMPLETE
	OR	A
	LD	HL,(CONTENT_LENGTH)
	LD	DE,(BODY_BYTES)
	SBC	HL,DE
	LD	B,H
	LD	C,L			; BC = low(CL - BODY)
	LD	HL,(CONTENT_LENGTH+2)
	LD	DE,(BODY_BYTES+2)
	SBC	HL,DE			; HL = high(CL - BODY); CF=1 if CL < BODY
	JR	C,.COMPLETE		; body overshoots CL -> complete
	LD	A,H
	OR	L
	OR	B
	OR	C
	JR	Z,.COMPLETE		; remaining == 0 -> complete
.INCOMPLETE
	OR	0xFF
	RET
.COMPLETE
	XOR	A
	RET

SHOULD_FINISH_AFTER_CLOSED
	LD	A,(CONTENT_LENGTH_SEEN)
	AND	A
	RET	Z
	LD	HL,CONTENT_LENGTH
	LD	DE,BODY_BYTES
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.NOT_YET
	INC	DE
	INC	HL
	DJNZ	.CMP
	XOR	A
	RET
.NOT_YET
	LD	A,1
	OR	A
	RET

UART_RX_ERROR_SEEN
	LD	A,(TCP.LSR_ACCUM)
	AND	LSR_OE | LSR_PE | LSR_FE | LSR_BI | LSR_RCVE
	RET

PARSE_CONTENT_LENGTH_U32
	XOR	A
	LD	(CONTENT_LENGTH),A
	LD	(CONTENT_LENGTH+1),A
	LD	(CONTENT_LENGTH+2),A
	LD	(CONTENT_LENGTH+3),A
.NEXT
	LD	A,(HL)
	CP	'0'
	RET	C
	CP	'9'+1
	RET	NC
	SUB	'0'
	PUSH	HL
	LD	(U32_DIGIT),A
	CALL	U32_MUL10_CONTENT
	LD	A,(U32_DIGIT)
	CALL	U32_ADD_A_CONTENT
	POP	HL
	INC	HL
	JR	.NEXT

U32_MUL10_CONTENT
	CALL	U32_COPY_CONTENT_TO_TEMP
	CALL	U32_SHL1_CONTENT
	CALL	U32_SHL1_TEMP
	CALL	U32_SHL1_TEMP
	CALL	U32_SHL1_TEMP
	JP	U32_ADD_TEMP_TO_CONTENT

U32_COPY_CONTENT_TO_TEMP
	LD	HL,CONTENT_LENGTH
	LD	DE,U32_TEMP
	LD	BC,4
.COPY
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.COPY
	RET

U32_SHL1_CONTENT
	LD	HL,CONTENT_LENGTH
	JR	U32_SHL1_AT_HL

U32_SHL1_TEMP
	LD	HL,U32_TEMP

U32_SHL1_AT_HL
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	RET

U32_ADD_TEMP_TO_CONTENT
	LD	HL,CONTENT_LENGTH
	LD	DE,U32_TEMP
	LD	A,(DE)
	ADD	A,(HL)
	LD	(HL),A
	INC	HL
	INC	DE
	LD	A,(DE)
	ADC	A,(HL)
	LD	(HL),A
	INC	HL
	INC	DE
	LD	A,(DE)
	ADC	A,(HL)
	LD	(HL),A
	INC	HL
	INC	DE
	LD	A,(DE)
	ADC	A,(HL)
	LD	(HL),A
	RET

U32_ADD_A_CONTENT
	LD	E,A
	LD	D,0
	LD	HL,CONTENT_LENGTH
	LD	A,(HL)
	ADD	A,E
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	ADC	A,D
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	ADC	A,D
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	ADC	A,D
	LD	(HL),A
	RET

; ------------------------------------------------------
; Print little-endian 32-bit unsigned integer at HL as decimal.
; ------------------------------------------------------
PRINT_U32_AT_HL
	LD	DE,U32_PRINT_VALUE
	LD	BC,4
.COPY
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.COPY
	XOR	A
	LD	(U32_PRINT_STARTED),A
	LD	IX,U32_POW10_TABLE
	LD	B,10
.POW_LOOP
	XOR	A
	LD	(U32_PRINT_DIGIT),A
.SUB_LOOP
	PUSH	BC,IX
	CALL	U32_COMPARE_PRINT_IX
	POP	IX,BC
	JR	C,.DIGIT_READY
	PUSH	BC,IX
	CALL	U32_SUB_PRINT_IX
	POP	IX,BC
	LD	A,(U32_PRINT_DIGIT)
	INC	A
	LD	(U32_PRINT_DIGIT),A
	JR	.SUB_LOOP
.DIGIT_READY
	LD	A,(U32_PRINT_DIGIT)
	AND	A
	JR	NZ,.PRINT_DIGIT
	LD	A,(U32_PRINT_STARTED)
	AND	A
	JR	Z,.NEXT_POWER
	XOR	A
.PRINT_DIGIT
	ADD	A,'0'
	CALL	PUT_CHAR
	LD	A,1
	LD	(U32_PRINT_STARTED),A
.NEXT_POWER
	LD	DE,4
	ADD	IX,DE
	DJNZ	.POW_LOOP
	LD	A,(U32_PRINT_STARTED)
	AND	A
	RET	NZ
	LD	A,'0'
	JP	PUT_CHAR

; Append little-endian 32-bit unsigned integer at DE as decimal.
; In: HL - destination pointer, DE - source pointer.
; Out: HL - destination pointer after appended digits.
APPEND_U32_FROM_DE
	LD	(U32_APPEND_PTR),HL
	LD	HL,U32_PRINT_VALUE
	LD	BC,4
.COPY
	LD	A,(DE)
	LD	(HL),A
	INC	DE
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.COPY
	XOR	A
	LD	(U32_PRINT_STARTED),A
	LD	IX,U32_POW10_TABLE
	LD	B,10
.POW_LOOP
	XOR	A
	LD	(U32_PRINT_DIGIT),A
.SUB_LOOP
	PUSH	BC,IX
	CALL	U32_COMPARE_PRINT_IX
	POP	IX,BC
	JR	C,.DIGIT_READY
	PUSH	BC,IX
	CALL	U32_SUB_PRINT_IX
	POP	IX,BC
	LD	A,(U32_PRINT_DIGIT)
	INC	A
	LD	(U32_PRINT_DIGIT),A
	JR	.SUB_LOOP
.DIGIT_READY
	LD	A,(U32_PRINT_DIGIT)
	AND	A
	JR	NZ,.APPEND_DIGIT
	LD	A,(U32_PRINT_STARTED)
	AND	A
	JR	Z,.NEXT_POWER
	XOR	A
.APPEND_DIGIT
	ADD	A,'0'
	CALL	APPEND_U32_CHAR
	LD	A,1
	LD	(U32_PRINT_STARTED),A
.NEXT_POWER
	LD	DE,4
	ADD	IX,DE
	DJNZ	.POW_LOOP
	LD	A,(U32_PRINT_STARTED)
	AND	A
	JR	NZ,.DONE
	LD	A,'0'
	CALL	APPEND_U32_CHAR
.DONE
	LD	HL,(U32_APPEND_PTR)
	RET

APPEND_U32_CHAR
	LD	HL,(U32_APPEND_PTR)
	LD	(HL),A
	INC	HL
	LD	(U32_APPEND_PTR),HL
	RET

; CF=0 when value >= power, CF=1 when value < power.
U32_COMPARE_PRINT_IX
	LD	HL,U32_PRINT_VALUE+3
	LD	A,(IX+3)
	CP	(HL)
	JR	NZ,.NE
	DEC	HL
	LD	A,(IX+2)
	CP	(HL)
	JR	NZ,.NE
	DEC	HL
	LD	A,(IX+1)
	CP	(HL)
	JR	NZ,.NE
	DEC	HL
	LD	A,(IX+0)
	CP	(HL)
	JR	NZ,.NE
	AND	A
	RET
.NE
	JR	C,.VALUE_GREATER
	SCF
	RET
.VALUE_GREATER
	AND	A
	RET

U32_SUB_PRINT_IX
	LD	HL,U32_PRINT_VALUE
	LD	A,(HL)
	SUB	(IX+0)
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	SBC	A,(IX+1)
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	SBC	A,(IX+2)
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	SBC	A,(IX+3)
	LD	(HL),A
	RET

PUT_CHAR
	PUSH	BC,HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL,BC
	RET

PRINT_HTTP_STATUS
	LD	HL,(HTTP_STATUS_PTR)
	LD	A,H
	OR	L
	RET	Z
	PRINT	MSG_HTTP_STATUS
	LD	HL,(HTTP_STATUS_PTR)
	LD	B,80
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.DONE
	CP	13
	JR	Z,.DONE
	CP	10
	JR	Z,.DONE
	LD	C,DSS_PUTCHAR
	RST	DSS
	INC	HL
	DJNZ	.NEXT
.DONE
	PRINT	WCOMMON.LINE_END
	RET

PRINT_HTTP_UNSUPPORTED
	LD	A,(HTTP_UNSUPPORTED_REASON)
	CP	HTTP_UNSUPPORTED_REDIRECT
	JR	Z,.REDIRECT
	CP	HTTP_UNSUPPORTED_HTTPS
	JR	Z,.HTTPS
	CP	HTTP_UNSUPPORTED_CHUNKED
	JR	Z,.CHUNKED
	CP	HTTP_UNSUPPORTED_GZIP
	JR	Z,.GZIP
	PRINTLN	MSG_HTTP_UNSUPPORTED
	RET
.REDIRECT
	PRINTLN	MSG_REDIRECT_UNSUPPORTED
	RET
.HTTPS
	PRINTLN	MSG_HTTPS_UNSUPPORTED
	RET
.CHUNKED
	PRINTLN	MSG_CHUNKED_UNSUPPORTED
	RET
.GZIP
	PRINTLN	MSG_GZIP_UNSUPPORTED
	RET

APPEND_STR
	LD	A,(DE)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	DE
	JR	APPEND_STR

APPEND_IX_STR
	LD	A,(IX+0)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	IX
	JR	APPEND_IX_STR

MSG_START
	DB "WGET "
	PACKAGE_VERSION_TAG
	DB " - HTTP downloader for SprinterESP"
	DB 0
MSG_USAGE
	DB "Usage: WGET.EXE url [-o output] [-y|-f] [-r]",13,10
	DB "  -o name   output file (default: name from URL)",13,10
	DB "  -y, -f    overwrite an existing file",13,10
	DB "  -r        resume (append to an existing file)",13,10
	DB "  /?        show this help",0
MSG_WIFI_NOT_FOUND
	DB "Sprinter-WiFi not found!",0
MSG_UART_READY
	DB "UART initialized.",0
MSG_CONNECTING
	DB "Connecting to ",0
MSG_COLON
	DB ":",0
MSG_OUTPUT
	DB "Output file: ",0
MSG_DOWNLOADING
	DB "Downloading body...",13,10,0
MSG_SOURCE
	DB "Source URL: ",0
MSG_SCHEME_ADDED
	DB "No URL scheme specified, using http://.",0
MSG_CONTENT_LENGTH
	DB "Content-Length: ",0
MSG_CONTENT_UNKNOWN
	DB "Content-Length: unknown",0
MSG_DOWNLOADED
	DB "Downloaded: ",0
MSG_BYTES
	DB " bytes",0
MSG_EXPECTED
	DB "Expected: ",0
MSG_RESUME
	DB "HTTP body incomplete, resuming at ",0
MSG_DBG_RECV
	DB "TCP recv: result=",0
MSG_DBG_GOT
	DB " got=",0
MSG_DBG_IPD
	DB " ipd=",0
MSG_DBG_LEFT
	DB " left=",0
MSG_DBG_LSR
	DB " lsr=0x",0
MSG_DBG_LSR_ACC
	DB " lsr_acc=0x",0
MSG_DBG_TOTAL
	DB " total=",0
; Plain-language names for the RES_* result codes (esplib.asm), shown in
; parentheses after "result=N" so testers don't have to ask what 4/6 mean.
MSG_REASON_OPEN
	DB " (",0
MSG_REASON_CLOSE
	DB ")",0
MSG_REASON_UNKNOWN
	DB "unknown",0
MSG_R_OK
	DB "ok",0
MSG_R_ERROR
	DB "ESP error",0
MSG_R_FAIL
	DB "failed",0
MSG_R_TXTO
	DB "send timeout",0
MSG_R_RXTO
	DB "receive timeout - no data",0
MSG_R_CONN
	DB "connected",0
MSG_R_NOTCONN
	DB "connection closed by server",0
MSG_R_ENABLED
	DB "enabled",0
MSG_R_DISABLED
	DB "disabled",0
MSG_NO_RESPONSE
	DB "No HTTP response received.",0
MSG_NO_BODY
	DB "HTTP response has no downloaded body.",0
MSG_DONE
	DB "WGET done.",0
MSG_NET_ERROR
	DB "Network/ESP error #"
MSG_ERROR_NO
	DB "n!",0
; Plain-language hints for the RES_* codes, printed under "Network/ESP error #N".
; Indexed by code; a 0 entry means "no hint for this code".
NET_REASON_COUNT	EQU 7
NET_REASON_TABLE
	DW 0			; 0 RES_OK (not an error)
	DW MSG_NETR_ERR		; 1 RES_ERROR
	DW MSG_NETR_FAIL	; 2 RES_FAIL
	DW MSG_NETR_TXTO	; 3 RES_TX_TIMEOUT
	DW MSG_NETR_RXTO	; 4 RES_RS_TIMEOUT
	DW 0			; 5 RES_CONNECTED
	DW MSG_NETR_NOCONN	; 6 RES_NOT_CONN
MSG_NETR_ERR
	DB "Could not open the connection: host down or refused, wrong",13,10
	DB "address/DNS, or Wi-Fi not up (run NETUP).",0
MSG_NETR_FAIL
	DB "The network operation failed.",0
MSG_NETR_TXTO
	DB "Sprinter-WiFi (ESP) did not respond - check the card and cabling.",0
MSG_NETR_RXTO
	DB "No reply from the server - it may be down or too slow (timeout).",0
MSG_NETR_NOCONN
	DB "The connection was closed before the transfer finished.",0
MSG_FILE_ERROR
	DB "File error: ",0
MSG_ABORTED
	DB "Aborted by user.",0
MSG_OVERWRITE_PRE
	DB "Local file '",0
MSG_OVERWRITE_POST
	DB "' exists. [R]esume / [O]verwrite / [C]ancel? ",0
MSG_RESUME_AT
	DB "Resuming at ",0
MSG_HTTP_UNSUPPORTED
	DB "Unsupported HTTP response.",0
MSG_HTTP_STATUS
	DB "HTTP status: ",0
MSG_INCOMPLETE
	DB "HTTP body size does not match Content-Length.",0
MSG_UART_OVERRUN
	DB "UART overrun detected. Try lower BAUD or check RTS/CTS flow control.",0
MSG_REDIRECT
	DB "Redirecting to: ",0
MSG_REDIRECT_UNSUPPORTED
	DB "Unsupported redirect URL.",0
MSG_HTTPS_UNSUPPORTED
	DB "HTTPS is not supported.",0
MSG_CHUNKED_UNSUPPORTED
	DB "Unsupported Transfer-Encoding: chunked.",0
MSG_GZIP_UNSUPPORTED
	DB "Unsupported Content-Encoding: gzip.",0
MSG_CANCELLED
	DB "Cancelled by user.",0

CMD_AT
	DB "AT",13,10,0
CMD_ECHO_OFF
	DB "ATE0",13,10,0
CMD_CIPMUX_0
	DB "AT+CIPMUX=0",13,10,0

HTTP_PREFIX
	DB "http://",0
HTTPS_PREFIX
	DB "https://",0
HTTP_STATUS_PREFIX
	DB "HTTP/",0
CONTENT_LENGTH_PREFIX
	DB "Content-Length:",0
TRANSFER_ENCODING_PREFIX
	DB "Transfer-Encoding:",0
CONTENT_ENCODING_PREFIX
	DB "Content-Encoding:",0
LOCATION_PREFIX
	DB "Location:",0
CHUNKED_VALUE
	DB "chunked",0
GZIP_VALUE
	DB "gzip",0
CLOSED_WORD
	DB "CLOSED"
DEFAULT_PORT
	DB "80",0
DEFAULT_PATH
	DB "/",0
DEFAULT_OUT_FILE
	DB "INDEX.HTM",0
SWITCH_OUTPUT_DASH
	DB "-o",0
SWITCH_OUTPUT_SLASH
	DB "/o",0
SWITCH_YES_DASH
	DB "-y",0
SWITCH_YES_SLASH
	DB "/y",0
SWITCH_FORCE_DASH
	DB "-f",0
SWITCH_FORCE_SLASH
	DB "/f",0
SWITCH_RESUME_DASH
	DB "-r",0
SWITCH_RESUME_SLASH
	DB "/r",0
SWITCH_HELP_Q_SLASH
	DB "/?",0
SWITCH_HELP_Q_DASH
	DB "-?",0
SWITCH_HELP_H_SLASH
	DB "/h",0
SWITCH_HELP_H_DASH
	DB "-h",0

REQ_GET
	DB "GET ",0
REQ_HTTP
	DB " HTTP/1.1",13,10,"Host: ",0
REQ_PORT_SEP
	DB ":",0
REQ_RANGE
	DB 13,10,"Range: bytes=",0
REQ_RANGE_END
	DB "-",0
REQ_END
	; Keep-alive so the server does NOT close after the body. In active +IPD
	; mode ESP-AT discards the ~1-1.5 KB still queued in its UART output when it
	; processes the peer FIN, which truncated every download. With keep-alive
	; the server leaves the socket open, the ESP delivers the whole body, we
	; stop once Content-Length bytes are in (BODY_IS_COMPLETE) and close it
	; ourselves. Servers that ignore keep-alive fall back to the resume path.
	DB 13,10
	DB "Connection: keep-alive",13,10
	DB 13,10,0

ARG_LEN		DB 0
OUT_FH		DB NO_HANDLE
HELP_REQUESTED	DB 0
CMDLINE_PTR	DW 0		; arg buffer ptr captured from IX at entry
FORCE_OVERWRITE	DB 0
FORCE_RESUME	DB 0
OUTPUT_ABORTED	DB 0
GOT_RESPONSE	DB 0
HEADER_DONE	DB 0
HDR_STATE	DB 0
HAVE_BODY	DB 0
PORT_IS_DEFAULT	DB 0
LAST_TCP_ERR	DB 0
TCP_IS_OPEN	DB 0
HTTP_STATUS_PTR	DW 0
ADJUST_RESPONSE	DB 0
CONTENT_LENGTH	DD 0
CONTENT_LENGTH_SEEN DB 0
BODY_BYTES	DD 0
TOTAL_BYTES	DD 0
SESSION_BASE	DD 0			; TOTAL_BYTES at run start (resume seed / 0)
HTTP_INCOMPLETE DB 0
RANGE_ACTIVE	DB 0
RESUME_COUNT	DB 0
BODY_LOG_PRINTED DB 0
HEADER_LINE_LEN DB 0
SAW_CLOSED	DB 0
HTTP_STATUS_CLASS DB 0
REDIRECT_PENDING DB 0
REDIRECT_COUNT	DB 0
LOCATION_SEEN	DB 0
HTTP_UNSUPPORTED_REASON DB 0
U32_DIGIT	DB 0
U32_TEMP	DD 0
URL_SCHEME_ADDED DB 0
U32_PRINT_STARTED DB 0
U32_PRINT_DIGIT DB 0
U32_PRINT_VALUE DD 0
U32_APPEND_PTR	DW 0
DEBUG_RECV_RESULT DB 0
DEBUG_RECV_BYTES DW 0
DEBUG_PRINTED	DB 0
DEBUG_LSR_HEX	DB "xx",0
DEBUG_LSR_ACC_HEX DB "xx",0
TRIM_ORIG_LEN	DW 0
TRIM_CAND_LEN	DW 0
TRIM_TMP	DD 0
; Retain-tail (hold) mode state.
HOLD_MODE	DB 0
HOLD_LEN	DW 0
RECV_DEST	DW 0
RECV_CAP	DW 0
U32_POW10_TABLE
	DD 1000000000
	DD 100000000
	DD 10000000
	DD 1000000
	DD 100000
	DD 10000
	DD 1000
	DD 100
	DD 10
	DD 1

	ENDMODULE

	; WGET consumes NET_BAUD/NET_ESP_* from NETUP and never loads NET.CFG.
	DEFINE	NETCFG_SESSION_ONLY
	INCLUDE "netcfg_lib.asm"
	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	; DNS resolution plus an external ESP8266 TCP connect can legitimately
	; exceed the shared 20-second local-service timeout.
	DEFINE	TCP_LONG_OPEN_TIMEOUT
	INCLUDE "esp_tcp.asm"
	INCLUDE "tput_lib.asm"
	; esplib.asm MUST be last: it ends with the RS_BUFF label that anchors the
	; runtime receive buffer and all BSS. Any include placed after it would have
	; its code/data overlaid by the ESP receive buffer.
	IFNDEF	ESP_AT_FORCE_222
	DEFINE	WIFI_STABLE_ACTIVE_RX
	ENDIF
	INCLUDE "esplib.asm"

	MODULE MAIN

	ASSERT	$ < STACK_TOP - 0x0100

WGET_BSS_BASE	EQU NETCFG.NETCFG_BSS_END
NUM_PRINT_BUFF	EQU WGET_BSS_BASE
URL_BUFF	EQU NUM_PRINT_BUFF + 8
HOST_BUFF	EQU URL_BUFF + URL_SIZE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
PATH_BUFF	EQU PORT_BUFF + PORT_SIZE
OUT_FILE	EQU PATH_BUFF + PATH_SIZE
REQ_BUFF	EQU OUT_FILE + FILE_SIZE
HEADER_LINE	EQU REQ_BUFF + REQ_SIZE
LOCATION_BUFF	EQU HEADER_LINE + HEADER_LINE_SIZE
WGET_BSS_END	EQU LOCATION_BUFF + URL_SIZE
RECV_BUFFER	EQU WIN2_BASE
	; RECV_BUFFER uses the whole allocated WIN2 page; stack stays at #8000
	; and therefore grows downward in WIN1.
	ASSERT	WGET_BSS_END < STACK_TOP - 0x0100
	ASSERT	RECV_BUFFER + RECV_BUFFER_SIZE <= 0xC000

	ENDMODULE

	END MAIN.START
