; Regression vectors for the exact optional ESP-TCP telemetry linked into
; DLSPEED. DLSPEED_REQUEST_TEST suppresses the application's END directive so
; this harness can enter after the included production code.

	DEFINE	DLSPEED_REQUEST_TEST
	INCLUDE "../src/apps/dlspeed.asm"

TEST_RESULT	EQU 0xC000
CAPTURE		EQU 0xC100
EXPECTED_RAM	EQU 0xC300

	MODULE DLSPEED_DIAG_VECTORS

TEST_START
	LD	SP,MAIN.STACK_TOP
	XOR	A
	LD	(TEST_RESULT),A
	LD	A,0xC3
	LD	(DSS),A
	LD	HL,DSS_STUB
	LD	(DSS+1),HL
	; The included application's runtime BSS begins just after its loaded code;
	; this harness's appended expected string can overlap that BSS. Preserve the
	; expected bytes in high test RAM before seeding NETCFG.CFG_BAUD below.
	LD	HL,EXPECTED
	LD	DE,EXPECTED_RAM
	LD	BC,EXPECTED_LEN
	LDIR
	CALL	TCP.DIAG_RESET

	; Verify full 32-bit carry in the counter primitive used by wait telemetry.
	LD	HL,0xFFFF
	LD	(TCP.DIAG_WAIT_TICKS),HL
	LD	HL,0x00FF
	LD	(TCP.DIAG_WAIT_TICKS+2),HL
	CALL	TCP.DIAG_RECORD_WAIT_TICK
	LD	HL,(TCP.DIAG_WAIT_TICKS)
	LD	A,H
	OR	L
	JP	NZ,FAIL_1
	LD	HL,(TCP.DIAG_WAIT_TICKS+2)
	LD	DE,0x0100
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1

	CALL	TCP.DIAG_RESET
	CALL	TCP.DIAG_RECORD_RECEIVE_CALL
	CALL	TCP.DIAG_RECORD_RECEIVE_CALL
	LD	BC,16060
	CALL	TCP.DIAG_RECORD_RECV_BLOCK
	LD	BC,128
	CALL	TCP.DIAG_RECORD_RECV_BLOCK

	LD	HL,1460
	CALL	TCP.DIAG_RECORD_IPD
	LD	HL,512
	CALL	TCP.DIAG_RECORD_IPD
	LD	HL,4096
	CALL	TCP.DIAG_RECORD_IPD

	CALL	TCP.DIAG_BEGIN_CONTINUATION
	CALL	TCP.DIAG_RECORD_WAIT_TICK
	CALL	TCP.DIAG_RECORD_WAIT_TICK
	CALL	TCP.DIAG_END_WAIT_RUN
	CALL	TCP.DIAG_END_CONTINUATION
	CALL	TCP.DIAG_RECORD_WAIT_TICK
	CALL	TCP.DIAG_END_WAIT_RUN
	CALL	TCP.DIAG_RECORD_CONTINUATION_MISS

	LD	HL,TCP.DIAG_RECEIVE_CALLS
	LD	DE,2
	CALL	CHECK32
	JP	NZ,FAIL_2
	LD	HL,TCP.DIAG_RECV_BLOCKS
	LD	DE,2
	CALL	CHECK32
	JP	NZ,FAIL_2
	LD	HL,(TCP.DIAG_RECV_MIN)
	LD	DE,128
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_2
	LD	HL,(TCP.DIAG_RECV_MAX)
	LD	DE,16060
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_2

	LD	HL,TCP.DIAG_IPD_FRAMES
	LD	DE,3
	CALL	CHECK32
	JP	NZ,FAIL_3
	LD	HL,TCP.DIAG_IPD_BYTES
	LD	DE,6068
	CALL	CHECK32
	JP	NZ,FAIL_3
	LD	HL,(TCP.DIAG_IPD_MIN)
	LD	DE,512
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_3
	LD	HL,(TCP.DIAG_IPD_MAX)
	LD	DE,4096
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_3

	LD	HL,TCP.DIAG_WAIT_TICKS
	LD	DE,3
	CALL	CHECK32
	JP	NZ,FAIL_4
	LD	HL,TCP.DIAG_CONT_WAIT_TICKS
	LD	DE,2
	CALL	CHECK32
	JP	NZ,FAIL_4
	LD	HL,TCP.DIAG_CONT_PROBES
	LD	DE,1
	CALL	CHECK32
	JP	NZ,FAIL_4
	LD	HL,TCP.DIAG_CONT_MISSES
	LD	DE,1
	CALL	CHECK32
	JP	NZ,FAIL_4
	LD	HL,(TCP.DIAG_WAIT_MAX)
	LD	DE,2
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_4
	LD	A,(TCP.DIAG_CONT_ACTIVE)
	OR	A
	JP	NZ,FAIL_4

	; Exercise the real post-transfer formatter, including 32/16 IPD average.
	LD	HL,V_BAUD
	LD	DE,NETCFG.CFG_BAUD
	CALL	MAIN.COPY_ASCIIZ
	LD	A,UART_RX_PROFILE_222
	LD	(WCOMMON.UART_ESP_PROFILE),A
	XOR	A
	LD	(WIFI.UART_FLOW_MODE),A
	LD	(TCP.LSR_ACCUM),A
	CALL	MAIN.PRINT_DIAGNOSTICS
	LD	HL,CAPTURE
	LD	DE,EXPECTED_RAM
	LD	BC,EXPECTED_LEN
.COMPARE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_5
	INC	HL
	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.COMPARE
	LD	HL,(CAPTURE_PTR)
	LD	DE,CAPTURE+EXPECTED_LEN
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5

	; Commit a partial first response, then an exact 206 Range continuation.
	LD	A,1
	LD	(DHTTP.CONTENT_LENGTH_SEEN),A
	XOR	A
	LD	(MAIN.RANGE_ACTIVE),A
	LD	(MAIN.FRAGMENT_COMMITTED),A
	LD	HL,0
	LD	(DHTTP.CONTENT_LENGTH),HL
	LD	HL,0x0020		; 2097152
	LD	(DHTTP.CONTENT_LENGTH+2),HL
	LD	HL,0x7A60		; 1473120
	LD	(DHTTP.BODY_BYTES),HL
	LD	HL,0x0016
	LD	(DHTTP.BODY_BYTES+2),HL
	CALL	MAIN.COMMIT_FRAGMENT
	JP	C,FAIL_6
	LD	HL,(MAIN.TOTAL_RECEIVED)
	LD	DE,0x7A60
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_7
	LD	HL,(MAIN.TOTAL_RECEIVED+2)
	LD	DE,0x0016
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_8

	LD	A,1
	LD	(MAIN.RANGE_ACTIVE),A
	XOR	A
	LD	(MAIN.FRAGMENT_COMMITTED),A
	LD	HL,MAIN.HEADER_BUFF
	LD	DE,HEADER_SIZE
	CALL	DHTTP.RESET
	LD	HL,V_RANGE_RESPONSE
	LD	BC,V_RANGE_RESPONSE_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAIL_12
	LD	HL,0x85A0		; remaining 624032
	LD	(DHTTP.BODY_BYTES),HL
	LD	HL,0x0009
	LD	(DHTTP.BODY_BYTES+2),HL
	CALL	MAIN.RANGE_LENGTH_MATCHES
	JP	C,FAIL_12
	CALL	MAIN.COMMIT_FRAGMENT
	JP	C,FAIL_9
	LD	HL,(MAIN.TOTAL_RECEIVED)
	LD	A,H
	OR	L
	JP	NZ,FAIL_10
	LD	HL,(MAIN.TOTAL_RECEIVED+2)
	LD	DE,0x0020
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_11
	; A server that ignores Range and returns 200 must be rejected: accepting it
	; would count a duplicate full body as the missing suffix.
	XOR	A
	LD	(MAIN.FRAGMENT_COMMITTED),A
	LD	HL,MAIN.HEADER_BUFF
	LD	DE,HEADER_SIZE
	CALL	DHTTP.RESET
	LD	HL,V_RANGE_IGNORED
	LD	BC,V_RANGE_IGNORED_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAIL_13
	CALL	MAIN.COMMIT_FRAGMENT
	JP	NC,FAIL_13
	LD	A,(DHTTP.ERROR)
	CP	DHTTP_ERR_RANGE
	JP	NZ,FAIL_13
	JR	TEST_DONE

; Compare 32-bit LE value at HL with zero-extended DE. Out: Z if equal.
CHECK32
	LD	A,(HL)
	CP	E
	RET	NZ
	INC	HL
	LD	A,(HL)
	CP	D
	RET	NZ
	INC	HL
	LD	A,(HL)
	OR	A
	RET	NZ
	INC	HL
	LD	A,(HL)
	OR	A
	RET

FAIL_1
	LD	A,1
	JR	FAILED
FAIL_2
	LD	A,2
	JR	FAILED
FAIL_3
	LD	A,3
	JR	FAILED
FAIL_4
	LD	A,4
	JR	FAILED
FAIL_5
	LD	A,5
	JR	FAILED
FAIL_6
	LD	A,6
	JR	FAILED
FAIL_7
	LD	A,7
	JR	FAILED
FAIL_8
	LD	A,8
	JR	FAILED
FAIL_9
	LD	A,9
	JR	FAILED
FAIL_10
	LD	A,10
	JR	FAILED
FAIL_11
	LD	A,11
	JR	FAILED
FAIL_12
	LD	A,12
	JR	FAILED
FAIL_13
	LD	A,13
FAILED
	LD	(TEST_RESULT),A
TEST_DONE
	NOP

DSS_STUB
	PUSH	AF
	LD	A,C
	CP	DSS_PCHARS
	JR	Z,.PCHARS
	CP	DSS_PUTCHAR
	JR	Z,.PUTCHAR
	POP	AF
	RET
.PCHARS
	POP	AF
	PUSH	HL,DE
	LD	DE,(CAPTURE_PTR)
.COPY
	LD	A,(HL)
	OR	A
	JR	Z,.COPY_DONE
	LD	(DE),A
	INC	HL
	INC	DE
	JR	.COPY
.COPY_DONE
	LD	(CAPTURE_PTR),DE
	POP	DE,HL
	RET
.PUTCHAR
	POP	AF
	PUSH	HL
	LD	HL,(CAPTURE_PTR)
	LD	(HL),A
	INC	HL
	LD	(CAPTURE_PTR),HL
	POP	HL
	RET

CAPTURE_PTR	DW CAPTURE
V_BAUD		DB "115200",0
V_RANGE_RESPONSE
	DB "HTTP/1.1 206 Partial Content",13,10
	DB "Content-Length: 624032",13,10,13,10
V_RANGE_RESPONSE_LEN EQU $-V_RANGE_RESPONSE
V_RANGE_IGNORED
	DB "HTTP/1.1 200 OK",13,10,"Content-Length: 1",13,10,13,10
V_RANGE_IGNORED_LEN EQU $-V_RANGE_IGNORED
EXPECTED
	DB "Diagnostics:",13,10
	DB "UART: 115200 baud, flow 0, ESP-AT 2.2.2, FIFO trigger 8",13,10
	DB "RECEIVE: 2 calls, block min 128, max 16060",13,10
	DB "IPD: 3 frames, 6068 bytes, min 512, max 4096, avg 2022",13,10
	DB "RX 1-ms waits: 3, continuation 2 ms",13,10
	DB "Max RX idle: 2 ms",13,10
	DB "Continuation: 1 probes, misses 1",13,10
	DB "UART LSR mask: 0, errors: 0",13,10
	DB "Reconnects: 0",13,10
EXPECTED_LEN	EQU $-EXPECTED

	ENDMODULE

	END DLSPEED_DIAG_VECTORS.TEST_START
