; Z80 regression vectors for the exact DHTTP parser linked into DLSPEED.

	DEVICE NOSLOT64K

TEST_RESULT	EQU 0xC000
HEADER_BUFFER	EQU 0xC100
HEADER_CAPACITY EQU 1024

	ORG 0x4000
TEST_START
	XOR	A
	LD	(TEST_RESULT),A

	; Status/header name split between receive blocks, body with second block.
	LD	A,1
	LD	(TEST_RESULT),A
	CALL	RESET_PARSER
	LD	HL,V_SPLIT_1
	LD	BC,V_SPLIT_1_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	OR	A
	JP	NZ,FAILED
	LD	HL,V_SPLIT_2
	LD	BC,V_SPLIT_2_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	CP	1
	JP	NZ,FAILED
	LD	HL,5
	CALL	EXPECT_BODY_LOW
	JP	NZ,FAILED

	; 32-bit Content-Length is retained even when only a few body bytes arrived.
	LD	A,2
	LD	(TEST_RESULT),A
	CALL	RESET_PARSER
	LD	HL,V_U32
	LD	BC,V_U32_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	OR	A
	JP	NZ,FAILED
	LD	HL,(DHTTP.CONTENT_LENGTH)
	LD	DE,0x1170		; 70000 = 0x00011170
	OR	A
	SBC	HL,DE
	JP	NZ,FAILED
	LD	HL,(DHTTP.CONTENT_LENGTH+2)
	LD	DE,1
	OR	A
	SBC	HL,DE
	JP	NZ,FAILED

	; Exact completion ignores bytes beyond Content-Length.
	LD	A,3
	LD	(TEST_RESULT),A
	CALL	RESET_PARSER
	LD	HL,V_EXACT
	LD	BC,V_EXACT_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	CP	1
	JP	NZ,FAILED
	LD	HL,3
	CALL	EXPECT_BODY_LOW
	JP	NZ,FAILED

	; Identity is the sole accepted Content-Encoding.
	LD	A,4
	LD	(TEST_RESULT),A
	CALL	RESET_PARSER
	LD	HL,V_IDENTITY
	LD	BC,V_IDENTITY_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	CP	1
	JP	NZ,FAILED

	; Premature EOF is represented by a non-complete parser with an exact
	; partial byte count; the caller converts transport close into exit 3.
	LD	A,5
	LD	(TEST_RESULT),A
	CALL	RESET_PARSER
	LD	HL,V_PARTIAL
	LD	BC,V_PARTIAL_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	OR	A
	JP	NZ,FAILED
	LD	HL,2
	CALL	EXPECT_BODY_LOW
	JP	NZ,FAILED

	LD	A,6
	LD	(TEST_RESULT),A
	LD	HL,V_MISSING
	LD	BC,V_MISSING_LEN
	LD	A,DHTTP_ERR_LENGTH_MISSING
	CALL	EXPECT_ERROR
	JP	NZ,FAILED
	LD	A,7
	LD	(TEST_RESULT),A
	LD	HL,V_STATUS
	LD	BC,V_STATUS_LEN
	LD	A,DHTTP_ERR_STATUS
	CALL	EXPECT_ERROR
	JP	NZ,FAILED
	LD	A,8
	LD	(TEST_RESULT),A
	LD	HL,V_CHUNKED
	LD	BC,V_CHUNKED_LEN
	LD	A,DHTTP_ERR_TRANSFER_ENCODING
	CALL	EXPECT_ERROR
	JP	NZ,FAILED
	LD	A,9
	LD	(TEST_RESULT),A
	LD	HL,V_GZIP
	LD	BC,V_GZIP_LEN
	LD	A,DHTTP_ERR_CONTENT_ENCODING
	CALL	EXPECT_ERROR
	JP	NZ,FAILED
	LD	A,10
	LD	(TEST_RESULT),A
	LD	HL,V_ZERO
	LD	BC,V_ZERO_LEN
	LD	A,DHTTP_ERR_LENGTH_ZERO
	CALL	EXPECT_ERROR
	JP	NZ,FAILED
	LD	A,11
	LD	(TEST_RESULT),A
	LD	HL,V_OVERFLOW
	LD	BC,V_OVERFLOW_LEN
	LD	A,DHTTP_ERR_LENGTH_INVALID
	CALL	EXPECT_ERROR
	JP	NZ,FAILED
	LD	A,12
	LD	(TEST_RESULT),A
	CALL	RESET_PARSER
	LD	HL,V_PARTIAL_CONTENT
	LD	BC,V_PARTIAL_CONTENT_LEN
	CALL	DHTTP.CONSUME
	JP	C,FAILED
	CP	1
	JP	NZ,FAILED
	LD	A,(DHTTP.STATUS_CODE)
	CP	'2'
	JP	NZ,FAILED
	LD	A,(DHTTP.STATUS_CODE+1)
	CP	'0'
	JP	NZ,FAILED
	LD	A,(DHTTP.STATUS_CODE+2)
	CP	'6'
	JP	NZ,FAILED
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

FAILED
TEST_DONE
	RET

RESET_PARSER
	LD	HL,HEADER_BUFFER
	LD	DE,HEADER_CAPACITY
	JP	DHTTP.RESET

EXPECT_BODY_LOW
	LD	DE,(DHTTP.BODY_BYTES)
	OR	A
	SBC	HL,DE
	RET	NZ
	LD	HL,(DHTTP.BODY_BYTES+2)
	LD	A,H
	OR	L
	RET

; HL/vector, BC/length, A/expected parser error.
EXPECT_ERROR
	LD	(EXPECTED_ERROR),A
	PUSH	HL,BC
	CALL	RESET_PARSER
	POP	BC,HL
	CALL	DHTTP.CONSUME
	JR	NC,.BAD
	LD	HL,EXPECTED_ERROR
	CP	(HL)
	RET
.BAD
	OR	1
	RET

EXPECTED_ERROR DB 0

V_SPLIT_1 DB 13,10,"SEND OK",13,10,"HTTP/1.1 200 OK",13,10,"Content-Leng"
V_SPLIT_1_LEN EQU $-V_SPLIT_1
V_SPLIT_2 DB "th: 5",13,10,13,10,"abcde"
V_SPLIT_2_LEN EQU $-V_SPLIT_2
V_U32 DB "HTTP/1.1 200 OK",13,10,"Content-Length: 70000",13,10,13,10,"abc"
V_U32_LEN EQU $-V_U32
V_EXACT DB "HTTP/1.1 204 Fine",13,10,"Content-Length: 3",13,10,13,10,"abcEXTRA"
V_EXACT_LEN EQU $-V_EXACT
V_IDENTITY DB "HTTP/1.1 200 OK",13,10,"Content-Encoding: identity",13,10,"Content-Length: 1",13,10,13,10,"x"
V_IDENTITY_LEN EQU $-V_IDENTITY
V_PARTIAL DB "HTTP/1.1 200 OK",13,10,"Content-Length: 5",13,10,13,10,"ab"
V_PARTIAL_LEN EQU $-V_PARTIAL
V_MISSING DB "HTTP/1.1 200 OK",13,10,13,10,"x"
V_MISSING_LEN EQU $-V_MISSING
V_STATUS DB "HTTP/1.1 302 Found",13,10,"Content-Length: 1",13,10,13,10,"x"
V_STATUS_LEN EQU $-V_STATUS
V_CHUNKED DB "HTTP/1.1 200 OK",13,10,"Transfer-Encoding: chunked",13,10,"Content-Length: 1",13,10,13,10,"x"
V_CHUNKED_LEN EQU $-V_CHUNKED
V_GZIP DB "HTTP/1.1 200 OK",13,10,"Content-Encoding: gzip",13,10,"Content-Length: 1",13,10,13,10,"x"
V_GZIP_LEN EQU $-V_GZIP
V_ZERO DB "HTTP/1.1 200 OK",13,10,"Content-Length: 0",13,10,13,10
V_ZERO_LEN EQU $-V_ZERO
V_OVERFLOW DB "HTTP/1.1 200 OK",13,10,"Content-Length: 4294967296",13,10,13,10
V_OVERFLOW_LEN EQU $-V_OVERFLOW
V_PARTIAL_CONTENT DB "HTTP/1.1 206 Partial Content",13,10,"Content-Length: 3",13,10,13,10,"abc"
V_PARTIAL_CONTENT_LEN EQU $-V_PARTIAL_CONTENT

	INCLUDE "dlspeed_http.asm"
	END TEST_START
