; Z80 vectors for aligned RTC start, saved stop, midnight wrap and zero sample.

	DEVICE NOSLOT64K
	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

TEST_RESULT EQU 0xC000
CAPTURE EQU 0xC100
	ORG 0x4000
TEST_START
	XOR	A
	LD	(TEST_RESULT),A
	LD	(CLOCK_CALLS),A
	LD	A,0xC3
	LD	(DSS),A
	LD	HL,DSS_STUB
	LD	(DSS+1),HL

	CALL	TPUT.START_ALIGNED
	LD	A,(CLOCK_CALLS)
	CP	3			; initial, repeated sample, first new second
	JP	NZ,FAILED
	LD	HL,(TPUT.T_START)
	LD	DE,3724			; 01:02:04
	OR	A
	SBC	HL,DE
	JP	NZ,FAILED

	CALL	TPUT.STOP		; next stub value is 01:02:09
	LD	A,(CLOCK_CALLS)
	CP	4
	JP	NZ,FAILED
	CALL	TPUT.CALC_STOPPED
	LD	A,B
	OR	A
	JP	NZ,FAILED
	LD	DE,5
	OR	A
	SBC	HL,DE
	JP	NZ,FAILED

	; A stopped RTC must return CF instead of hanging forever.
	LD	A,1
	LD	(CLOCK_STUCK),A
	XOR	A
	LD	(CLOCK_CALLS),A
	CALL	TPUT.START_ALIGNED
	JP	NC,FAILED
	LD	A,(CLOCK_CALLS)
	CP	5			; baseline plus four bounded polls
	JP	NZ,FAILED
	XOR	A
	LD	(CLOCK_STUCK),A
	LD	A,4
	LD	(CLOCK_CALLS),A

	; 23:59:59 -> 00:00:00 is one second, not a negative duration.
	LD	HL,0x517F		; 86399 = 0x01517F
	LD	(TPUT.T_START),HL
	LD	A,1
	LD	(TPUT.T_START+2),A
	LD	HL,0
	LD	(TPUT.T_STOP),HL
	XOR	A
	LD	(TPUT.T_STOP+2),A
	CALL	TPUT.CALC_STOPPED
	LD	A,B
	OR	A
	JP	NZ,FAILED
	DEC	HL
	LD	A,H
	OR	L
	JP	NZ,FAILED

	; Same-second start/stop remains exactly zero for sample-too-short handling.
	LD	HL,100
	LD	(TPUT.T_START),HL
	LD	(TPUT.T_STOP),HL
	XOR	A
	LD	(TPUT.T_START+2),A
	LD	(TPUT.T_STOP+2),A
	CALL	TPUT.CALC_STOPPED
	LD	A,B
	OR	H
	OR	L
	JP	NZ,FAILED
	LD	HL,1
	LD	DE,0
	CALL	TPUT.REPORT_STOPPED
	JP	NC,FAILED		; zero seconds must be rejected
	LD	A,(CLOCK_CALLS)
	CP	4			; REPORT_STOPPED must not read RTC
	JP	NZ,FAILED

	; Saved-result formatter: 524288 / 24 = 21845 B/s = 21 KiB/s.
	LD	HL,0
	LD	(TPUT.T_START),HL
	LD	HL,24
	LD	(TPUT.T_STOP),HL
	XOR	A
	LD	(TPUT.T_START+2),A
	LD	(TPUT.T_STOP+2),A
	LD	HL,0
	LD	DE,8
	CALL	TPUT.REPORT_STOPPED
	JP	C,FAILED
	; Exercise a 17-bit duration too: the aligned reporter must not truncate
	; elapsed seconds to the legacy 16-bit divider range.
	LD	HL,0
	LD	(TPUT.T_STOP),HL
	LD	A,1
	LD	(TPUT.T_STOP+2),A	; 65536 sec
	LD	HL,0
	LD	DE,8			; 524288 / 65536 = 8 B/s
	CALL	TPUT.REPORT_STOPPED
	JP	C,FAILED
	LD	HL,CAPTURE
	LD	DE,EXPECTED
	LD	BC,EXPECTED_LEN
.COMPARE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAILED
	INC	HL
	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.COMPARE
	LD	HL,(CAPTURE_PTR)
	LD	DE,CAPTURE+EXPECTED_LEN
	OR	A
	SBC	HL,DE
	JP	NZ,FAILED
	JR	TEST_DONE
FAILED
	LD	A,1
	LD	(TEST_RESULT),A
TEST_DONE
	RET

DSS_STUB
	PUSH	AF
	LD	A,C
	CP	DSS_PCHARS
	JR	Z,.PCHARS
	CP	DSS_PUTCHAR
	JR	Z,.PUTCHAR
	CP	DSS_SYSTIME
	JR	Z,.SYSTIME
	POP	AF
	RET
.PCHARS
	POP	AF
	PUSH	HL,DE
	LD	DE,(CAPTURE_PTR)
.COPY
	LD	A,(HL)
	OR	A
	JR	Z,.COPY_DONE
	LD	(DE),A
	INC	HL
	INC	DE
	JR	.COPY
.COPY_DONE
	LD	(CAPTURE_PTR),DE
	POP	DE,HL
	RET
.PUTCHAR
	POP	AF
	PUSH	HL
	LD	HL,(CAPTURE_PTR)
	LD	(HL),A
	INC	HL
	LD	(CAPTURE_PTR),HL
	POP	HL
	RET
.SYSTIME
	POP	AF
	LD	A,(CLOCK_CALLS)
	INC	A
	LD	(CLOCK_CALLS),A
	LD	H,1
	LD	L,2
	LD	B,3
	LD	A,(CLOCK_STUCK)
	OR	A
	RET	NZ
	LD	A,(CLOCK_CALLS)
	CP	3
	RET	C
	LD	B,4
	RET	Z
	LD	B,9
	RET
CLOCK_CALLS DB 0
CLOCK_STUCK DB 0
CAPTURE_PTR DW CAPTURE
EXPECTED
	DB "Time: 24 sec",13,10
	DB "Rate: 21845 B/s (21 KiB/s)",13,10
	DB "Time: 65536 sec",13,10
	DB "Rate: 8 B/s (0 KiB/s)",13,10
EXPECTED_LEN EQU $-EXPECTED

	MODULE WIFI
UART_RX_PAUSE
	RET
UART_RX_RESUME
	RET
	ENDMODULE
	MODULE UTIL
DELAY_1MS
	RET
	ENDMODULE

	DEFINE TPUT_ALIGN_TEST_SHORT
	DEFINE TPUT_ALIGNED
	INCLUDE "tput_lib.asm"
	END TEST_START
