; Regression vectors for FTP's ESP-AT 2.2.2 active multi-link burst reader.
; Executes the real RECEIVE_ANY_LINK_BURST parser against scripted UART data.

	DEVICE NOSLOT64K

	DEFINE	ESP_TCP_TEST_READER

RS_BUFF_SIZE	EQU 192
REG_RBR		EQU 0xC3E8
REG_LSR		EQU 0xC3ED
LSR_DR		EQU 0x01
LSR_OE		EQU 0x02
LSR_PE		EQU 0x04
LSR_FE		EQU 0x08
LSR_BI		EQU 0x10
LSR_THRE	EQU 0x20
LSR_TEMT	EQU 0x40
LSR_RCVE	EQU 0x80
RES_ERROR	EQU 1
RES_FAIL	EQU 2
RES_TX_TIMEOUT	EQU 3
RES_RS_TIMEOUT	EQU 4
RES_NOT_CONN	EQU 6
RES_BUSY	EQU 9

TEST_RESULT	EQU 0xC000
TEST_MARKER	EQU 0xC001
RECV_DEST	EQU 0xC100

	MACRO ASSERT_W16 addr?, val?
	LD	HL,(addr?)
	LD	DE,val?
	OR	A
	SBC	HL,DE
	LD	A,H
	OR	L
	JP	NZ,FAILED
	ENDM

	MACRO ASSERT_B addr?, val?
	LD	A,(addr?)
	CP	val?
	JP	NZ,FAILED
	ENDM

	ORG 0x4000

TEST_START
	LD	SP,0xBFF0
	XOR	A
	LD	(TEST_RESULT),A
	LD	(TEST_MARKER),A

; Same-link frames are coalesced under one balanced ISA mapping.
	LD	A,1
	LD	(STAGE),A
	CALL	RESET_STATE
	LD	HL,IN_BACK2BACK
	LD	BC,IN_BACK2BACK_LEN
	CALL	SET_INPUT
	LD	HL,RECV_DEST
	LD	BC,2000
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	C,FAILED
	LD	(LAST_BC),BC
	ASSERT_W16 LAST_BC, 6
	ASSERT_B TCP.LAST_IPD_LINK, 0
	ASSERT_B ISA.OPEN_COUNT, 1
	ASSERT_B ISA.CLOSE_COUNT, 1
	ASSERT_B WIFI.PAUSE_OPEN_COUNT, 1
	ASSERT_B WIFI.RESUME_OPEN_COUNT, 1
	LD	HL,RECV_DEST
	LD	DE,EXP_ABCDEF
	LD	B,6
	CALL	CMP_MEM

; A different-link header ends the burst but leaves its body for the next call.
	LD	A,2
	LD	(STAGE),A
	CALL	RESET_STATE
	LD	HL,IN_MIXED
	LD	BC,IN_MIXED_LEN
	CALL	SET_INPUT
	LD	HL,RECV_DEST
	LD	BC,2000
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	C,FAILED
	LD	(LAST_BC),BC
	ASSERT_W16 LAST_BC, 3
	ASSERT_B TCP.LAST_IPD_LINK, 0
	ASSERT_W16 TCP.PAYLOAD_LEFT, 3
	LD	HL,RECV_DEST+3
	LD	BC,2000
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	C,FAILED
	LD	(LAST_BC),BC
	ASSERT_W16 LAST_BC, 3
	ASSERT_B TCP.LAST_IPD_LINK, 1
	ASSERT_W16 TCP.PAYLOAD_LEFT, 0
	LD	HL,RECV_DEST
	LD	DE,EXP_ABCUVW
	LD	B,6
	CALL	CMP_MEM

; CLOSED seen after payload is reported only after those bytes are returned.
	LD	A,3
	LD	(STAGE),A
	CALL	RESET_STATE
	LD	HL,IN_DATA_CLOSE
	LD	BC,IN_DATA_CLOSE_LEN
	CALL	SET_INPUT
	LD	HL,RECV_DEST
	LD	BC,2000
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	C,FAILED
	LD	(LAST_BC),BC
	ASSERT_W16 LAST_BC, 4
	LD	HL,RECV_DEST
	LD	DE,EXP_TAIL
	LD	B,4
	CALL	CMP_MEM
	LD	HL,RECV_DEST+4
	LD	BC,2000
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	NC,FAILED
	CP	RES_NOT_CONN
	JP	NZ,FAILED
	ASSERT_B ISA.OPEN_COUNT, 1
	ASSERT_B ISA.CLOSE_COUNT, 1

; A full caller buffer leaves PAYLOAD_LEFT exact; the next call continues it.
	LD	A,4
	LD	(STAGE),A
	CALL	RESET_STATE
	LD	HL,IN_SPLIT
	LD	BC,IN_SPLIT_LEN
	CALL	SET_INPUT
	LD	HL,RECV_DEST
	LD	BC,4
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	C,FAILED
	LD	(LAST_BC),BC
	ASSERT_W16 LAST_BC, 4
	ASSERT_W16 TCP.PAYLOAD_LEFT, 2
	LD	HL,RECV_DEST+4
	LD	BC,2000
	LD	DE,1000
	CALL	TCP.RECEIVE_ANY_LINK_BURST
	JP	C,FAILED
	LD	(LAST_BC),BC
	ASSERT_W16 LAST_BC, 2
	ASSERT_B TCP.LAST_IPD_LINK, 1
	ASSERT_W16 TCP.PAYLOAD_LEFT, 0
	LD	HL,RECV_DEST
	LD	DE,EXP_ABCDEF
	LD	B,6
	CALL	CMP_MEM

	LD	A,0xA5
	LD	(TEST_MARKER),A
TEST_DONE
	HALT

FAILED
	LD	A,(STAGE)
	LD	(TEST_RESULT),A
	JR	TEST_DONE

RESET_STATE
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	XOR	A
	LD	(TCP.MULTI_PENDING_RESULT),A
	LD	(ISA.OPEN_COUNT),A
	LD	(ISA.CLOSE_COUNT),A
	LD	(WIFI.PAUSE_OPEN_COUNT),A
	LD	(WIFI.RESUME_OPEN_COUNT),A
	RET

SET_INPUT
	LD	(WIFI.INPUT_PTR),HL
	LD	(WIFI.INPUT_LEFT),BC
	RET

CMP_MEM
.LOOP
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAILED
	INC	HL
	INC	DE
	DJNZ	.LOOP
	RET

; Scripted source for ESP_TCP_TEST_READER.
TEST_READ_BYTE
	PUSH	HL
	LD	HL,(WIFI.INPUT_LEFT)
	LD	A,H
	OR	L
	JR	Z,.EMPTY
	DEC	HL
	LD	(WIFI.INPUT_LEFT),HL
	LD	HL,(WIFI.INPUT_PTR)
	LD	A,(HL)
	INC	HL
	LD	(WIFI.INPUT_PTR),HL
	POP	HL
	LD	C,A
	AND	A
	RET
.EMPTY
	POP	HL
	SCF
	RET

STAGE		DB 0
LAST_BC		DW 0
IN_BACK2BACK	DB "+IPD,0,3:ABC+IPD,0,3:DEF"
IN_BACK2BACK_LEN EQU $-IN_BACK2BACK
IN_MIXED	DB "+IPD,0,3:ABC+IPD,1,3:UVW"
IN_MIXED_LEN	EQU $-IN_MIXED
IN_DATA_CLOSE	DB "+IPD,1,4:TAIL",13,10,"1,CLOSED",13,10
IN_DATA_CLOSE_LEN EQU $-IN_DATA_CLOSE
IN_SPLIT	DB "+IPD,1,6:ABCDEF"
IN_SPLIT_LEN	EQU $-IN_SPLIT
EXP_ABCDEF	DB "ABCDEF"
EXP_ABCUVW	DB "ABCUVW"
EXP_TAIL	DB "TAIL"

	MODULE WIFI
RS_BUFF		EQU 0xD000
INPUT_PTR	DW 0
INPUT_LEFT	DW 0
PAUSE_OPEN_COUNT DB 0
RESUME_OPEN_COUNT DB 0
UART_WAIT_RS
	SCF
	RET
UART_READ
	XOR	A
	RET
UART_TX_STRING
	OR	A
	RET
UART_TX_BUFFER
	OR	A
	RET
UART_TX_CMD
	XOR	A
	RET
UART_EMPTY_RS
	RET
UART_SET_DATA_RX_MODE
	RET
UART_SET_DATA_RX_MODE_OPEN
	RET
UART_RX_RESUME
	RET
UART_RX_RESUME_OPEN
	PUSH	HL
	LD	HL,RESUME_OPEN_COUNT
	INC	(HL)
	POP	HL
	RET
UART_RX_PAUSE
	RET
UART_RX_PAUSE_OPEN
	PUSH	HL
	LD	HL,PAUSE_OPEN_COUNT
	INC	(HL)
	POP	HL
	RET
	ENDMODULE

	MODULE ISA
OPEN_COUNT	DB 0
CLOSE_COUNT	DB 0
ISA_OPEN
	PUSH	HL
	LD	HL,OPEN_COUNT
	INC	(HL)
	POP	HL
	RET
ISA_CLOSE
	PUSH	HL
	LD	HL,CLOSE_COUNT
	INC	(HL)
	POP	HL
	RET
	ENDMODULE

	MODULE WCOMMON
CANCELLED	DB 0
CHECK_CANCEL_IN_ISA
	OR	A
	RET
	ENDMODULE

	MODULE UTIL
STRCMP
	SCF
	RET
UTOA
	RET
DELAY
	RET
DELAY_1MS
	RET
	ENDMODULE

	INCLUDE "esp_tcp.asm"
	INCLUDE "esp_tcp_multi.asm"

	END TEST_START
