; Host-side regression harness for the actual NETUP busy-response retry loop.
; Run through tools/test-netup-busy.sh.

	DEVICE NOSLOT64K

RES_OK				EQU 0
RES_ERROR			EQU 1
RES_BUSY			EQU 9
NETUP_BUSY_RETRIES		EQU 10
NETUP_BUSY_DELAY		EQU 500

TEST_RESULT			EQU 0xC000
TEST_RESPONSE			EQU 0xC100

	ORG 0x4000

TEST_START
	XOR	A
	LD	(TEST_RESULT),A

	; A normal command succeeds after three transient busy replies.
	LD	A,3
	CALL	TEST.RESET
	LD	HL,TEST.CMD
	LD	BC,2000
	CALL	MAIN.SEND_CMD_BUSY_TIMEOUT
	AND	A
	JP	NZ,FAILED
	LD	A,(TEST.CALL_COUNT)
	CP	4
	JP	NZ,FAILED
	LD	A,(TEST.DELAY_COUNT)
	CP	3
	JP	NZ,FAILED
	LD	A,(TEST.BAD_ARGS)
	AND	A
	JP	NZ,FAILED

	; A dirty runtime buffer must still end exactly after the assembled CRLF.
	; The former append helper did not copy the final zero, so UART_TX_STRING
	; continued transmitting 0xA5 bytes as a second input line.
	LD	HL,TEST.CMD_BUFFER
	LD	DE,TEST.CMD_BUFFER+1
	LD	BC,TEST.CMD_BUFFER_SIZE-1
	LD	(HL),0xA5
	LDIR
	LD	HL,TEST.CMD_BUFFER
	LD	DE,TEST.CMD_PREFIX
	CALL	MAIN.APPEND_STR
	LD	IX,TEST.CMD_SSID
	CALL	MAIN.APPEND_IX_STR
	LD	DE,TEST.CMD_SUFFIX
	CALL	MAIN.APPEND_STR
	LD	A,(HL)
	AND	A
	JP	NZ,FAILED
	INC	HL
	LD	A,(HL)
	CP	0xA5
	JP	NZ,FAILED
	LD	HL,TEST.CMD_BUFFER
	LD	DE,TEST.CMD_EXPECTED
	LD	B,TEST.CMD_EXPECTED_LEN
.COMPARE_CMD
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAILED
	INC	DE
	INC	HL
	DJNZ	.COMPARE_CMD

	; Exhausting the ordinary busy budget returns RES_BUSY deterministically.
	LD	A,0xFF
	CALL	TEST.RESET
	LD	HL,TEST.CMD
	LD	BC,2000
	CALL	MAIN.SEND_CMD_BUSY_TIMEOUT
	CP	RES_BUSY
	JP	NZ,FAILED
	LD	A,(TEST.CALL_COUNT)
	CP	NETUP_BUSY_RETRIES+1
	JP	NZ,FAILED
	LD	A,(TEST.DELAY_COUNT)
	CP	NETUP_BUSY_RETRIES
	JP	NZ,FAILED
	LD	A,(TEST.BAD_ARGS)
	AND	A
	JP	NZ,FAILED

	; A non-busy ESP error is terminal and must not be retried.
	XOR	A
	CALL	TEST.RESET
	LD	A,RES_ERROR
	LD	(TEST.FORCED_RESULT),A
	LD	HL,TEST.CMD
	LD	BC,2000
	CALL	MAIN.SEND_CMD_BUSY_TIMEOUT
	CP	RES_ERROR
	JP	NZ,FAILED
	LD	A,(TEST.CALL_COUNT)
	CP	1
	JP	NZ,FAILED
	LD	A,(TEST.DELAY_COUNT)
	AND	A
	JP	NZ,FAILED

	JP	TEST_DONE

FAILED
	LD	A,1
	LD	(TEST_RESULT),A

TEST_DONE
	HALT

	MODULE TEST

; In: A = number of busy replies before success.
RESET
	LD	(BUSY_BEFORE_OK),A
	XOR	A
	LD	(FORCED_RESULT),A
	LD	(CALL_COUNT),A
	LD	(DELAY_COUNT),A
	LD	(BAD_ARGS),A
	RET

CMD
	DB "AT+CWJAP=\"test\",\"test\"",13,10,0
CMD_PREFIX
	DB "AT+PING=",34,0
CMD_SSID
	DB "8.8.8.8",0
CMD_SUFFIX
	DB 34,13,10,0
CMD_EXPECTED
	DB "AT+PING=",34,"8.8.8.8",34,13,10,0
CMD_EXPECTED_LEN	EQU $-CMD_EXPECTED
CMD_BUFFER
	DS 64,0
CMD_BUFFER_SIZE	EQU $-CMD_BUFFER

BUSY_BEFORE_OK	DB 0
FORCED_RESULT	DB 0
CALL_COUNT	DB 0
DELAY_COUNT	DB 0
BAD_ARGS	DB 0

	ENDMODULE

	MODULE WIFI

RS_BUFF	EQU TEST_RESPONSE

; Deterministic UART_TX_CMD stub with the real routine's register-preservation
; contract. It also verifies that every retry receives the original command
; pointer and timeout.
UART_TX_CMD
	PUSH	BC,DE,HL
	LD	A,(TEST.CALL_COUNT)
	INC	A
	LD	(TEST.CALL_COUNT),A
	LD	DE,TEST.CMD
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	LD	HL,2000
	OR	A
	SBC	HL,BC
	JR	Z,.ARGS_OK
.BAD
	LD	A,1
	LD	(TEST.BAD_ARGS),A
.ARGS_OK
	LD	A,(TEST.FORCED_RESULT)
	AND	A
	JR	NZ,.DONE
	LD	A,(TEST.BUSY_BEFORE_OK)
	AND	A
	JR	Z,.DONE
	DEC	A
	LD	(TEST.BUSY_BEFORE_OK),A
	LD	A,RES_BUSY
.DONE
	POP	HL,DE,BC
	OR	A
	RET	Z
	SCF
	RET

	ENDMODULE

	MODULE UTIL

DELAY
	LD	A,(TEST.DELAY_COUNT)
	INC	A
	LD	(TEST.DELAY_COUNT),A
	RET

	ENDMODULE

	MODULE MAIN

	INCLUDE "asciiz_append.asm"
	INCLUDE "netup_busy_retry.asm"

	ENDMODULE

	END TEST_START
